### ISSUE TITLE
Item still "craftable" after removing pattern

### ISSUE THREAD

**Issue by RammyT** [Divine-Journey-2/main#148]
**Modpack version:**
beta

**Description:**
Removing a pattern from your ME system will leave the item showing as craftable in Terminals, until you unload your ME system or turn it off/on.

**Steps to reproduce:**
Set up small ME system with at least one Interface and one Molecular Assembler on it.
Make a random pattern and place it in the Interface and remove it again.
Open a Terminal and see it still being craftable.

**Expected behavior:**
When the pattern is removed from the Interface, the item shouldn't be shown as craftable anymore.

**Comment by Atricos** [comment]
I believe the new AE2 Trousers Edition v46 fixes this issue: https://github.com/PrototypeTrousers/Applied-Energistics-2/releases
v47 has been included in the 2.5.0 version of the pack: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
