### ISSUE TITLE
Recurrent Complex mod causing a crash on servers

### ISSUE THREAD

**Issue by legendcrazyman** [Divine-Journey-2/main#158]
Modpack version:
2.0.0 Release

Description: Recurrent Complex causes the server to crash instantly (from reading posts about this problem on Discord some servers don't crash but lag very intensely) upon loading a chunk I would assume has a reccurent complex structure. The console states that a newly loaded chunk in dimension 0 is causing cascading worldgen lag.

Steps to reproduce:

1. Create a server with 10 GB RAM / Forge 1.12.2 server
2. Get four players (8 GB minimum client RAM) to run around the overworld loading chunks. (After doing a few quests in the beginning)
3. Server crashes upon finding one of these broken recurrent complex chunks.

![console](https://user-images.githubusercontent.com/89759794/131279986-4c5c5e6f-ee34-4914-a1b3-9e6a0f8e88d2.png)

**Comment by JadedMagic5** [comment]
This crash applies to both SP and MP, similar to what OP says; getting unlucky and finding one of these structures will crash the server. The Blurp Club has met this issue as well and refraining from decreasing the structure spawn rate, this is what we did to soft fix the crash, it will lag but not crash. These seem to have worked over the course of loading 5million chunks with pregenerators.

Pregen the world, it will still crash during pregen but will chip away at the chunks and eventually load and get through this.

In server.properties, we set max-tick-time=600000(10min) from the default 60000(1min) so the server has time to load all cascading chunks. The setting change will allow the server to not respond for 10minutes before force closing.

**Comment by Atricos** [comment]
So does anyone know which structure(s) cause this issue?

**Comment by Atricos** [comment]
@legendcrazyman Can you provide a crash report please?

**Comment by tjsd** [comment]
Here is some reppors that I get with world-gen:
https://termbin.com/wntq9
https://termbin.com/2yku

**Comment by tjsd** [comment]
I changed the tick-time to -1 in server.properties and it doesn't crash now, but here is what I got when the console started spamming again: 
https://pastebin.com/aYdF0qrp

**Comment by Tylerun** [comment]
https://github.com/Ivorforce/RecurrentComplex/issues/467

This has been an active issue for a long time.

**Comment by Atricos** [comment]
I have lowered the spawn rate of all overworld structures and completely disabled some structures (Big Clockwork Site, Big Pyramid, Gigantic Tree, Gigantic Tree 1, Small Clockwork Site, Statue Temple, Stone Maze Big, Temple Pyramid, Temple Pyramid 1, Veldt Bath, Wood Wall Remnants) in 2.1.0.

We'll see if this helps.
I'm not closing the issue yet, because I'm not certain that this does the job.

**Comment by Tylerun** [comment]
If it doesn't i checked the changelogs looks like not much was done between the version you have and the 1 version below it except its not broken

**Comment by Atricos** [comment]
I haven't gotten any Recurrent Complex-related complaints since 2.1.0, so I'm pretty confident this has been fixed.
