### ISSUE TITLE
Switch Extended Crafting to updated fork

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Divine-Journey-2/main#159]
**Modpack version:**
Imported from Github from the `02d0e7c` commit

**Describe the request:**
Hello, I noticed that you had included Extended Crafting in your modpack and wanted to make a recommendation to switch to the fork of Extended Crafting (Located here: [Curseforge](https://www.curseforge.com/minecraft/mc-mods/extended-crafting-omnifactory-edition), [GitHub](https://github.com/OmnifactoryDevs/ExtendedCrafting)) as this fork fixes a couple issues present in the 1.12.2 version of Extended Crafting, such as a dupe bug with the automation interface and some issues with Crafttweaker support, since Extended Crafting is no longer being updated for 1.12.2. As a disclaimer, I do work on this fork.

**Reasons why this should be added:**
This fork fixes an existing dupe bug with the Automation Interface, is more precise with NBT in crafttweaker recipes in the crafting tables, and fixes a slight issue where the quantum compressor could get stuck when shift clicking items in.

**Describe alternatives you've considered:**
The alternative here would simply not be replacing Extended Crafting with its forked version.

**Additional context:**
Please let me know if you have any questions about the fork.

**Comment by KleinGrrmpf** [comment]
This might not be possible because CurseForge doesn't accept every fork of every mod in a modpack. There is a list of forked mods that are not on CurseForge that are still allowed in modpacks (Like AE2 Trouser's Edition) but this fork might not be on that list.

**Comment by Zenthae** [comment]
it's used by Omnifactory so it should be allowed

**Comment by WaitingIdly** [comment]
Its literally a mod on curseforge https://www.curseforge.com/minecraft/mc-mods/extended-crafting-omnifactory-edition

**Comment by Atricos** [comment]
I have switched to the OmniFactory version in 2.1.0.
