### ISSUE TITLE
Warning about texture errors for players on linux

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Divine-Journey-2/main#160]
**Modpack version:**
Imported from Github, off of commit `02d0e7c`

**Description:**
During loading of the pack, there are some warnings about textures not being processed for players that are playing on linux because of a file capitalization difference between the files names and the declared files in the resources. I have gathered these warnings into a pastebin here: [Pastebin](https://pastebin.com/wR4rjbry)

**Steps to reproduce:**
1. Launch the pack
2. Open up `latest.log` and search for `linux`
3. See the errors

**Expected behavior:**
I expect that there will be no errors in the log about possible texture errors for players using linux.

**Comment by Lgmrszd** [comment]
Hello, linux player here. I can indeed confirm that those items look like this:
![missing_texture](https://user-images.githubusercontent.com/16291541/131400092-e475ed55-fc4a-4492-8571-ce657b9d556e.png)

**Comment by Atricos** [comment]
I changed all puzzle tile textures to lowercase in 2.1.0.
