### ISSUE TITLE
switch ore excavation with ftb ultimine

### ISSUE THREAD

**Issue by GrummDado** [Divine-Journey-2/main#161]
The reason being the "merge stone" setting in ultimine which will mine the ore vein even if the stone type is different, since underground biomes is a thing, it will be much useful.

here's an example

https://user-images.githubusercontent.com/20334454/131313726-52072702-9c95-42c4-8242-c1f0d3e57d8c.mp4

**Comment by Ludi87** [comment]
I prefer OreExcavation since you can make your own shapes. (If it's enabled, I didn't check)

**Comment by KleinGrrmpf** [comment]
it is
