### ISSUE TITLE
Remove Just Enough Energistics

### ISSUE THREAD

**Issue by Caedis** [Divine-Journey-2/main#165]
**Modpack version:**
2.0.1

**Describe the request:**
Remove the mod Just Enough Energistics

**Reasons why this should be added:**
JEE's usage was implemented (and improved upon) by ProtoTypeTrousers in their fork of AE2 and is overridden by JEE's implementation.

**Comment by Atricos** [comment]
Removed Just Enough Energistics in 2.1.0.
