### ISSUE TITLE
infinite items available early through the creative item buffer.

### ISSUE THREAD

**Issue by BigKeanerBigWeaner** [Divine-Journey-2/main#167]
The creative item buffer fro ender io is available early in the creative item progression, but when items are placed into it and the auto output is set to an inventory, infinite items are available much earlier than the creative chest.
![2021-08-30_12 59 00](https://user-images.githubusercontent.com/68492310/131376482-a434608d-c806-4c94-a16e-b7fd0f04a877.png)

**Comment by Atricos** [comment]
Moved the Creative Buffer to be available after the Creative Chest, and the AE2 Creative Energy Cell now takes a Creative Capacitor Bank instead. Also moved around quests in Chapter 29 because of this. Available in 2.1.0.
