### ISSUE TITLE
Evil craft display stands kicks me to multiplayer screen when crafted

### ISSUE THREAD

**Issue by BananaLord12** [Divine-Journey-2/main#168]
**Modpack version:**
2.0.1

**Java version:**
1.8.0_51

**Description:**
I wanted to make a stand from evil craft to display the bags that contain the meaning of life

**When did the crash happen?**
When I placed the items in a crafting station and tried to make like a couple

**Steps to reproduce:**
1. Open game and load world
2. Place a crafting station
3. Craft the display stand from evilcraft
4. Game kicks you to multiplayer screen or single player, only tested it on server

**Minecraft crash report:**

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
I dedicated 6 gigs while I have 8 gigs.

**Screenshots:**

**Additional context:**

**Comment by Atricos** [comment]
I just tested the Acacia version (the first one in JEI) and it worked. There are ton of versions, which one were you using?

**Comment by BananaLord12** [comment]
i was using version 2.0.1 when i was about to make the item it did just kicked me out of the server and i assumed that crashed my game but when i returned back to the server, it was still there, i did make the oak version of the stand, but it could be just a random thing, and i cant exactly provide a crash report as it just kicked me and i was debating to either place it under crash or bug

**Comment by Atricos** [comment]
**Can anyone else try to reproduce this on a server?** And if you have access to the server files, can you see if it creates a crash report or not?

I just have nothing to work with. :(

**Comment by BananaLord12** [comment]
It appears to be me, we can close this as it was weird for me
