### ISSUE TITLE
Nether Quartz pickaxe is not locked

### ISSUE THREAD

**Issue by HeyImCarlo4** [Divine-Journey-2/main#171]
**Modpack version:**
2.0.1

**Description:**
Nether Quartz pickaxe is not locked so u can just skip a part of tinker's construction

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Open crafting table and craft the item (https://cdn.discordapp.com/attachments/708998228212842516/882004027859169290/2021-08-30_22.48.35.png)

**Expected behavior:**
I expected to see the crafting locked because u can skip a part of tinker construction

**Screenshots:**
https://cdn.discordapp.com/attachments/708998228212842516/882004027859169290/2021-08-30_22.48.35.png

**Comment by Atricos** [comment]
I found the same issue with the Certus Quartz and Black Quartz Pickaxe as well.

I changed the mining level of all 3 to Iron in 2.1.0.

**Comment by KleinGrrmpf** [comment]
I'm not sure if this really is a bug. You can also make vanilla iron pickaxes just fine (which also have mining level diamond). The mining level diamond says that the pickaxe can mine everything that is as "hard" as diamond ore. So you can't mine obsidian with it (which would be the skip that you described).
