### ISSUE TITLE
Grammar error on a tip

### ISSUE THREAD

**Issue by sarperen** [Divine-Journey-2/main#172]
**Location:**
It is in the tips during loading screen
![image](https://user-images.githubusercontent.com/43860774/131418596-3cfeab76-93f7-4e3c-9d1a-63b2cdde9130.png)

**Exact fix:**
The first sentence doesn't exactly make sense. Changing "didn't" in to "don't" would fix it.

**Comment by sarperen** [comment]
For more context, the current tip sounds like you used to not have to play DJ1, but now you have to.

**Comment by Atricos** [comment]
Changed "didn't" to "don't" in 2.1.0.
