### ISSUE TITLE
Change alwaysRecreateAspectFromItemStackFile to false (in ThaumicJEI config)

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#175]
**Modpack version:**
2.1.0

**Describe the request:**
If this isn't already the case, add a fully generated "thaumicjei_itemstack_aspects.json" file to the files you download (if generated you can find it in the configs folder).
But definitely set the config option "alwaysRecreateAspectFromItemStackFile" to false. In my opinion, this is fine because there are no new items being added to the pack.

**Reasons why this should be added:**
It makes the game less laggy in the 15 minutes that the json is generating and also prevents freezes.

**Comment by Atricos** [comment]
Some new items might still be added to the game in the future. I guess I'll just have to not forget to change it back for 1 launch to generate their aspect stacks too... We'll see.

**Comment by KleinGrrmpf** [comment]
You can also just delete the file if you want to generate a new json file

**Comment by Atricos** [comment]
Alright, you've convinced me.

I changed the setting to false in 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
