### ISSUE TITLE
Engineers tools quests can be completed with the wrong tool

### ISSUE THREAD

**Issue by nanonator102** [Divine-Journey-2/main#176]
**Modpack version:**
2.0.0

**Description:**
The quest "Snippidy-snap!" under "4. Immerse Yourself" is triggered by the Engineers Hammer.
The quest "An Engineer's Must-Have" under "4. Immerse Yourself" is triggered by the Engineer's Wire Cutters

**Steps to reproduce:**
1. Ensure your inventory does not have the Engineers Hammer or the Engineers wire cutters
2. Obtain the opposite item expected for the quest (Wire Cutters for Hammer quest, Hammer for wire cutters quest)
3. Submit the quest

**Expected behavior:**
Both quests can only be completed with the respective item.

**Comment by Atricos** [comment]
Fixed in 2.2.0, now both quests only accept the correct tool!
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
