### ISSUE TITLE
Add more info in quest.

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#177]
Maybe add in #892 that you can use yellorium instead of lava. You can very easily get two blocks of it and it gives 1.7 times more energy.

**Comment by RammyT** [comment]
This is quest #892, are you sure this is what you meant?
![image](https://user-images.githubusercontent.com/72321012/131639132-326d6e6b-3fb5-4364-968a-5ffe8389beb5.png)

**Comment by Bosfik** [comment]
> This is quest #892, are you sure this is what you meant?
> ![image](https://user-images.githubusercontent.com/72321012/131639132-326d6e6b-3fb5-4364-968a-5ffe8389beb5.png)

Oh, I'm sorry. The quest was about thermoelectric generator. Can't check its number now.

**Comment by itech2018** [comment]
> > This is quest #892, are you sure this is what you meant?
> > ![image](https://user-images.githubusercontent.com/72321012/131639132-326d6e6b-3fb5-4364-968a-5ffe8389beb5.png)
> 
> Oh, I'm sorry. The quest was about thermoelectric generator. Can't check its number now.

I think the quest your on about is 893

**Comment by Atricos** [comment]
Added the info to the Thermoelectric Generator quest, that Yellorium Blocks work even better.

Fix in version 2.2.0:
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
