### ISSUE TITLE
Replacement for LagGoggles/TickCentral

### ISSUE THREAD

**Issue by Caedis** [Divine-Journey-2/main#178]
**Modpack version:**
2.1.1

**Describe the request:**
With the bug that was caused by LG/TickCentral, might I suggest swapping to spark?  

[Mod page](https://www.curseforge.com/minecraft/mc-mods/spark)

**Comment by Atricos** [comment]
As suggested, I added Spark to the pack in 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
