### ISSUE TITLE
Server crash with Enthralled Dramcryx

### ISSUE THREAD

**Issue by Z4RM** [Divine-Journey-2/main#181]
**Modpack version:**
2.1.1

**Java version:**
8 but I don't know exactly, It's an only Minecraft server.

**Description:**
A mob kill me and the server instant crash.

**When did the crash happen?**
When __Enthralled Dramcryx__ of *DivineRPG* kill me.

**Steps to reproduce:**
1. Find a Enthralled Dramcryx (I don't know if spawn it do the same but I think).
2. Change gamemode to surival if if you are not already.
3. Wait the mob kill you.
4. The server crashes.

**Minecraft crash report:**
I attach a file because the crash report is to big to be in pastebin....
[crash-2021-08-31_20.06.54-server.txt](https://github.com/Divine-Journey-2/main/files/7086078/crash-2021-08-31_20.06.54-server.txt)

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
The server have 12 GBs of RAM.

**Comment by Atricos** [comment]
I tested this on a Singleplayer world, it didn't cause a crash there.

Questions:
- Did you try it on a server? (I know you said the server crashed, but that could still mean the SP internal server, so I'm just making sure.)
- Can you reproduce the issue? Does this *always* happen?

**Comment by WaitingIdly** [comment]
Could not reproduce. Until further information or corroboration is provided, this will be closed.
