### ISSUE TITLE
Congealed blood usage - recipe conflict

### ISSUE THREAD

**Issue by Krollbotid** [Divine-Journey-2/main#182]
**Modpack version:**
2.0.1

**Description:**
Recipe conflict. Doesn't affect playthrough, and I really found it accidentally, when was looking usage of congealed blood. I know I'm using old version of the modpack, but fixing of this recipe conflict wasn't stated in announcement.
![image](https://user-images.githubusercontent.com/37172495/131562972-3b5dbde1-484c-4068-8b34-6b4357303544.png)

**Steps to reproduce:**
1. Get into the world
2. Check usage of congealed blood balls

**Expected behavior:**
Since purple block has it's own recipe (craft from it's own type of slimeballs). I expect that upper recipe shouldn't exist.

**Additional context:**
Nothing

**Comment by Atricos** [comment]
Fixed in 2.2.0, now the Congealed Slime Block crafts in a different shape.
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
