### ISSUE TITLE
Text Out of Bounds Error in Quest 776

### ISSUE THREAD

**Issue by M0RGaming** [Divine-Journey-2/main#184]
**Modpack version:**
2.0.1

**Description:**
While looking ahead at the upcoming quests, I noticed that quest 776 had a Text out of bounds error as one of the requisites.

**Steps to reproduce:**
1. Open Quest Book
2. Navigate to Chapter 29, "Getting Creative"
3. Hover over quest 776, "Time and time again you gotta craft something"
4. Error is visible

**Screenshots:**
![Screen Shot 2021-08-31 at 3 43 47 PM](https://user-images.githubusercontent.com/13577339/131580217-703695f5-9246-4e38-be42-800472742fa6.png)

**Comment by Atricos** [comment]
That's literally the name of the quest. It's a joke for the Essence of Dimensionality.

**Comment by M0RGaming** [comment]
Ahh, that makes sense lol. The darker red threw me off.
