### ISSUE TITLE
Nerf Typesetting Table and Printing Press recipes

### ISSUE THREAD

**Issue by l4ssc** [Divine-Journey-2/main#185]
**Modpack version:**
2.0.0

**Describe the request:**
The Typesetting Table and Printing Press from BiblioCraft can be used to duplicate enchantment books from a single enchantment book (potentially infinitely with mending and an Ender IO tank with Liquid XP) and currently their recipes are unchanged, meaning that almost as soon as you get steel, you can infinitely copy any enchantment :^) it is self-explanatory how potentially OP that is.

**Reasons why this should be changed:**
- Other extra enchantment-related functionality (the DE disenchanter, OB auto enchantment table, EIO enchanter, IF stuff, etc) has been gated similarly and most of those aren't even close to as powerful in comparison

**Describe alternatives you've considered:**
- Just disabling the printing press and typesetting table altogether. I do not have any real qualms with this alternative, but I think keeping it later-game would be fine as well given the DE disenchanter is still a thing

**Additional context:**
Current recipes: 
![image](https://user-images.githubusercontent.com/72284051/131604874-b9c88535-c27f-4954-8e2d-b72724c093b3.png)
![image](https://user-images.githubusercontent.com/72284051/131604898-1f6c654b-fbaf-40de-b564-6524c90e499e.png)
![image](https://user-images.githubusercontent.com/72284051/131604939-14354f5d-bebd-41bd-9db1-f0afde705381.png)

**Comment by Uchiwars** [comment]
i mean, it's not THAT broken cuz it costs xp and materials everytime! i'm trying to create a Looting 3 press but it costs 40 levels! it's not cheap at all
and it has 3 durability, so in comparison to the late game enchant stuff it's not that op

**Comment by thecodingchicken** [comment]
I agree.  This probably should be gated a bit.  However, due to the fact that using it early-game can be quite expensive xp-wise, I think it is mostly fine.  If I take a better look at it, I'll probably just make things a bit more expensive, and potentially gate it a bit

**Comment by Waisse** [comment]
It costs a ton of xp, it's fine.

**Comment by ToasterKoishi** [comment]
It should be noted that the title of this issue should be "Buff" the recipes, not "Nerf" them. Nerf the *recipes* means that you're requesting for the recipes to be made easier. Or you could just delete the word "recipes" from the issue title, and that would make the title mean "nerf the item," which makes sense since you're asking for the items to be "worse" (which could mean that they have a harder recipe).

In the end the actual adjustment to the difficulty of this item is up to Atri's judgment.

**Comment by Atricos** [comment]
Gated all of these until Chapter 11. Fix is in version 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
