### ISSUE TITLE
Outdated Quest description: 3 → 4 items

### ISSUE THREAD

**Issue by cow-mc** [Divine-Journey-2/main#191]
**Location:**
4th Chapter, Quest 903: "Onwards, to Moldol!" description: `Craft the 3 most essential Molds! [...]`
fc09fe8d27c0132ee231aec1ea70ee6fae0421ec added the Gear Mold to the required items, so there are now 4 molds in total.

**Exact fix:**
> Craft the ~~3~~ 4 most essential Molds!

**Comment by Atricos** [comment]
Fixed in 2.2.0, now it says `"4 most essential Molds"`:
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
