### ISSUE TITLE
Cant craft red coal with block of charcoal

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#197]
**Modpack version:**
2.2.1

**Description:**
Cant craft red coal with block of charcoal (chisel), the current recipe is the actually additions block of charcoal which isnt craftable

**Comment by thecodingchicken** [comment]
Working on it right now

**Comment by Atricos** [comment]
Fixed in 2.2.0 with the exact fix @thecodingchicken provided.
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
