### ISSUE TITLE
EnderIO conduits don't work (incompatibility with Tick Central and/or Lag Goggles)

### ISSUE THREAD

**Issue by desht** [Divine-Journey-2/main#198]
**Modpack version:**
2.1.0

**Description:**
EnderIO conduits are broken; no rendering, don't connect, GUI doesn't open properly

**Steps to reproduce:**
1. Open the game
2. Place an EnderIO item conduit
3. Notice it doesn't render, doesn't connect to any inventories and it's nearly impossible to open the GUI.

**Expected behavior:**
For conduits to work.

**Screenshots:**
See screenshots in issue I linked below.

**Additional context:**
This is a known incompatibility with EnderIO & Tick Central and/or Lag Goggles, both of which are in DJ2.  See https://github.com/SleepyTrousers/EnderIO/issues/5470 - this was fixed 10 months ago.  The problem is that DJ2 seems to be shipping a much older version of EnderIO for some reason..?  Don't know if there's a particular reason for that, but it doesn't work properly.

**Comment by WaitingIdly** [comment]
Update to 2.1.1, its fixed there

**Comment by desht** [comment]
Yeah, I just realised, sorry about that.
