### ISSUE TITLE
Grating/Iron grate have the same recipes.  

### ISSUE THREAD

**Issue by thecodingchicken** [Divine-Journey-2/main#200]
**Modpack version:**
2.0.1

**Description:**
Galacticraft Grating(<galacticraftcore:grating>) and Quark Iron Grates(<quark:grate>) share the same recipe.  

**Steps to reproduce:**
1. (Assumes game is open and in a world)
2. Open up jei and search for iron bars.  
3. Press u and view the recipes.  Involved recipes are included.  
![image](https://user-images.githubusercontent.com/29822509/131897664-0c4c5657-e898-4e29-aad6-6c5ebd771e11.png)
![image](https://user-images.githubusercontent.com/29822509/131897695-0bca57e5-36fe-43c2-9053-11de8f2553d6.png)

**Expected behavior:**
They have different recipes.  In addition, I would expect the quantity to remain the same.  

I will open a pull request shortly to fix this.

**Comment by Atricos** [comment]
Galacticraft Iron Grating now also uses Compressed Steel, making the recipes different.

Fixed in version 2.2.0:
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
