### ISSUE TITLE
Reenable magma slime islands in the nether

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#204]
**Modpack version:**
2.1.1

**Describe the request:**
Reenable magma slime islands in the nether/
I:slimeIslandBlacklist

**Reasons why this should be added:**
for magma slime crystals

**Comment by King65868** [comment]
Magma slime islands aren’t disabled though?

**Comment by Atricos** [comment]
The configs do say that Slime Islands are disabled in dimension `-1`, but apparently Magma Slime Islands are different, and they do spawn.
