### ISSUE TITLE
internal server error in single player world while fighting baykok

### ISSUE THREAD

**Issue by Emetain** [Divine-Journey-2/main#206]
**Modpack version:**
2.1.1

**Description:**
Internal server crashed while fighting baykok. After relogging the internal server crashed again. This happened after dying a lot or when baykok went into the water.

**Steps to reproduce:**
1. Get into a world
2. Summon the fight against baykok
3. Fight baykok
4. Let baykok swim
5. Die a lot
6. Internal server crash

**Expected behavior:**
Internal Server crashes when baykok is swimming and you respawn

**Comment by Atricos** [comment]
Please provide a crash report.

**Comment by WaitingIdly** [comment]
Did not provide a crash report.
