### ISSUE TITLE
Ender Core's tooltip references wrong item

### ISSUE THREAD

**Issue by JadedMagic5** [Divine-Journey-2/main#211]
**Location:**
Tooltips | Mod: Ender Utilities | All 3 Inactive Ender Cores

**Exact fix:**
Change "Ender Crystal" to "End Crystal"

**Comment by Atricos** [comment]
These are base tooltips added by Ender Utilities.

I could remove them and readd them correctly, but they would display at the bottom, below even the internal item name.

I don't think this is that big of an issue, as it's still clearly understandable.
