### ISSUE TITLE
End steel armour

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#219]
**Modpack version:**
2.1.1

**Describe the request:**
End steel armour is cheaper than dark steel (ignoreing the extra reqiurement of endstone), its not as much of armour increase comapred to stellar armour but it being so much cheaper. maybe replace the diodes with the dark steel pieces

**Comment by Atricos** [comment]
Changed the recipes of the End Steel Armor pieces, now they're more difficult *and* take Dark Steel Armor pieces in their recipes.

Also made Stellar Armor pieces take End Steel Armor pieces in their recipes.

Fix is in version 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
