### ISSUE TITLE
Progression skip by getting iridium early via the Immersive Engineering Excavator

### ISSUE THREAD

**Issue by ToasterKoishi** [Divine-Journey-2/main#220]
The platinum mineral vein has a 12.5% rate of giving iridium, which allows you to get it several chapters earlier than intended. This may result in being able to get some things earlier than intended, although I have not personally checked so I am not sure if it really has a long-term effect.

There's a user on Discord currently investigating how far they can skip by getting Iridium early, which apparently has gotten them Steaming Restonia crystals via quest reward while still only being in the IF Chapter. [https://discord.com/channels/691927762755387402/881852587203231775/883534650172145664](https://discord.com/channels/691927762755387402/881852587203231775/883534650172145664) I may or may not update this ticket with more information later.

Secondly, this is also a much faster way of getting Iridium than using the IF Laser Drill, which may have an impact on balance.

**Comment by Zcey1** [comment]
Additionally there is more skipping possible via using the iridium to make osmiridium and then completing the "Giga Storage" quest (making a 1024k storage component) that has a reward of Steaming Restonia to enable more progression skipping.

**Comment by Atricos** [comment]
The `config/immersiveengineering.cfg` file only allows for disabling Bauxite, Copper, Lead, Nickel, Silver and Uranium veins. Do you know where to disable the others?

**Comment by ZephyrWindSpirit** [comment]
Might only be for using ie ores in their machines, but cofh/thermalexpansion/common.cfg under plugins?

**Comment by Atricos** [comment]
Ah, nevermind, I found it. There is CraftTweaker support for this!
https://docs.blamejared.com/1.12/en/Mods/Immersive_Engineering/CraftTweaker_Support/Excavator/Excavator/

**Comment by Atricos** [comment]
Disabled Platinum and Iridium Veins from being Excavatable. I believe this only changes new chunks though, but could be wrong.

Fix available in version 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
