### ISSUE TITLE
Roots Pyre eating items

### ISSUE THREAD

**Issue by SolarKnight202** [Divine-Journey-2/main#221]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.1.1

**Description:**
The pyre from Roots eats items to automatically continue the crafting ritual and then never outputs anything. the first ritual (which has to be started by hand ofc) will output as normal, but all rituals after will not actually output, resulting in the input materials being wasted.

**Steps to reproduce:**
1. Get into a world
2. Place the require items to craft something in the pyre, as well as extras in a chest underneath (e.g. charred stone)
3. Start the ritual with a flint and steel.
4. The pyre will start crafting and immediately pull the required items for the next ritual. it will then output from the first ritual, immediately start the next ritual. No more items will be output after the first ritual.

**Expected behavior:**
Each time the pyre completes a ritual, it should output the items of said ritual.

**Screenshots:**
![Example](https://user-images.githubusercontent.com/51036245/132080785-e3d9c177-4590-44a7-97fd-d1cf15aed658.png)

**Additional context:**

**Comment by WaitingIdly** [comment]
Fixed due to Roots update in #210
