### ISSUE TITLE
Add Uppers

### ISSUE THREAD

**Issue by Retrogamesnl** [Divine-Journey-2/main#222]
**Modpack version:**
2.1.1

**Describe the request:**
I would like to see the popular mod uppers be added to the modpack.

**Reasons why this should be added:**
Bro they go up

**Describe alternatives you've considered:**
snad would also be great or even pixelmon

**Additional context:**
![image](https://user-images.githubusercontent.com/43819938/132090075-59f20131-660a-4bfd-95e4-d037e0427c1e.png)

**Comment by Atricos** [comment]
No. Some of the early quests reward you with Item Conduits, they should be more than enough before you can get Itemducts and Item Conduits.

Is Pixelmon a joke btw....?
