### ISSUE TITLE
Lead Dust not smelting in Redstone Furnace

### ISSUE THREAD

**Issue by NLBlacky** [Divine-Journey-2/main#223]
**Modpack version:**
2.1.1

**Description:**
Lead Dust (Thermal Foundation) does not smelt in the Redstone Furnace (Thermal Expansion) but does work in the Alloy Smelter (Ender IO) while according JEI this should work in the Redstone Furnace.  

**Steps to reproduce:**
1. Get Lead Dust (can be gained from pulverizing Lead Ore in the Pulverizer (Thermal Expansion).
2. Try to place the Lead Dust in the Redstone Furnace (won't work)
3. Try to place the Lead Dust in any other furnace like the Alloy Smelter (this will work)

**Expected behavior:**
Lead Dust should be smeltable in the Redstone Furnace.

**Comment by Atricos** [comment]
Fixed in 2.2.0, now the Redstone Furnace does accept Lead Dust: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
