### ISSUE TITLE
immersive engineering weapons are underpowered

### ISSUE THREAD

**Issue by sdjjufdki** [Divine-Journey-2/main#224]
**Modpack version:**
2.1.1

**Describe the request:**
immersive engineering weaponry are underpowered compared to tinkers or divinerpg weapons at the same stage, dealing far less damage and using far more expensive ammo.

**Reasons why this should be changed:**
seeing as these weapons' recipes have been tweaked, it's reasonable for their damage output to be scaled to match the balance of divinerpg. this would also add some variety in combat options, as the chemthrower and the revolver are both unique weapons. 

**Describe alternatives you've considered:**
the immersive engineering configs allows tweaking of damage values of the railgun and individual revolver cartridges, however the chemthrower's damage cant be tweaked, only it's fluid consumption.

**Additional context:**
bow enchants scales their damage a lot (+150% at power 5), making them far better than ie weapons, which cant be enchanted. as well as this, tinkers construct offers powerful melee options.

**Comment by Waisse** [comment]
The railgun and armor-piercing bullets for the revolver can both pass through armor, I don't know what you're talking about. They're both niche weapons.

**Comment by sdjjufdki** [comment]
i'd agree if mobs had player level armor but currently the armor piercing niche isn't enough to make up for their lack of damage, seeing as most mobs dont even have armor and the ones that do have so little that high damage weapons could pierce through them anyway due to the vanilla armor reduction mechanic

**Comment by Waisse** [comment]
You're gonna have to bring some numbers because I think both the railgun and revolver are quite strong in the right situation. The railgun is perfectly serviceable with the zoom function over very long range, and the revolver can actually devastate from middle to close range with the right bullets. They're not exactly powerhouses but it just works.
Is it better than Tinker's nonsense? No, expect at... bypassing armor. I don't think it's fair to compare a mod about constantly evolving and customizable tools and weapons against a mod which has some cool gadgets to play around with. Overall IE is underpowered, this isn't new. Or perhaps Tinker's is too op? 
It's not just about balancing numbers, you're comparing apples to oranges. You said "immersive engineering weaponry are underpowered compared to tinkers or divinerpg weapons at the same stage". There is just one thing to consider thought. Tinker's and DivineRPG is a constantly evolving progression of gear, whereas your railgun/revolver won't upgrade and doesn't move in power once you got your upgrades. There is no good way to balance IE with these two mods really, but you are free to prove me wrong.
But please buff IE stuff, I don't want my party to laugh at me when I pull out my mining drill I can't even enchant.

**Comment by sdjjufdki** [comment]
i mean for one im comparing ie stuff to weaponry of the same stage in progression. so i compared the railgun to baykok's bow and wildwood bow, both with poewr 5, an enchantment literally given by the questbook (shadow bow apparently doesnt work with power so actually that is pretty bad). the living bow dealt 12 hearts per shot on average, while baykok's bow dealt 14. the railgun, on the other hand, deals 7.5 hearts with iron rods, 9 hearts with steel rods, and 12 with graphite electrodes. i can see someone being rich enough to fire iron/steel rods like they're dirt, but there is no chance any player at that stage of the game will have the resources to consistently fire electrodes, and even then its only on par with modded bows. as for the zoom mechanic, im pretty sure theres at least one mod that adds a zoom keybind.
now for the revolver, which i do admit deals decent damage with the right cartridges, namely, buckshot and dragons breath. but they're still far too expensive for their effect, especially with the apparently bugged mob spawning rates. and now that roots adds a spell that increases reach, the range of these cartridges is barely better than any melee weapon under the effect of said spell. and a tinkers katana made with materials of that stage without any modifiers and embossments can indeed do better in combat than a single revolver with dragon's breath cartridges, and again, thats without the modifiers and embossments. revolvers could indeed be dual wielded unlike melee weapons, but the cartidges are still too expensive to be practical, as opposed to the minimal maintenance costs of the other options ive brought up. and again, there isnt much mobs in the game that has enough armor in the first place for the armor piercing cartridge to be significant, so armor piercing isnt a valid point.
i have said at the start that these weapons are unique, which is why i want them to be a more solid option in the first place. they do have their niches, they are cool and interesting to use, but currently i just find them to provide subpar damage for their large costs, especially when less expensive and earlier options seems to work better.

**Comment by Waisse** [comment]
I'll be honest, this is an overarching problem with IE in general. The mod itself is underpowered. I'm all for a buff to IE but I'll wait for differing opinions.

**Comment by sdjjufdki** [comment]
i'll be real, if any one of these could get some enchants they would be well worth their cost, but i guess bluesunrize hate humanity too much for that to happen

**Comment by ToasterKoishi** [comment]
I agree that IE equipment is underpowered for their progression point and cost. It is kind of weird for the questbook to recommend them so heavily when there are so many better and cheaper choices in the pack. In particular the biggest issue with these three weapons (Revolver / Chemthrower / Railgun) is their extremely high ammunition cost. But even if that were offset (with custom recipes for example), they still do subpar damage compared to other weapons.

Suggestion: keep the ammunition cost high (or only slightly nerf it, but keep it higher than that of other weapons), but increase the damage significantly, to make it worth the cost of firing these weapons. Revolver should be on par with well-enchanted / well-built bows, railgun should probably do a crapton of damage (and maybe hold more power by default), and chemthrower should have its fuel usage reduced.

**Comment by sdjjufdki** [comment]
agree

**Comment by Atricos** [comment]
Buffed the Railgun in 2.3.0, and now deals 10x more damage (with all bullets), the Homing Bullet also deals an additional 2x more (20x in total). RF consumption is now only 200 RF per shot (down from 800 RF per shot). Additionally, the Chemthrower now consumes 10x less fluid and 32x less RF/tick.
