### ISSUE TITLE
Reduce the spawning of the Divine RPG "Frost" Mob in the overworld.

### ISSUE THREAD

**Issue by SPIDERBOY2012** [Divine-Journey-2/main#225]
**Modpack version:**
2.1.1

**Describe the request:**
The Divine RPG "Frost" Mob is very loud and the Spawn rate, if possible, should be heavily reduced in the overworld.

**Reasons why this should be changed:**
I Love to build my bases in snowy/cold biome but the Frost mob very frequently spawns in caves and above ground and creates loud explosion noises from far away. The Frost enemy can detect you through walls which makes it very hard to find and kill them.

**Describe alternatives you've considered:**
Turning the game to peaceful and back to hard gets rid of them for a short time but this is annoying to do every 5-10 minutes
Also, turning off the "Block" sounds in settings removes the explosion noises but I do like having my sounds on. 
Lighting up all the caves nearby could be a solution but its hard to do early game.

**Additional context:**
Thanks for reading :)

https://user-images.githubusercontent.com/90105913/132102374-71b935c8-0b39-419f-9858-c8db1d71a734.mp4

**Comment by Atricos** [comment]
Completely disabled the mob in 2.3.0. It was the only source of Tomatoes, but now Tomato Seeds generate in Dungeon chests instead.
