### ISSUE TITLE
Tinker's Construct Tools Do Not Mine Underground Biomes Blocks at Correct Speeds

### ISSUE THREAD

**Issue by GinFizzz** [Divine-Journey-2/main#226]
**Modpack version:**
2.0.1

**Description:**
Tinker's Construct's tools such as the Stone Shovel do not mine alternate versions of blocks at the correct rate.
Example: Tinker's Con. Shovel mines Vanilla Minecraft Gravel at one speed, mines Gneiss Gravel at a different, slower speed.
This is likely due to the block not being registered properly for Tinker's Constructs.

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Place a normal Gravel and an Underground Biomes Gneiss Gravel block.
3. Spawn a Tinker's Construct Shovel
4. Mine both blocks, and see the speed difference.

**Expected behavior:**
Tinker's Constructs should mine all blocks that share an ore dict entry at the same rate.

**Comment by sarperen** [comment]
The Underground Biomes Blocks have different mining times for non-TC tools too, so I think this is intended behaviour.

**Comment by Atricos** [comment]
Exactly as @sarperen said, Underground Biomes blocks have differing break speeds, no matter if you use Tinkers' or other tools.
