### ISSUE TITLE
Roots 3 crash with spell modifier editing in Imposer

### ISSUE THREAD

**Issue by DrTasslehoff** [Divine-Journey-2/main#227]
**Modpack version:**
2.2

**Java version:**
1.8 301

**Description:**
 When trying to edit modifiers on any Roots spell when the staff has any spell with additional modifiers in any slot results in a crash.

**When did the crash happen?**
trying to edit spells in the Imposer.

**Steps to reproduce:**

1.  Place a staff into the Imposer
2. Right click with a knife to open the interface
3. Open a spell and add any number of modifiers to a spell, this works fine
4. Attempt to repeat steps 1-3 and you will see a crash on step 3

**Minecraft crash report:**
https://pastebin.com/f4sSupYz

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
10GB/32GB

**Additional context:**
You can normally shift-click ingredients into spells without opening the interface, but this also fails when the staff has any spell with new modifiers inside of it.

**Comment by Atricos** [comment]
Please report this to the Roots devs: https://github.com/MysticMods/Roots/issues
This is not something I can fix my changing configs or scripts.
It's likely happening because the 3.1.1 version is very new.

**Comment by DrTasslehoff** [comment]
For anyone else coming across this issue, or related crashes using the new Roots stuff: It's a temporary thing and you eventually stop crashing. The solution that seems to work for now is to setup a staff with only spells without modifiers. Afterwards, grab one of each herb and then go into the imposer and unlock all of the modifiers for a spell. Afterwards you should stop crashing doing that.

**Comment by noobanidus** [comment]
This was reported on our tracker as https://github.com/MysticMods/Roots/issues/744 and I *believe* that I've resolved it as of 3.1.2 by adding additional safe-guards for potential null players on the client-side into Roots, MysticalLib and Mystical World.

**Comment by WaitingIdly** [comment]
Resolved in 2.4.0
