### ISSUE TITLE
Quake Hammer from Erebus is invisible 

### ISSUE THREAD

**Issue by King65868** [Divine-Journey-2/main#229]
**Modpack version:**
2.2.0

**Description:**
The Quake Hammer that drops from the Antlion boss is invisible.

**Steps to reproduce:**
1. Open the game.
2. Kill the Antlion boss.
3. Quake Hammer drops and is invisible.

**Expected behavior:**
The Quake Hammer should not be invisible.

**Screenshots:**
![2021-09-04](https://user-images.githubusercontent.com/84357753/132111073-d1a41e0f-b103-4f91-ad58-764a0ed201f7.png)

**Comment by Atricos** [comment]
This is the exact texture the Quake Hammer uses:
![image](https://user-images.githubusercontent.com/24854267/132683608-de8092ed-30f3-49c4-8a2f-40c628cf2a06.png)

And in fact it *does* render, it's just very-very-VERY small. If you hold it in your hand some scribbe does show up next to your 9th hotbar slot.

I'm not sure how to edit the above image to make it larger though.
