### ISSUE TITLE
Odd/broken soul binder recipes appearing in JEI

### ISSUE THREAD

**Issue by Synthitic** [Divine-Journey-2/main#23]
**Modpack version:**
Beta 1

**Description:**

	-Attempting to view where a filled soul vial comes from in JEI gives odd soul binder recipes
        -Example: viewing where the filled Enderman soul vial comes from shows that a Z-Logic Controller and 4 XP will give an empty soul vial and the Enderman Soul Vial, the recipe does not work. (broken recipe?)
   	-Scrolling through soul binder recipes causes the FPS to drop significantly (is this standard?)

**Steps to reproduce:**
1. Open the game
2. Get into a world
3. Attempt to view where to get a filled soul vial, can be any mob

**Expected behavior:**
There should not be weird recipes appearing for filled soul vials. I do not know if the fps drop while viewing recipes is normal.

**Comment by tyler489** [comment]
Im pretty sure this is because you are using crafttweaker to modify existing recipes, instead of enderio's xml system, as I have never seen this happen when using the xml.
