### ISSUE TITLE
Underground Biomes Certus Quartz Ore has incorrect output in enrichment chamber.

### ISSUE THREAD

**Issue by MelnCat** [Divine-Journey-2/main#230]
**Modpack version:**
2.2.0

**Description:**
Putting certus quartz ore from underground biomes into a mekanism enrichment chamber results in 4 charged certus quartz, rather than 4 certus quartz. The AE2 certus quartz ore results in 4 certus quartz as expected.

**Steps to reproduce:**
1. Get into a world
2. Place a mekanism enrichment chamber and connect it to a power source
3. Put in a certus quartz ore from underground biomes (limestone, shale, basalt, etc)
4. See that the output is 4 charged certus quartz rather than regular certus quartz.

**Expected behavior:**
The output from the ore should be 4 regular certus quartz instead of the charged certus quartz that it currently outputs.

**Screenshots:**
![image](https://user-images.githubusercontent.com/37024464/132113555-8aa3be71-a08d-40af-8474-d4a120510a24.png)
AE2 Certus Quartz Ore (correct)

![image](https://user-images.githubusercontent.com/37024464/132113566-3b99cbcb-6fb5-4962-a301-bef16607b015.png)
Underground Biomes Certus Quartz Ore (incorrect)

**Additional context:**
N/A

**Comment by Atricos** [comment]
Applied the exact provided changes in 2.3.0.
