### ISSUE TITLE
Give priority to the backpack in the Bauble slot

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#234]
**Modpack version:**
2.2.0

**Describe the request:**
If u have 2 backpacks, one in your toolbar & one in your bauble slot, pressing the hotkey will open the one in your toolbar rendering the one u have equipped unusable. 

**Reasons why this should be added:**
Making this chance, will allow you to have a personal backpack at the ready whenever u press the hotkey & one in your toolbar for random things. The way it is now, u need to have both in your toolbar 

**Describe alternatives you've considered:**
No other solutions. 

**Additional context:**
- I've played a lot of 1.16 modded MC and I've come across Sophisticated Backpacks mod. This has to be the best backpacks mod we have **by far** One thing u can do, is wear one in your bauble that will open whenever u press the hotkey and one in your toolbar that u can use for random things.

**Comment by Atricos** [comment]
Is this for the new Simply Backpacks or Iron Backpacks?

**Comment by EagleHamlet** [comment]
> Is this for the new Simply Backpacks or Iron Backpacks?

This for the new Simply Backpacks mod.

**Comment by Atricos** [comment]
There is nothing in the Simply Backpacks config that would fix this, so I highly suggest reporting this to the Simply Backpacks devs, if you want it to be fixed.

**Comment by WaitingIdly** [comment]
As there is no way for us to interact with this, this issue will now be closed.
