### ISSUE TITLE
Sense Enemy from 2.1.1 becomes Extension in 2.2.0. An unobtainable spell. 

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#236]
**Modpack version:**
2.2.0

**Description:**
I made the Sense Enemy spell in the 2.1.1 Modpack version & when I updated to 2.2.0 the spell became Extension. This is an unobtainable spell

**Steps to reproduce:**
1. Make spell in 2.1.1 version
2. Update to 2.2.0
3.  You now have an unobtainable spell that it doesn't even show in the JEI

**Expected behavior:**
Nothing

**Screenshots:**
![image](https://user-images.githubusercontent.com/90133613/132123011-c55bf90e-dace-4760-a134-46e50ec8e826.png)

![image](https://user-images.githubusercontent.com/90133613/132123029-9da07fe0-ae2c-49d0-9d6f-03a1a00040ad.png)

![image](https://user-images.githubusercontent.com/90133613/132123088-9649657f-efec-4d27-8bc2-c6e424387274.png)

**Additional context:**
The spell allows you locate animals, hostiles, plant life, growing plants, ores & even specific ores, amongst other things. If it were craftable you could bypass the long cooldown of the spell with another staff. Using 3 staffs & this spell whilst holding diamond ore in your off-hand will allow you to locate all diamond ores in your vicinity and u could reliably abuse this to find all rare ores around you.

**Comment by Atricos** [comment]
As Roots is being developed, this is bound to happen. When creating a world on newer Divine Journey 2 version, this will no longer occur.
