### ISSUE TITLE
Acid Cloud & Heal modifier gives you insane regeneration. Allowing you tank & outheal shocking amounts of damage. 

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#237]
**Modpack version:**
2.2.0

**Describe the request:**
Reduce the insane regen 

**Reasons why this should be changed:**
This with some armor & a few bonus hearts will make you unkillable and allow you to outheal any type of damage, unless it's a very very high burst. You can outheal by a large margin when all of these are combined -> Withering IV + Poison IV + Lava Damage. You can stand in lava with all of these effects **whilst wearing no armor** and still outheal the damage

**Describe alternatives you've considered:**
Make this spell apply regen III or IV instead OR reduce the healing capabilities of the cloud. 

**Additional context:**
Nothing

File too big so uploading to to YT channel. 

https://www.youtube.com/watch?v=XmKXUa7uEuI&ab_channel=HamletEagle

**Comment by Atricos** [comment]
Gated the Acid Cloud until Chapter 10 in 2.3.0.
