### ISSUE TITLE
Jigsaw Puzzle Currently Broken

### ISSUE THREAD

**Issue by Pajama-Day** [Divine-Journey-2/main#239]
**Modpack version:**
2.2.0

**Description:**
Puzzle Pieces Satchel has the incorrect enchantment - Vorpal IV instead of Holding IV, making completing the jigsaw puzzle impossible

**Steps to reproduce:**
1. Open a world
2. Make/Get the Puzzle Pieces Resonant Satchel
3. The Satchel lacks all 81 pieces needed to complete the puzzle, therefore rendering it and therefore the pack unfinishable.

**Expected behavior:**
The Puzzle Pieces Satchel is supposed to have Holding IV so that it can hold all the pieces.

**Screenshots:**
[Vorpal IV instead of Holding IV](https://i.imgur.com/0vK3FkM.png)
[Currently, the Satchel holds 67 of the 81 pieces.](https://i.imgur.com/4IzN485.png)

**Comment by ToasterKoishi** [comment]
That's actually really hilarious. Must have been broken by a recent patch that shuffled the enchantments around, because this was definitely working in beta.

**Comment by Atricos** [comment]
Enchantment IDs constantly change and shuffle around for some reason.

I checked the Puzzle Pieces Bag with the new Backpack mod already added, and it was Holding IV... I'll check it again then.

**Comment by Atricos** [comment]
The "Puzzle Pieces" bag is now a Diamond Shulker Box, so it no longer uses Enchantments. Changed the shown item in JEI, its recipe now uses a regular Diamond Shulker Box, and changed the quest to require this item.
