### ISSUE TITLE
Nickel is far too Good 

### ISSUE THREAD

**Issue by proretard21** [Divine-Journey-2/main#240]
Modpack version:
2.20

Describe the request:
(Tinker's construct) Nickel is guaranteed crit which means you are always doing double dmg with tinkers weapons, I feel it defeats the point of using anything else until later later on.
**Reasons why this should be changed:**
Makes the game far too easy because you can kill most mobs in a few hits at most.

Describe alternatives you've considered:
I'm not sure if you can change the trait passive but I can't think of anything to change it to.

**Comment by sdjjufdki** [comment]
i mean for one crits are 1.5x damage in minecraft, which is still pretty good but not so much as to break balance completely.
but yea theres very little point to using any non tinkers sword early on, and honestly not that much still until much later, though this problem isnt just because of nickel's critikill.

**Comment by ToasterKoishi** [comment]
All factors considered, I agree that Critikill is not overpowered enough in comparison to other possible modifiers / weapons in this pack to justify removing it. Even though it is available early, it is available early enough that the player likely has not obtained any gear that would make landing crits difficult (such as jump boost), so Nickel may be better replaced with a different modifier. Then, later in the game, there are many other available modifiers / weapons that are competitive with it (Cold Blooded, Bloody Mary, Hearts, Katana's combo bonus, heavily enchanted Baykok bow, etc).

**Comment by Atricos** [comment]
I don't think it's "far too good". It's decent, feel free to use it.
