### ISSUE TITLE
heart canister quest rewards

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#242]
**Modpack version:**
2.2.0

**Description:**
The heart canisters from the blaze quests (#939, and #941) in exploration 1 have a blank nbt tag, crafted ones and the reward from quest (#126) do not which makes them unstackable

![image](https://user-images.githubusercontent.com/8618678/132136125-cbc65936-c209-4a45-814d-3e02aca6ae5f.png)
![image](https://user-images.githubusercontent.com/8618678/132136127-4731a2af-ec59-4431-be28-2f69547c7727.png)

**Comment by Atricos** [comment]
Changed the 2 Heart Canisters, now they're given without any NBT in 2.3.0.
