### ISSUE TITLE
Black Tarantula quest incorrectly names "Baobab Tree" instead of "Eucalyptus Tree"

### ISSUE THREAD

**Issue by Autissima** [Divine-Journey-2/main#243]
**Location:**
In the 7th chapter quest "Black Tarantula", the description mentions a "Baobab tree"
**Exact fix:**
The tree however, is an eucalyptus tree as seen on [the Erebus wiki](https://static.wikia.nocookie.net/the-erebus/images/e/e2/Brood_Mother_dungeon.png/revision/latest/scale-to-width-down/642?cb=20210221172938).

**Comment by Atricos** [comment]
Corrected in 2.3.0.
