### ISSUE TITLE
Hopseed trees not spawning gates progression in chapter 15

### ISSUE THREAD

**Issue by Zcey1** [Divine-Journey-2/main#245]
2.2.0 & previous versions

In chapter 15 (blood magic) you re required to make arboreal essence, this requires hopseed saplings. As it seems, hopseed trees either dont spawn or are too rare to be found. I checked in creative with an xray to check over 1000 chunks, and found not a single hopseed leaf, log, or sapling.

**Steps to reproduce:**
1: Generate a world
2: Check forest and hills biomes
3: Hopseed trees don't spawn

**Expected behavior:**
1: Generate a world
2: Check forest and hills biomes
3: Hopseed trees spawn

**Screenshots:**
This is a screenshot of my x-ray GUI, it auto-adds blocks when they have been loaded by the game.
![image](https://user-images.githubusercontent.com/32963933/132268175-69905fa4-9cc2-4f9f-84a0-c0cbdc84ad79.png)
Hopseed sapling on FTB wiki
![image](https://user-images.githubusercontent.com/32963933/132268258-3a9def61-0400-4cf0-8d3a-24d28455fc9e.png)

**Comment by Atricos** [comment]
If any Beta tester sees this, can they confirm that they spawn? I'm also not sure.

**Comment by Atricos** [comment]
`config/natura.cfg` does confirm that they spawn, but I suppose they might be too rare.
![image](https://user-images.githubusercontent.com/24854267/132399772-963187e4-64f6-4be3-ab07-513c4ea3fe59.png)

**Comment by WaitingIdly** [comment]
I can confirm that they generate. However, each sapling only generates in specific biomes, and could potentially take many hours to find - and this process must be done until 5 (maybe more, do not recall) of the saplings are found.

Especially on servers, this is an issue - perhaps add a Roots Pyre crafting ritual for each of these trees?

**Comment by Zcey1** [comment]
Yeah I would recommend an alternative method to get willow, tigerwood, maple, silverbell, and hopseed. A roots ritual or some other method as they are first required in chapter 15, so it is possible to have an abyssal craft, up to tier 3 blood alter, or high-level machine be needed for them.

**Comment by ZephyrWindSpirit** [comment]
Would appreciate being able to get all the natura saplings, including redwood. Lots of us pre 1.13 have built bases in those trees.

**Comment by Atricos** [comment]
Added a custom AbyssalCraft Ritual for each Natura Sapling in 2.3.0. They all need either a Totemic Red Cedar, a Roots Wildwood or a Dreadlands Sapling are various other items. All of these are very easily accessible (the first 2 were required to get here in the first place).

**Comment by luciscout** [comment]
This did not resolve this issue - Hopseed trees and Willow trees are still rare, and Roots Wildwood Saplings are not obtainable.

**Comment by Atricos** [comment]
Added a recipe for the Roots Wildwood Sapling, and now everything should be available much more easily.
