### ISSUE TITLE
Erebus portal does not open

### ISSUE THREAD

**Issue by Borbarad13** [Divine-Journey-2/main#246]
**Modpack version:**
2.2.0

**Description:**
The Erebus portal doesn't open and I think this might be a bug (not an Erebus expert though).

**Steps to reproduce:**
1. Open the game
2. Get the staff of Gaea, stone bricks (from vanilla Minecraft), leave blocks (from vanilla minecraft) and the portal block
3. Arrange them as shown in the attached screenshot (both combinations with the portal block at the height of the stone bricks and with the portal block at the height of the leaves have the same result)
4. Try to click the staff into the portal block

**Expected behavior:**
A portal should open, but it does not.

**Screenshots:**
![leaves_are_vanilla](https://user-images.githubusercontent.com/16468773/132418454-d1b6c492-ed13-412a-9421-7cafdfe70baf.png)
![portal_block_down](https://user-images.githubusercontent.com/16468773/132418457-8fca5bcb-e3bd-4d27-aa97-c5abfad29a23.png)
![portal_block_up](https://user-images.githubusercontent.com/16468773/132418459-533bdf95-d306-4502-9670-4990cd347aff.png)
![stone_bricks_vanilla](https://user-images.githubusercontent.com/16468773/132418460-d29a519d-b5dc-48bf-ac69-6fa9d110513d.png)

**Additional context:**
I restarted as well the client/server, but the problem persists. I also tried to put the portal on the ground as well as using other blocks than stone bricks.

**Comment by King65868** [comment]
It looks like it is 1 block too wide

**Comment by Atricos** [comment]
It does open. Place the Staff of Gaea into the Gaean Keystone by right clicking the top side of the block.

Check this video if you're unsure: https://www.youtube.com/watch?v=c7j0SRtal-s

**Comment by Borbarad13** [comment]
Got it working with a 2x2 portal and the keystone 7 blocks away with sky access (not sure if the later one matters).

**Comment by Borbarad13** [comment]
Thanks for the support and sorry for the false alarm!
