### ISSUE TITLE
 Industrial Foregoing upgrades quest (#1313)

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#247]
**Modpack version:**
2.2.0

**Description:**
The questbook says a stack of each upgrade can be used but only one of each can be put into a machine
![image](https://user-images.githubusercontent.com/8618678/132567694-62ed404f-22f1-44c1-b0a7-60cdb4442ac6.png)

**Comment by Atricos** [comment]
Fixed the description in 2.3.0.
