### ISSUE TITLE
Sylvan armor not auto-repairing in latest update

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#249]
**Modpack version:**
2.2.0

**Description:**
Sylvan armor is no longer auto-repairing at all. I have the full armor set and not once has a single piece gained a durability point.

**Steps to reproduce:**
1. Obtain and equip sylvan armor
2. Damage it in any way
3. The armor will not repair

**Expected behavior:**
As far as the questbook and ftbi wiki, it has a 1/80 chance per tick to repair, which equates to 25% chance per second. It should be repaired by now

**Screenshots:**
![image](https://user-images.githubusercontent.com/21179158/132595800-616f960c-f19f-423b-8397-55dd978ca893.png)

**Comment by Atricos** [comment]
There is nothing in the configs that would change this behaviour.

If it's truly a bug, report it to the Roots devs.
