### ISSUE TITLE
Runed items do autorepair

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#251]
**Location:**
chapter 3 quest "Nordic Raiders"

**Exact fix:**
Not exactly a "typo" but an incorrect information from the quest. while they don't autorepair as fast, the runic items DO autorepair.

**Comment by Atricos** [comment]
Corrected the misinformation in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866
