### ISSUE TITLE
Lags when using the crafting table

### ISSUE THREAD

**Issue by divinepr** [Divine-Journey-2/main#253]
**Modpack version:**
2.2.0

**Description:**
Lags when using the crafting table. If this is a server, the TPS drops very much when you try to craft 64 items or less

**Steps to reproduce:**
Just try to craft 64 chests and pick them up via SHIFT. The server is lagging!

**Expected behavior:**
It will be crafted and there will be no lags

**Screenshots:**
I'm not attaching my own video, this is a known problem
[https://www.youtube.com/watch?v=MgQgAUS8tnA](https://www.youtube.com/watch?v=MgQgAUS8tnA)

**Additional context:**
I suggest adding a Fast Work bench, I tested it on the server and it works for me! But you need to have on the server and client

**Comment by Atricos** [comment]
FastWorkbench was originally in the pack, but we had other troubles with it, so we had to remove it...
Unfortunately some servers may lag, try to give your server more RAM (if possible), or (depending on the number of online players) you might need to use a CPU with a higher clock speed.
