### ISSUE TITLE
Updating the pack resets multiple configs (Inventory Tweaks, Mouse Tweaks, OreExcavation)

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#254]
**Modpack version:**
2.3.0

**Description:**
When you update the pack, all the settings concerning Inventory Tweaks are reset. 

**Steps to reproduce:**
1. Open the game, change some Inventory Tweaks settings by clicking the three dots in the top right of your inventory
2. Change the pack version
3. Open the game and look at the Inventory Tweaks settings and notice that they are reverted.

**Expected behavior:**
The settings stay the same.

**Comment by KleinGrrmpf** [comment]
It also deletes all the custom OreExcavation profiles you created.

**Comment by WaitingIdly** [comment]
This is simply a description of updating. please remember to copy your old files over.

**Comment by KleinGrrmpf** [comment]
This could be fixed though by simply not including the oreexcavation_shapes.json, the InvTweaks.cfg and the MouseTweaks.cfg file in every new update. And including them is not most likely not necessary because in those files probably nothing is going to change. Isn't that the same thing as not including the vanilla config options in every update because nothing in them changes anymore and people would lose their keybinds after every update?

**Comment by WaitingIdly** [comment]
keybinds are done through defaultoptions. also, you typically have to copy those over too.

**Comment by KleinGrrmpf** [comment]
But if you can leave those out of the updated, why can't you just leave out these config files as well?

(I'm not trying to argue over this, I am genuinly trying to understand that because in my understanding, you could just leave them out. But this doesn't seem to be the case, so I'd like to understand why)

**Comment by Nagapito** [comment]
Also, while at it, the ftbbackup config file should also be excluded from the pack.
If not there, the game will create a default one the first time...

This prevents having to configure or replace the config file every server update...
