### ISSUE TITLE
Feat Req: Add FastWorkbench (and optionally FastFurnace)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Divine-Journey-2/main#256]
First check if your request has been submitted before. If a similar request already exists, please don't submit, instead comment on that request. Note that new mods are likely NOT going to be added to the modpack. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your request has been added. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.3.0

**Describe the request:**
The mods [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench) and [FastFurnace](https://www.curseforge.com/minecraft/mc-mods/fastfurnace) should be added to DJ2.  Primarily FastWorkbench, but I figured if I was going to request one I should do both.

**Reasons why this should be added:**
FastWorkbench massively improves crafting speed when using the crafting table (which currently lags, and it's a fairly large delay).
FastFurnace just decreases the TPS load of furnaces, likely won't be huge but certainly nice to have.

**Describe alternatives you've considered:**
I'm not aware of any alternatives to having FastWorkbench.  Not having it results in the currently existing crafting table lag.

**Additional context:**
https://imgur.com/a/JakA1rv
That visible delay between the shift click craft being initiated and completed is what FB fixes, note this is only a 14-craft operation, the delay gets substantially worse when performing a 64-craft operation.

**Comment by Atricos** [comment]
Added FastWorkbench in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
