### ISSUE TITLE
Dank null "ore conversion" glitch

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#258]
**Modpack version:**
2.3.0

**Description:**
The dank/null's "oredict" ability has a very unintended side effect with the -allOres oredict tag. when an ore is set to oreDict mode true and any other block with the -allOres tag is shift-clicked in, the incoming ore will be converted into the ore-dicted option,

**Steps to reproduce:**
1. Get a dank null and place an ore with the -allOres oredict tag inside.
2. hold O and click the ore to enable oredicting
3. take any other ore with the -allOres tag and shift click on it with the dank/null gui open

**Expected behavior:**
The oreDict feature is meant for multiple types of the same ore, but for some reason, the allOres tag is accepted as valid, and will convert eroneously.

**Comment by Atricos** [comment]
Removed the `allOres` OreDict, instead I used an IIngredient array in scripts. This fixes the issue in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866
