### ISSUE TITLE
/bq_admin default load quest for singleplayer users who don't have commands enabled

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#259]
**Modpack version:**
2.3.0

**Describe the request:**
There should be a repeatable quest somewhere in the questbook (most likely in the 1st chapter) that will run the "bq_admin default load" command when completed in singleplayer.

**Reasons why this should be added:**
Having to open up the game to LAN is annoying, and not everybody knows that you can do that. Plus, not everybody will know you HAVE to run it when updating the pack, which will be more clear if it's within a quest

**Comment by Atricos** [comment]
This would work on Singleplayer, but it would perhaps lead to some issues on Multiplayer where only admins can use the command.

**Comment by WaitingIdly** [comment]
A quest that can do this will cause crashes on servers. Will not be implemented.
