### ISSUE TITLE
adding a mode for rails transportation 

### ISSUE THREAD

**Issue by Skipper1996** [Divine-Journey-2/main#260]
im playing on a server and for performance purposes, we build our bases "horizontal not vertical "

and id like to have some transportation long distance like Railcraft or something along the line in earyl/mid game

**Comment by aacidic** [comment]
I can understand the idea, but what stops you from using vanilla features like normal rails or ice? The recipes remain unchanged (boat recipe is cheap even after being changed), and for longer distances you can also combine using the nether + rails, or even using boat + ice if you get your hands on a silk touch tool too.

**Comment by KleinGrrmpf** [comment]
Staff of Travelling and Travel Anchors are always the answer for that

**Comment by Atricos** [comment]
No.
