### ISSUE TITLE
In the Mystical World huts, the chests have Mystical World copper instead of Thermal copper

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#263]
**Modpack version:**
2.3.0
**Description:**
The loot chests in the basement of the Mystical World huts have the copper ingots of Mystical World instead of the Thermal ones. Those can't be used in any crafting and since there is no Forge Lexicon, you can't convert them into the Thermal Copper Ingots.

**Steps to reproduce:**
1. Find a Mystical Worlds hut
2. Go to the basement and open the chest
3. Be lucky to find a Copper Ingot
4. Observe the mod name

**Expected behavior:**
The loot table should have the Thermal Copper Ingot or there should be an early way to convert the items.

**Comment by WaitingIdly** [comment]
"no Forge Lexicon" there are like 10 oredictionary machines, one from mekanism.

**Comment by KleinGrrmpf** [comment]
I did check the converting methods and the machine from IF is deactivated, the Forge Lexicon is deactivated and by the time you get to mekanism, you'll have a lot of copper. I don't know of any other methods to convert items... You'll have this kind of copper when you still need to go mining manually, that's why converting it early on is important.

**Comment by Atricos** [comment]
The huts now generate Thermal Copper Ingots instead in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.
