### ISSUE TITLE
Uranium from IE Excavator has no uses

### ISSUE THREAD

**Issue by cauliflower69** [Divine-Journey-2/main#265]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.1.1

**Description:**
Uranium from IE Excavator has no uses

**Steps to reproduce:**
1. Find a Uranium Vein
2. Get Uranium
3. Cant smelt it and when placed in an IE crusher it produces nothing and cant be smelted

**Expected behavior:**
Some use for it

**Comment by KleinGrrmpf** [comment]
Or just have the ore produce yellorium ingots/dust in the furnace/crusher

**Comment by Atricos** [comment]
That's interesting, Uranium's supposed to be disabled:
![image](https://user-images.githubusercontent.com/24854267/132995032-4750318b-cb95-4ab7-b291-cc23c6869ebd.png)

**Comment by UserNullified** [comment]
Can confirm, found an Uranium vein.
![javaw_KMQH95rY9n](https://user-images.githubusercontent.com/52426806/132996533-466a2fb8-a0f8-4981-933b-f80d7518c523.png)

**Comment by Atricos** [comment]
I set the chance to 0 as well in 2.3.1. I'm not sure if this fixes the issue yet, so I'll leave this open until I can confirm.

**Comment by NathanHentges** [comment]
I believe that config option is for the ore blocks themselves being generated in the world, not the ore deposits meant for the excavator.

**Comment by Hjaldar** [comment]
The issue is this line in ImmersiveEngineering.zs (446):

mods.immersiveengineering.Excavator.removeMineral("Uranium Ore");

The command "/ie mineral list" shows the registered name is just "Uranium", so changing that line to

mods.immersiveengineering.Excavator.removeMineral("Uranium");

should work.

**Comment by Atricos** [comment]
Implemented the changes that we've been talking about in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), which now actually does remove the Uranium Veins.
