### ISSUE TITLE
Typo in the tooltip of Eye of the Watcher

### ISSUE THREAD

**Issue by pyroaffe99** [Divine-Journey-2/main#266]
**Location:**
Where is the typo located? (Quests / Title Screen / Tooltips / Advancements / ...)
In the Tooltip of the Eye of the Watcher

**Exact fix:**
It says the Watcher is summoned by the Eye of the Watcher, though it is actually summoned by the Call of the Watcher.

**Comment by Atricos** [comment]
Fixed the typo in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189.
