### ISSUE TITLE
Nether Reed cannot be used to make paper - QuestBook says you can.

### ISSUE THREAD

**Issue by SPIDERBOY2012** [Divine-Journey-2/main#268]
**Modpack version:**
2.3.0

**Description:**
Nether reed cannot be used to make paper, as the quest book mentions that you can in Chapter 5 - "They can grow here too"

**Expected behavior:**
A crafting recipe for paper with nether reed should exist.

**Comment by Atricos** [comment]
Nether Reed can now be used to make Paper in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.
