### ISSUE TITLE
Certus Quartz Crystals cannot be crushed directly in the IE crusher

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#269]
**Modpack version:**
2.3.0

**Description:**
While Certus Quartz ore can be crushed into 2 certus quartz dust, Certus Quarts Crystals cannot be crushed directly in the IE crusher

**Screenshots:**
![image](https://user-images.githubusercontent.com/21179158/132927211-950404f4-6199-46e5-afa2-5e6f699387c0.png)

**Comment by Atricos** [comment]
This was actually an issue in a number of crushers, including the Actually Additions, Extra Utiltiies and Lightning Crushers, and it's been fixed now in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189
