### ISSUE TITLE
Crystal Growth Accelerator quest requirement should be reduced

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#270]
**Modpack version:**
2.3.0

**Describe the request:**
The crystal growth accelerator requirement in the quest "Purity Is Key" should be reduced from 5 to 2.

**Reasons why this should be changed:**
Mekanism's enrichment chamber serves as a direct upgrade to the crystal growth accelerators and requires 2 to craft. Any excess is not required. Since this quest blocks off a majority of the AE2 questline, the resource demand should not be as high for a non-mandatory amount of accelerators. 

**Describe alternatives you've considered:**
While crystal growth accelerators can be used separately from mekanism's enrichment chamber, and 5 is the max amount for 1 pool of water, anybody who DOES craft the enrichment chamber will have 3/5 of those accelerators made completely useless and a waste of materials.

**Comment by Atricos** [comment]
Reduced the requirement from 5 to 2 in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.
