### ISSUE TITLE
Add Osmium ore to the IE Excavator

### ISSUE THREAD

**Issue by cauliflower69** [Divine-Journey-2/main#272]
Would be nice to have this added

**Comment by Atricos** [comment]
Added Osmium Veins to the Excavator in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.

**Comment by tyler489** [comment]
This Sorta Worked, except I cant find it generating anywhere, went through a 15x15 chunk area and saw litteraly everything else. So i ran the command to add osmium ore and the excavator generates nothing.
https://gyazo.com/3ad39d2dd9fd410e3c2e7b8c211143de
https://gyazo.com/159ac0831047fd0540ddf05c1881268c
Even the core sample shows the "no ore" texture

**Comment by Hjaldar** [comment]
@tyler489 See #285
