### ISSUE TITLE
Chapter 30, Quest Description

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#275]
**Location:**
Chapter 30, Quest #795, Description, paragraph 2, row 2, first word

**Exact fix:**
Add a Scythe glyph between the 5th and the 6th char.

**Comment by Atricos** [comment]
Wow, you're incredibly ovservant. Impressive. Added the missing character in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.
