### ISSUE TITLE
the recipe for Large Nether Brick tile Bugged, it gives just normal nether brick.

### ISSUE THREAD

**Issue by Death0bomb** [Divine-Journey-2/main#276]
When trying to craft Large Nether Brick Tile with the 2 slabs of nether brick it gives normal Nether brick and not Large Nether Brick Tile.

**Comment by Atricos** [comment]
The recipe conflicted with the 2 Slabs -> Nether Brick recipe, so now I've added a different recipe for it in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.
