### ISSUE TITLE
Redstone Furnace making Abyssalcraft charcoal

### ISSUE THREAD

**Issue by King65868** [Divine-Journey-2/main#277]
**Modpack version:**
2.3.0

**Description:**
The Thermal redstone furnace produces Abyssalcraft charcoal which is much less useful than vanilla charcoal.

**Steps to reproduce:**
1. Open the game.
2. Make a redstone furnace and smelt wood. 

**Expected behavior:**
I expected vanilla charcoal to come out.

**Screenshots:**
![2021-09-11](https://user-images.githubusercontent.com/84357753/132970691-357984db-33d1-4d46-8f5d-1f14df2a569f.png)

**Comment by Atricos** [comment]
My experience is quite different, I tried like 5-6 types of wood logs, and I could never get the AbyssalCraft Charcoal. I even used the Dreadlands Wood Log, and it still gave regular Charcoal.
![image](https://user-images.githubusercontent.com/24854267/132996038-5629c3ab-eaef-470e-8d44-7563865bb6a1.png)
Which type of Wood did you use?

**Comment by King65868** [comment]
I used dark oak wood, worked fine in the alloy smelter but gave abyssalcraft charcoal in the redstone furnace.

**Comment by King65868** [comment]
Looks like it’s working perfectly fine now, weird stuff, but I’ll just close this now.
