### ISSUE TITLE
Config Files still present after Mods have been removed from Pack.

### ISSUE THREAD

**Issue by Willshaper** [Divine-Journey-2/main#278]
**Modpack version:**
2.3.0

**Description:**
phosphor.json is still preset in the config folder even though the mod itself was removed from the pack.
hardcorequesting.cfg is also still in the Config folder, even though the mod is not in the pack.

**Steps to reproduce:**
N/A

**Expected behavior:**
N/A

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by Atricos** [comment]
Thank you! Removed the file in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866.
