### ISSUE TITLE
Tank mekanism cant upgrade

### ISSUE THREAD

**Issue by DayJora** [Divine-Journey-2/main#279]
**Modpack version:**
2.3.0

**Description:**
Fluid Tank from Mekanism can`t used in crafting after its breaked ( it has font-style italic after )

**Steps to reproduce:**
1. Craft any Fluid Tank
2. Place and break
3. Try craft upgraded version 

**Expected behavior:**
You can use in craft any tanks to upgrade them

**Screenshots:**
recipe: 
![image](https://user-images.githubusercontent.com/29127679/132990475-f4039a0b-4f21-4444-a514-397c5b14b019.png)

my tank ( after break ): 
![image](https://user-images.githubusercontent.com/29127679/132990490-db99697f-6250-4b87-b656-8fa74102dcb7.png)

trying upgrade: 
![image](https://user-images.githubusercontent.com/29127679/132990503-a873cc2b-9066-4c90-b670-884e7567810f.png)

**Additional context:**

**Comment by Atricos** [comment]
Changed the Recipe Function that deals with the upgrade, and now (in 2.3.1: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3457866) it works even after the Tank's been placed down once and picked up again.
