### ISSUE TITLE
Flight before Twilight Forest information in Tips.

### ISSUE THREAD

**Issue by UserNullified** [Divine-Journey-2/main#281]
**Location:**
Line 104 of the Tips config, regarding flight before the Twilight Forest.

**Exact fix:**
The end says: "Tinkers' Slime Boots & Slimestring." instead of "Tinkers' Slime Boots & Slimesling."

**Comment by Atricos** [comment]
Corrected the tip in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189
