### ISSUE TITLE
Add in Cosmetic Armor Reworked into the Pack

### ISSUE THREAD

**Issue by TheDoctor123t** [Divine-Journey-2/main#284]
**Modpack version:**
2.3.1

**Describe the request:**
I would like to see Cosmetic Armor Reworked added within the pack

**Reasons why this should be added:**
Allows you to "wear" cosmetic armor over top of the actual armor you want to wear (EG: If you wanted to wear Crimson Cult armor for it looks but wanted to use Draconic Armor). The armor to my understanding is purely cosmetic and I don't think would have a bad interaction with Divine RPG (AKA Possibility of two set bonuses) although I haven't tested that aspect. It would make the pack better to allow players to wear the armor they want to look while still using the armor they want to use for combat.

**Describe alternatives you've considered:**
Alternative methods I have considered are Morphic armor from Thaumic Augmentation might in theory work but I don't have a massive understanding to it. Morphic armor may also not allow you to switich out the base armor so to speak (EG: If you wanted to go from Terrasteel to Draconic Evolution Armor but wanted to wear Crimson Cult armor, you might need a second set of Crimson Cult armor rather than Cosmetic Armor Reworked just having the same crimson cult armor set through the whole pack.)

**Additional context:**
This does not have a benefit for fighting against someone as you can disable the cosmetic armor in the Config.

**Comment by KleinGrrmpf** [comment]
This is just something that you can add yourself

**Comment by TheDoctor123t** [comment]
> 
> 
> This is just something that you can add yourself

Entirely fair, just more quality of life thing when installing the pack for servers rather than having to get the mod yourself.

**Comment by KleinGrrmpf** [comment]
Sure. But if everybody came with a request to add some cosmetic or client-side mod to the pack, there would be a lot of those mods in the pack which are not really needed. But I don't decide here, this is just a heads up ;)

**Comment by Atricos** [comment]
No, it's just more load time for something that's not that useful.
