### ISSUE TITLE
Immersive Engineering Excavator changes don't work

### ISSUE THREAD

**Issue by NathanHentges** [Divine-Journey-2/main#285]
**Modpack version:**
2.3.1

**Description:**
The current Excavator changes in `/scripts/ImmersiveEngineering.zs` are formatted incorrectly.
On line 443, it currently reads:
`# Excavator changes`
`mods.immersiveengineering.Excavator.removeMineral("Platinum Ore");`
`mods.immersiveengineering.Excavator.removeMineral("Iridium Ore");`
`mods.immersiveengineering.Excavator.removeMineral("Uranium Ore");`
`mods.immersiveengineering.Excavator.addMineral("Osmium Ore", 35, 0.005, ["ore:oreOsmium"], [1.0], [0, -1]);`

But the correct formatting would be:
`# Excavator changes`
`mods.immersiveengineering.Excavator.removeMineral("Platinum");`
`mods.immersiveengineering.Excavator.removeMineral("Iridium");`
`mods.immersiveengineering.Excavator.removeMineral("Uranium");`
`mods.immersiveengineering.Excavator.addMineral("Osmium", 35, 0.005, ["oreOsmium"], [1.0], [0, -1]);`

**Steps to reproduce:**
1. Open /scripts/ImmersiveEngineering.zs and make the above changes
2. Check the Engineer's Manual mineral deposits, should see the Osmium vein.

**Screenshots:**
Engineer's Manual showing the Osmium vein after making these changes
![Engineer's Manual showing the Osmium vein](https://user-images.githubusercontent.com/16007054/133005763-33bc6a2c-0db2-4699-a9c6-4ae5537f1403.png)

**Additional context:**
Additionally, you can remove platinum ore from the nickel vein by adding the line:
`mods.immersiveengineering.Excavator.getMineral("Nickel").removeOre("orePlatinum");`

_Edit:_ Changed `"Osmium Ore"` to `"Osmium"` in the mineral name

**Comment by NathanHentges** [comment]
After adding `mods.immersiveengineering.Excavator.getMineral("Nickel").removeOre("orePlatinum");` below the previous lines in the script, platinum was correctly removed from the nickel deposit.

Updated nickel deposit shown below
![Nickel deposit](https://user-images.githubusercontent.com/16007054/133006636-58b2d076-8ab7-41fd-96b9-a3b2743dfb4f.png)

**Comment by Hjaldar** [comment]
Can I also suggest changing the name of the Osmium mineral to the single word "Osmium" instead of "Osmium Ore" for consistency? The /ie mineral set command doesn't seem to work with spaces in the name, despite the use of angled brackets as suggested in /ie mineral help

**Comment by tjsd** [comment]
I tried implementing the fixes as outlined here, but they Osmium vein contains 0 minerals still.
I think that black quartz should also be added to the quartzite vein.

**Comment by Hjaldar** [comment]
@tjsd Did you change the osmium line from `ore:oreOsmium ` to just plain `oreOsmium`? That caught me out when I first made a change and I also got no minerals.

**Comment by NathanHentges** [comment]
For anyone else making this change manually, I'd recommend completely replacing the entire block under `# Excavator changes` just to ensure you don't miss any small details like that.
Hjaldar, good call on the Osmium vein name, I overlooked that.

**Comment by Atricos** [comment]
Corrected the changes in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189
