### ISSUE TITLE
Handy bag large's recipe is unchanged

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#286]
**Modpack version:**
2.3.0

**Describe the request:**
Give it a recipe, probably using the smaller one

**Reasons why this should be changed:**
Its cheaper to craft the large one (but the small one is still needed for a quest)
![image](https://user-images.githubusercontent.com/8618678/133006687-9437342f-3e5a-4c7d-8751-3df9fe5dccb8.png)
![image](https://user-images.githubusercontent.com/8618678/133006707-a4846eab-3053-4837-9650-f707370da23f.png)

**Comment by Atricos** [comment]
Changed the recipe and moved the Large Handy Bag to Chapter 19 (from 13) in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189
