### ISSUE TITLE
Chalk Slab To CobbleStone Recipe bugged doesnt out put cobblestone but shows the cobblestone in the crafting table

### ISSUE THREAD

**Issue by Death0bomb** [Divine-Journey-2/main#287]
When trying to craft cobblestone with 2 slabs of chalk shows a cobblestone, but doesnt output it. just gives back the items crafted like never happened.

![unknown_2021 09 13-19 47](https://user-images.githubusercontent.com/50574593/133139785-1c8622c8-186a-406f-94a5-9b52182c7510.gif)

**Comment by Atricos** [comment]
I just tried it in Singleplayer an it worked. Try to restart your game/server, and make sure the client and the server are on the same version.
