### ISSUE TITLE
Typo in Quests #1341 and #1378

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#291]
**Location:**
Flux-Infused JetPlate & Dark Soularium JetPlate Quests (Chapter 12, #1341 and #1378) description
"...gives a large amount of armor, and can change held items. ..."

**Exact fix:**
It should be 'charge' instead of 'change'.

**Comment by Atricos** [comment]
Corrected the typos in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189.
