### ISSUE TITLE
Placing Comparator next to Pyre crashes the game

### ISSUE THREAD

**Issue by Alexthehuman3** [Divine-Journey-2/main#292]
**Modpack version:**
2.3.1

**Java version:**
Version 8 update 301 (1.8.0_301-b09 (ex. "11.0.8")

**Description:**
Place a comparator next to a pyre (input side facing pyre), with pyres containing items in it and it'll crash the game.

**When did the crash happen?**
The moment you place the comparator's input facing the pyre.

**Steps to reproduce:**
1. Place down the Pyre
2. Put Chest Beneath Pyre
3. Put Dispenser Behind Pyre
4. Put stuff in Pyre (that has a recipe e.g. charred stone)
5. Put some stuff in chest that is the same as recipe to bulk create.
5. Place Comparator's input toward the Pyre.
6. Crash

**Minecraft crash report:**
https://pastebin.com/BMaXGigg 
https://pastebin.com/CgdeHjgR (Creative World, without Fey Crafter and Attuned Roots Stone)

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
6GB - has 16GB (even if recommended is 8gb)

**Additional context:**
Placed Next to Fey Crafter and that Root stone that needed a ritual to activate. Has an Empty Dispenser at the back of the Pyre, followed by a chest that has recipe material beneath the pyre.

**Comment by Alexthehuman3** [comment]
updated to Java JRE 1.8.0_301 after switching to GDLauncher
New Crash Log: https://pastebin.com/fgMrdvEu

**Comment by Atricos** [comment]
Updated Roots to 1.12.2-3.1.2 in Divine Journey 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), which fixes the issue. (Roots changelog: https://www.curseforge.com/minecraft/mc-mods/roots/files/3461007)
