### ISSUE TITLE
Creative Vending Upgrade unobtainable due to crafting loop

### ISSUE THREAD

**Issue by Command-Crafter** [Divine-Journey-2/main#293]
**Modpack version:**
2.3.1

**Description:**
The recipe for a creative vending upgrade requires a creative buffer
The recipe for a creative buffer requires a creative bin
The recipe for a creative bin requires a creative vending upgrade

None of these items have alternate recipes or other ways to obtain them as far as i can see, which makes them unobtainable.

**Expected behavior:**
A recipe for either of these items that doesn't depend on each other

**Screenshots:**
![image](https://user-images.githubusercontent.com/34944204/133303235-0bd95332-66b9-4904-b460-64aac0bbb6c8.png)
![image](https://user-images.githubusercontent.com/34944204/133303283-c7253e6d-7df8-4808-b0a4-cfaf49e4558f.png)
![image](https://user-images.githubusercontent.com/34944204/133303354-fedea689-3cda-42f7-8afa-82f0b2eb4c1e.png)

**Comment by Atricos** [comment]
Ah, that's because I moved the Creative Buffer futher. Thanks for noticing (presumably) before anyone got here in Survival.

**Comment by Atricos** [comment]
Fixed in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189) by changing the Creative Buffers into Creative Capacitor Banks in the Vending Upgrade's recipe.
