### ISSUE TITLE
"TEPid Brine!" quest in chapter 13 cube vs cuboid (and a stylistic comment)

### ISSUE THREAD

**Issue by Autissima** [Divine-Journey-2/main#294]
As written in the title the body described in the quest is a cuboid, and not a cube.
Furthermore, I'd inject an "out", so the text doesn't read as "build a cube of the blocks" but instead "build a cube out of the blocks".

**Location:**
Quest description of "TEPid Brine!" in chapter 13

**Exact fix:**
[...] build a 4x4x3 cuboid (out) of the Thermal Evaporation Blocks [...]

**Comment by Atricos** [comment]
Corrected the description in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189.
