### ISSUE TITLE
No gold ore recipe in the SAG mill.

### ISSUE THREAD

**Issue by harmonicvoltage** [Divine-Journey-2/main#297]
**Modpack version:**
2.3.1

**Description:**
Despite there being a recipe for every other ore in the SAG mill (to my knowledge), there is no recipe for gold ore. 

**Steps to reproduce:**
1. Craft, place, and power a SAG mill.
2. Obtain gold ore.
3. Attempt to place gold ore in the SAG mill.
4. Gold ore is unable to be placed in the SAG mill.

**Expected behavior:**
Gold ore to be placed into the SAG mill properly and double like any other ore.

**Comment by Atricos** [comment]
Added recipes for all Gold variants in the SAG Mill in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189)
