### ISSUE TITLE
Command Block in Venus Dungeon

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#298]
**Modpack version:**
2.3.1

**Description:**
One of the Venus Dungeon prebuilds has a command block

**Steps to reproduce:**
1. Get to Venus
2. Find a Dungeon with a forge right at the entrance
3. (In Spectator) from the entrance crossing, fly one room higher and then straight, through the fountain and two walls 
    (In Survival) Go Left (it goes down at the end), Straight, Left, Straight, Up, Right (Where the spawner is), Left, and Right

**Expected behavior:**
The command block should spawn a spawner

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/57828910/133447735-73f4bc96-8b24-4405-9764-fba655df5cb8.png)

**Additional context:**
the command block is set to activate on redstone signal

**Comment by Atricos** [comment]
The Command Block changes to a Spawner now in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189)
