### ISSUE TITLE
Custom alloy smelter recipes do not require full input to complete recipes

### ISSUE THREAD

**Issue by DrTasslehoff** [Divine-Journey-2/main#299]
**Modpack version:**
2.3.1

**Description:**
Recipes such as "Blank dark steel upgrade" or "snowflake" that require multiple of one item in a stack can be competed without the full amount. So 1 dark iron bar + 1 energized dark dust + 1 mithril ingot will craft blank dark steel upgrades.

**Steps to reproduce:**
1. input one of each item required for a recipe into an alloy smelter

**Expected behavior:**
recipe should not start until all items are provided

**Comment by Atricos** [comment]
Seems people have run into this issue before: https://github.com/Shadows-of-Fire/EnderTweaker/issues/16

**Comment by Atricos** [comment]
Fixed in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), along with like 30 other Alloy Smelter recipes that could be cheesed.
