### ISSUE TITLE
Rebalance mekanism energy cell or energy cell recipe

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#301]
**Modpack version:**
2.3.1

**Describe the request:**
I feel like the recipe for mekanism's energy cell is unreasonable compared to it's predecessor and it's own relative storage values. This request is either to change the recipe to use the MV capacitor instead of the HV capacitor, or increase the capacity of the energy cell to be more in-line with it's HV capacitor ingredient.

**Reasons why this should be changed:**
The HV capacitor stores 4M RF maximum. The mekanism energy cube stores 800k RF maximum. This is a 1/5 downgrade in storage capacity.
HV capacitors are overall much cheaper then this "upgrade" recipe is in and of itself.

**Describe alternatives you've considered:**
While an additional solution could be to nerf the HV cell to make the energy cell an upgrade, I feel like that would negatively impact existing systems.

**Comment by Atricos** [comment]
Increased the capacity of all Energy Cubes from 800k / 3.2M / 12.8M / 51.2M to 4M / 12M / 36M / 108M in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), making them more of an upgrade.
