### ISSUE TITLE
Typo in Chapter 18 Quest Magic May Fulfil the Prophecy #7

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#302]
**Location:**

Quest Magic may fulfil the prophecy # 7, Chapter 18.

The quest description and title are off.

**Exact fix:**
The title should say "fulfill" instead of "fulfil". Also, the quest description first line translates to "Seek out the week and burn them!" This should read "Seek out the weak and burn them!"

**Comment by Atricos** [comment]
Corrected the typo in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189
