### ISSUE TITLE
Ring of Growth has an uncraftable spell dust from Roots.

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#306]
**Modpack version:**
2.3.1

**Description:**
The Ring of Growth From Actually Additions mod uses a spell dust that can not be crafted, the spell dust is merely an example or an icon and it's not tied to any recipe. I've asked around and it's supposed to be the Harvest / Growth Infusion spell dust

**Steps to reproduce:**
1. Look up ring of Growth
2. Try to craft it with EVERY craftable spell dust
3. Nothing works. Even tried the basic recipe in the book.

**Expected behavior:**
The ring of Growth should have the growth infusion / harvest spell dust. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/90133613/133649131-920fd9ee-82e9-4c3e-95cc-2aabf20e4593.png)

**Additional context:**
Ring of Growth is not currently used in any recipe but it's a nice ring to have overhaul.

**Comment by Atricos** [comment]
Changed the Spell Dust to another Empowered Emeradis Block in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189. (This bug occurred because of the new Roots update that made Spell Dusts uncraftable, instead Spells are aquired differently now.)
