### ISSUE TITLE
Make the Simply Backpacks build into each other

### ISSUE THREAD

**Issue by scatter-dev** [Divine-Journey-2/main#307]
**Modpack version:**
2.3.0

**Describe the request:**
The backpacks from Simply Backpacks don't build on each other, they're all totally separate recipes. I think it makes sense to change this so you first have to craft a Common Backpack, to use as an ingredient in the Uncommon Backpack, etc.

**Reasons why this should be added:**
There is an early quest to tell the player about the utility of backpacks. Currently it has you make a Rare Backpack, which becomes useless as soon as you can make an Epic Backpack (which isn't even that hard to make, so it would mostly end up in crafting a Rare Backpack just for the quest and never using it). The quest text also says "work your way up to a Rare Backpack", clearly a holdover from Iron Backpacks but it's inaccurate now.

**Describe alternatives you've considered:**
The quest could require you to make an Epic Backpack instead, solving the issue of making a Rare Backpack only to discard it immediately. (The "work your way up to" text should be changed in this case.) To me this is fine, since the Epic Backpack isn't that hard to make, so it's fine to ask for it so early. Really as a balance thing all of the backpacks could be made more difficult, working up to the Epic Backpack during a longer period, but since it's mainly QoL (you could just make tons of Common Backpacks, after all) I don't like that solution either.

**Comment by WaitingIdly** [comment]
Due to how Simply Backpacks is coded, the nbt data you get is hardcoded - meaning doing this with a backpack containing items would wipe your items. obviously, we dont want that as a possibility, so this will not be implemented.
quest was switched to epic in dev a few days ago

**Comment by scatter-dev** [comment]
As I said in the post, changing the quest to an Epic Backpack solves the issue just as well, especially considering the reasons not to have them build into each other. I'll close this.
