### ISSUE TITLE
[Bug] SAG Mill can't process all Oil Sands

### ISSUE THREAD

**Issue by TheonlyTazz** [Divine-Journey-2/main#309]
**Modpack version:**
2.2 (But others have reported it also not a recipe on 2.3.1)
![image](https://user-images.githubusercontent.com/3908847/133776688-3f887c10-1817-4d85-9847-cad1e66d90e5.png)

**Description:**
SAG Mill cannot process every type of Oil Sand which it should be

**Steps to reproduce:**
Get various types of (Underground Biomes) Oil Sand
Try putting them into SAG Mill
???
**FAIL**

**Expected behavior:**
Get various types of (Underground Biomes) Oil Sand
Try putting them into SAG Mill
???
**SUCCESS**

**Screenshots:**
![image](https://user-images.githubusercontent.com/3908847/133776953-1a15a62d-032a-49f9-9454-dab15c3ab2c1.png)

![image](https://user-images.githubusercontent.com/3908847/133776974-e8077777-8355-44f1-b0e2-9b1c2852fa9d.png)

**Additional context:**
Pack is fun ya'll

**Comment by Atricos** [comment]
The SAG Mill can now process all types of Oil Sands in 2.4.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189.
