### ISSUE TITLE
Player Crafted Clocks and Compasses can’t be put into induction smelter.

### ISSUE THREAD

**Issue by King65868** [Divine-Journey-2/main#313]
**Modpack version:**
2.3.1

**Description:**
Quark adds NBT to player crafted compasses and clocks which makes them not able to be put into an induction smelter.

**Steps to reproduce:**
1. Craft a clock/compass.
2.  Try to insert into an induction smelter.

**Expected behavior:**
I would have expected the compass/clocks to have the ability to insert into induction smelter.

**Additional context:**
I found an issue here that references this bug in action. https://github.com/NillerMedDild/Enigmatica2Expert/issues/1664

And the fix for it is posted below this line that should be added to fix this issue.
https://github.com/NillerMedDild/Enigmatica2Expert/commit/d5c59cee27b06c5017019e1b89b851392a7ae3e6

**Comment by Atricos** [comment]
Fixed in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189). The Induction Smelter now asks for the Compass and the Clock with the NBT they're crafted with.
