### ISSUE TITLE
Pulverized obsidian in a magma crucible gives molten brass

### ISSUE THREAD

**Issue by elias098** [Divine-Journey-2/main#314]
**Modpack version:**
2.3.1

**Description:**
Pulverized obsidian in a magma crucible gives molten brass.

**Steps to reproduce:**
Put pulverized obsidian into a magma crucible.

**Expected behavior:**
For the pulverized obsidian to give molten obsidian

**Comment by Atricos** [comment]
Definitely very strange, but fixed in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189).
