### ISSUE TITLE
Mekanism energy cubes downgrading when placed?

### ISSUE THREAD

**Issue by candycanecroc** [Divine-Journey-2/main#317]
(public server) When I placed a mekanism elite energy cube it downgraded to basic. So I tried mining it to see if it was a visual but it was a basic energy cube still, can anyone help me with that? I dont know what bug it is that is causing this but I need higher tier energy cubes for further progression.

**Comment by WaitingIdly** [comment]
Please follow the instructions when creating a bug report. If you do not, and we cannot easily reproduce it (which we cannot, in this case), we can never even try to fix the bug.
