### ISSUE TITLE
Wildwood dungeon weird bug.

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#319]
**Modpack version:**
2.3.1 but there weren't any changes for the dungeon

**Description:**
I was building a wildwood dungeon puzzle thing. When i thought i've done that, i've pressed a button. Nothing happened. Then i re-checked everything 3-4 times. No mistakes. Then i entered gamemode spectator and found that the figure which is compared to the building(under the building place) is partly made of limestone, not polished andesite which was given. There was no such issue in other dungeons i've completed in this dimension but still it's a weird bug and it can happen. When i removed limestone , replaced it with andesite and pressed a button everything worked as intended

**Steps to reproduce:**
^

**Expected behavior:**
These blocks shouldn't be limestone

**Screenshots:**
Figure under the building place is on the screenshot.
![bug](https://user-images.githubusercontent.com/87584837/133909487-8dac2421-80a6-4fbf-92d1-2401cf0da466.jpg)

**Comment by WaitingIdly** [comment]
Given that the structure changed to not using the /clone command, which is what is causing this, in 2.4.0, please generate a *new* dungeon in 2.4.0 and confirm that this occurs there.
Once you have done so, please comment on this issue confirming. If there is no comment within a week, this issue will be closed, presumed resolved by the change.

**Comment by Bosfik** [comment]
Tested 10 dungeons, everything works as intended. Issue closed
