### ISSUE TITLE
Invar ingots cannot be crushed in a Mekanism Crusher

### ISSUE THREAD

**Issue by IntoxicatedPlatypus** [Divine-Journey-2/main#320]
Modpack version:
2.4.0

Description:
Using a Mekanism Crusher (or a crushing factory) is not possible with Invar Ingots.

Steps to reproduce:
1. Open a Mekanism Crusher (either basic or any factory tier).
2. Put Invar Ingots into the crusher.
3. Invar Ingots aren't processing, and cannot be crushed.

Expected behavior:
Invar Ingots should be crushed.

**Comment by WaitingIdly** [comment]
No Thermal Ingot can be processed into its pulverized form using Mekanism machines

**Comment by IntoxicatedPlatypus** [comment]
Bronze can, I don't know about others. Invar was the first one to stand out

**Comment by Atricos** [comment]
From 2.5.0, Electrum, Invar, Constantan, Signalum, Lumium and Enderium Ingots can now all be crushed in the Mekanism Crusher:
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
