### ISSUE TITLE
Warded Jar & Blank label, increase craft result from 1 to 2 or 4

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#321]
**Modpack version:**
2.4.0

**Describe the request:**
Would be nice if Warded Jars & Blank Labels from Thaumcraft would result in 2 items instead of one every time u craft them. 

**Reasons why this should be changed:**
Making a single Warded Jar & Blank Label is a rabbit hole and a half. Making 30-40 for all of your essentia is a nightmare. 

**Additional context:**
Or at least make the Warded Jars craft 2 or 4 instead of one. It's such a nightmare crafting just one of them. Labels are not that hard to craft, but it would still be quite nice to have more than one every time u craft them.

**Comment by Atricos** [comment]
You should fully automate most Botania Runes and Blood Magic Catalysts before diving into Thaumcraft. Also set up an automatic Greatwood Tree farm. It shouldn't be too difficult afterwards.
