### ISSUE TITLE
Skythern Dungeon Boss Door Skip

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#323]
**Modpack version:**
2.4.0

**Description:**
You can break the lamps above the boss door which allows an ender pearl to be thrown through the gap

**Steps to reproduce:**
1. Get to Skythern
2. Find a dungeon
3. progress to the boss door
4. break the lamps above the door
5. use an ender pearl to teleport through the gap

**Expected behavior:**
Not being able to skip the boss door that easily

**Comment by JohanniklasLp** [comment]
![grafik](https://user-images.githubusercontent.com/57828910/133946835-bba41ddc-c325-481b-a99a-977cb6774fac.png)
![grafik](https://user-images.githubusercontent.com/57828910/133946864-3b36454a-e8b0-4c8f-be04-b34655f0a397.png)

**Comment by Atricos** [comment]
Replaced the 2 Lanterns with unbreakable blocks in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385 Thank you for the report.
