### ISSUE TITLE
Skythern Dungeon can partly be skipped

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#324]
**Modpack version:**
2.4.0

**Description:**
You can find the knowledge of the sky in skythern dungeon chests, making it unnecessary to progress through the whole dungeon.

**Steps to reproduce:**
1. Get to skythern
2. Find a dungeon
3. Loot chests until you have at least 4 knowledge of the sky

**Expected behavior:**
Only the boss should drop knowledge of the sky

**Comment by JohanniklasLp** [comment]
Random Dungeon Chest Loot:
![grafik](https://user-images.githubusercontent.com/57828910/133946791-48e6f884-2f52-42a5-ac6f-2a16f20c1fac.png)

**Comment by JohanniklasLp** [comment]
To add to this, the skythern dungeon has skythern blocks.

After progressing through the dungeon, you will reach a tar room with a skythern door 
![grafik](https://user-images.githubusercontent.com/57828910/134025476-6abc963d-6199-4024-9919-f718f2069b5e.png)
that leads into a wildwood room
![grafik](https://user-images.githubusercontent.com/57828910/134024448-b1bbf199-918b-4f10-b9b4-1c1c7c4de914.png)
After this room, there are some lamps on the ceiling.

breaking the lamps and some glass reveals a room with liquid coralium where you came from and 6 skythern blocks on the other side
![grafik](https://user-images.githubusercontent.com/57828910/134024643-1794cae8-f4e4-45ee-95a9-e3bda971540b.png)

There are 3 occurences of the skythern blocks in total
The second one is from the skythern door entrance, take a left, then a right, a left, another left. break the dispenser. Go down and break some spikes. There are 2 blocks in this room.

The third one is located a bit before the first one, after the room with the tool forge.
![grafik](https://user-images.githubusercontent.com/57828910/134026196-bf45a79a-0267-44df-b519-4b59f19095a5.png)
Instead of going straight in the right room, you can go left and break the diorite, behind it are skythern blocks as well as a chest.

**Comment by Atricos** [comment]
Removed Knowledge of the Sky from Chests, and changed all the Skythern blocks you could find in the dungeon into Apalachia blocks in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385 Thank you for noticing these!
