### ISSUE TITLE
Crafting Impulse item duct without thermal expansion or glowstone

### ISSUE THREAD

**Issue by lonewolf4death** [Divine-Journey-2/main#326]
You can craft impulse item duct in twilight forest uncrafting table, 6 regular itemduct + 1 lead plate gives you 1 opaque impulse if u select the correct recipe.

**Comment by WaitingIdly** [comment]
Please follow the bug issue creation format, or edit your message to follow that format.

**Comment by Atricos** [comment]
Fixed the Impulse Itemduct recipes in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
