### ISSUE TITLE
Roots achievment trophy not working

### ISSUE THREAD

**Issue by TylerStamand** [Divine-Journey-2/main#327]
**Modpack version:**
2.4.0

**Description:**
Roots achievement is not showing up in the advancements tab, nor is the trophy for the advancement being given. The trophy for the roots advancement should be a pyre but it is just an empty trophy if you look in JEI or cheat it in.

**Steps to reproduce:**
For getting the trophy
1. Open the game / Start the modpack / Get into a world 
2. Make a pyre
3. Achievement is given but no trophy awarded

**Expected behavior:**
There should be an achievement for roots in the advancements tab. When crafting a pyre for the first time you should be awarded a trophy with a pyre. 

**Additional context:**
The advancement itself can be fixed in config/triumph/script/triumph/03_root_3.txt and changing the setIcon in the from <roots:bonfire> to <roots:pyre>

The trophy can be fixed by going into config/triumph/functions/triumph/03_root_3.txt and change the TrophyItem Id from roots:bonfire to roots:pyre

**Comment by Atricos** [comment]
Fixed in 2.5.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385), and tested it, the Roots achievement does correctly show up now. I had to change `roots:bonfire` to `roots:pyre` in 3 distinct places.
