### ISSUE TITLE
Adding mod

### ISSUE THREAD

**Issue by Deux28** [Divine-Journey-2/main#328]
Hello came here to propose a couple mods that would be cool to have in the pack has far me an a couple friends tough of them and soo i came here to give the idea of the mods.

Mod - Rustic.  for more building and decor style it has.

Mod - Architecturecraft for more possibilyties of building.

Mod - Random Things  for all the stuff we can combine and create for a funny gameplay

Mod - MrCrayFish for house decor 

Mod - Cosmetic Armor Reworked to be able to turn on and off the armor or change it to look like a different one without the need of removing the stronger armor set.

Mod -Apotheosis- this one just one that would look nice not much requested

Well we are over 28 players ik is not much but we wanted to express what we thinked, thx for the attention.

**Comment by aacidic** [comment]
Apotheosis is incredibly broken as a mod, and aids in breaking other features and ruining things that would be a challenge (level 150 enchants, overpowered bosses with overpowered drops, disenchanting etc).

Cosmetic Armour was already suggested and declined before (see #284).

Random Things could be an idea but just as Apotheosis, it can be just as powerful with all of its utilities able to bypass other gated features already in place - ESPECIALLY time in a bottle, that is one of the most powerful tools in all of modded minecraft.

CFM (Crayfish's Furniture Mod), we already have Bibliocraft, but I can see where the textures that Biblio isn't a popular option, so this mod could go either way, I think there is a computer too (off the top of my head) which has powerful trades which would need to be changed/removed.

Architecturecraft can go either way as well, but it could have some unforseen consequences like lag or crashes from model complexity.

Rustic seems like a decent idea though, it could even be integrated into the main questline with the potion brewer it has (I forget the actual name).

**Comment by Atricos** [comment]
No. These would just increase load time without adding actually necessary content. Feel free to add any of them in Singleplayer though.
