### ISSUE TITLE
Garden Cloches are too slow & not worth crafting considering how difficult they are to make & the gatekeeping

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#329]
**Modpack version:**
2.4.0

**Describe the request:**
A garden cloche, even with Rich Phyto-Gro which has a 1.75x growth modifier which is not easy to get is SLOWER than an Ender IO farming station, farming 1/4 of a crop in a corner.
![image](https://user-images.githubusercontent.com/90133613/133984467-ba933771-a395-4281-a352-5a6f34595fee.png)

![image](https://user-images.githubusercontent.com/90133613/133986372-289d6e74-7fa0-4ff5-839a-b9f852dc6bb7.png)

With a Basic Capacitor & one corner being dedicated to ONLY to this type of seed, I'm producing MORE than a garden cloche. The setup that I use for Ender IO farming station is terran soil & greenhouse glass which **only** works during the day. The only thing nice about the cloches is that they work during the night & they are somewhat compact, but they still require energy, water, a place for output & a growth modifier. Not to mention, all of these can only be input / output through specific holes. 
 
**Reasons why this should be changed:**
They are not worth the craft at all, unless u need a resource that's not used very often, then again, you could use any other way to plant & harvest them than use garden cloches. Not to mention, the soil from Roots doesn't work. You MUST use dirt so that's another huge disadvantage. 

**Describe alternatives you've considered:**
1. Increase the speed considerably when growing a plant inside the garden cloche
2. OR - make it so it can use elemental soil from Roots
3. AND - increase the growth modifier from bonemeal and other variants. 
4. OR - Make the garden cloche be available more early, earlier than Ender IO farming stations.

Buffing these guys is a double-edged sword. They can produce quite a bit of lag if multiple are running in the same chunk, but at the current recipe, I'd expect them to work better... And It's not like Ender IO farms don't produce lag ...

**Comment by Atricos** [comment]
Garden Cloches now require a Prudentium Ingot instead of an Intermedium Ingot in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385 This definitely nudges it to the right direction. Do you think this is enough or should I cheapen the recipe further?

**Comment by EagleHamlet** [comment]
> Garden Cloches now require a Prudentium Ingot instead of an Intermedium Ingot in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385 This definitely nudges it to the right direction. Do you think this is enough or should I cheapen the recipe further?

That seems about the right recipe. 

Just wondering:
Nothing can be done to increase the growth? Or make the growth modifier more effective (bonemeal for example) ? Or make the elemental soil work in the garden cloches?

**Comment by Atricos** [comment]
You can use Bone Meal, yeah. I'll look into being able to use Elemental Soil.

**Comment by EagleHamlet** [comment]
> You can use Bone Meal, yeah. I'll look into being able to use Elemental Soil.

Thank you for looking into elemental soil.

I think that would be it for the garden cloches. I would test if 10/10/10 seeds work inside garden clothes & it doesn't just make them 1/1/1 again if you put them inside and get them out. Not sure what kind of drops 10/10/10 seeds would give on terran soil. Probably worth looking into.

**Comment by King65868** [comment]
Upgraded seeds don’t work in cloches, so that’s a big downside

**Comment by EagleHamlet** [comment]
> Upgraded seeds don’t work in cloches, so that’s a big downside

Damn, that's a huge downside. Do they work on elemental soil, for example terran?

**Comment by King65868** [comment]
I wouldn’t see why not, but haven’t tested

**Comment by Atricos** [comment]
There are no config options to add soils to the Garden Cloche, and there are no CraftTweaker methods either.

So this is as much as I can do. If the Garden Cloche recipe still seems unbalanced, feel free to reopen the issue.
