### ISSUE TITLE
Add recipes to craft Sheetmetal Slabs back into their respective blocks

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#332]
**Modpack version:**
2.4.0

**Describe the request:**
Add recipes to craft Sheetmetal Slabs back into their respective blocks

**Reasons why this should be added:**
It makes sense.

**Describe alternatives you've considered:**
Make recipes to be at least able to smelt them in a smeltery for one ingot (since you can also melt the sheet metal for two ingots)

**Comment by Atricos** [comment]
Added Sheetmetal Slabs to Sheetmetal recipes in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
