### ISSUE TITLE
Alchemy table/soul forge automation guide

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#333]
**Modpack version:**
2.4.0

**Describe the request:**
I wanted to suggest an addition to the quest "Funky Potions" or "Soul Smith"(ch15)
This addition consists of a guide on how to automate the production in an alchemy table and in a soul forge. The player can just create multiple forges/tables but that's very expensive and annoying on this stage. So the guide is in this link:
https://docs.google.com/document/d/1RMVtUtX4Km2f1PIIOWzIwvjxP9XEPzfpGaCuw2MS63c/edit
You can rephrase it like you want ofc.

**Reasons why this should be added:**
This chapter is really painful to do manually and there is no explanation in quest book on how to automate soul forge/alchemy table without creating multiple ones.
There is also a way to automate it using integrated dynamics but at least for me this way is easier.

**Comment by Atricos** [comment]
Rephrased your guide a bit and added it the Hellfire Forge quest. Also referenced it in the Alchemy Table quest.
This is all in update 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
