### ISSUE TITLE
Switch from Waila to The One Probe

### ISSUE THREAD

**Issue by tjsd** [Divine-Journey-2/main#334]
I really want to see liquids, and you cant do that with WAILA. I think switching to The One Probe with TOP_Addons would provide the same features but more QOL to the experience.

**Comment by KleinGrrmpf** [comment]
First of all, this is improper format of issues. Secondly, what liquids exactly can't you see? You can toggle the WAILA between fluid and block targeting and you can enable tank content and energy level display in the WAILA config as well? What more is there to see?

**Comment by tjsd** [comment]
You cant see whats in portable tanks or other liquid containers, like you can with TOP.

**Comment by KleinGrrmpf** [comment]
Of course you can. Go into the WAILA mod options, into the Capability module tab and enable Tank and Energy data.

**Comment by tjsd** [comment]
TIL! That should be a tip on the loadingscreen imo! thanks!
