### ISSUE TITLE
Enable Plant Interactor

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#335]
**Modpack version:**
2.4.0

**Describe the request:**

Re-enable the Plant Interactor

**Reasons why this should be changed:**

Right now the justification for this being disabled is it is outclassed by farming stations. This, IMHO, doesn't make much sense when you consider that the Plant Gatherer and Plant Sower are enabled. And for upscaling large farms, as you need to do with Mystical Agriculture, the Plant Interactor is much more versatile especially when combined with blocks that increase growth rate, because of the way the Farming Station handles checks for harvests. 

**Describe alternatives you've considered:**

Other solutions would be large quantities of Farming Stations, which would be less optimal.

**Additional context:**

![image](https://user-images.githubusercontent.com/77116048/134065976-82e94827-fefd-4a04-a195-07ba599f367b.png)

**Comment by Atricos** [comment]
Enabled the Plant Interactor and added a custom recipe for it in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
