### ISSUE TITLE
Enchanted Book - Withering impossible to craft

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#336]
**Modpack version:**
2.4.0

**Description:**
You cannot craft the withering enchanted book

**Steps to reproduce:**
1. Create 8 CoFH Core Arrows of Decay with Wither (0:05)
2. Try to craft the withering book
3. You cannot because the recipe requires Ender IOs Arrows of Decay which you cannot craft instead of CoFH Core ones (you cannot even put the arrows into the enchanter)

**Expected behavior:**
Being able to craft the book with CoFH Arrows of Decay or being able to craft Ender IO Arrows / Potions of Decay or dict CoFH Core Arrows / Potions of Decay to Ender IO ones.

**Additional Context:**
JEI Recipe to create Ender IO lingering potions of decay doesn't have any liquid:
![grafik](https://user-images.githubusercontent.com/57828910/134075654-7c1c615c-a758-4055-b2bd-5ddac5c5a586.png)
Trying to just put a bottle in a fluid transposer without a liquid does nothing.

The Ender IO arrow recipe as well as the other decay potion types of Ender IO show only Thermal Foundation potion liquids, not the ender IO potion liquid. Thermal Foundation potion liquids will only create the CoFH Core variants.

**Comment by JohanniklasLp** [comment]
I was lucky enough to get an EnderIO Potion from a Thaumcraft Rare Treasure, so it is actually possible to get the book

**Comment by Atricos** [comment]
Arrows of Decay can now also use the CoFH Lingering Potions of Decay, not just the EnderIO ones, making them craftable, and also making the Withering Enchanted Books craftable in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
