### ISSUE TITLE
Dark Tank combining issue

### ISSUE THREAD

**Issue by King65868** [Divine-Journey-2/main#338]
**Modpack version:**
2.4.0

**Description:**
Dark tanks can not be combined when one of the tanks has blood in the tank when put in a particular order and gives an error message.

**Steps to reproduce:**
1. Craft up two dark tanks.
2.  Put blood in one of the tanks.
3.  Put the tank with the blood on the right and tank without blood on the left and craft them together.
4.  See that it gives an error message and output does not show up.
**Expected behavior:**
I expected the tanks to combine.
**Screenshots:**
![2021-09-21](https://user-images.githubusercontent.com/84357753/134229839-382fc5cd-93c3-48ae-a734-3875fb6cdeb6.png)

**Comment by Atricos** [comment]
Dark Tanks can now correctly be combined even if the first one doesn't have fluid, but the second one does in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
