### ISSUE TITLE
Wildwood dungeon puzzle hinting

### ISSUE THREAD

**Issue by Autissima** [Divine-Journey-2/main#340]
**Modpack version:**
2.4.0

**Describe the request:**
The Wildwood dungeon features a puzzle where the player needs to copy a structure from an adjacent room, which gets checked by the player by pressing a button.
However, the button is mirrored, the button should be in the same place relative to the entrance, as in the other room.

**Reasons why this should be changed:**
As the two rooms are otherwise identical, this leads to the assumption that the player needs to mirror the structure, as opposed to copying it.

**Comment by RammyT** [comment]
It is stated in the quest's description that you should not mirror it.
If people don't read the quest description, there really isn't much else we can do.

**Comment by Atricos** [comment]
The button doesn't get checked in the structure, and yeah, the quest book explains it.
