### ISSUE TITLE
Make Cryo-Stabilized Fluxducts cheaper

### ISSUE THREAD

**Issue by FakeDomi** [Divine-Journey-2/main#342]
**Modpack version:**
2.3.0

**Describe the request:**
Cryo-Stabilized Fluxducts should cost less to make and be available earlier.

**Reasons why this should be changed:**
Cryo-Stabilized Fluxducts are gated behind Thaumcraft. The next best tier of Fluxducts only allows 25krf/t throughput per connection, which is very underpowered when comparing to Mekanism cables where the throughput grows as you add more cables to the network. They are very powerful and relatively cheap. As mentioned in the tips however, those cables should be avoided for performance reasons. Players should not have to choose between FPS or throughput.

**Describe alternatives you've considered:**
An alternative would be heavily buffing the previous tiers of Fluxducts to make them a viable alternative to Universal Cables in mid-game bases. For reference, we are currently drawing 50-100krf/t and just finished chapter 17.

**Comment by WaitingIdly** [comment]
Cryo-Stabilized Fluxducts are actually more laggy on large networks than Mekanism's can be. Use EnderIO Conduits.

**Comment by KleinGrrmpf** [comment]
Wait, they are? I always thought that Mekanism was the worst...

**Comment by King65868** [comment]
Not since 1.7, they are a lot better now

**Comment by FakeDomi** [comment]
Mekanism cables still use TESRs for rendering in 1.12.
https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/client/render/transmitter/RenderUniversalCable.java

**Comment by Atricos** [comment]
No, with the Auto Infusion Matrix, you can easily get enough wherever you need them.
