### ISSUE TITLE
Minecraft just crashes when i try to load the modpack

### ISSUE THREAD

**Issue by Wolf9513** [Divine-Journey-2/main#343]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.4.0

**Java version:**
version 8 update 301 build 1.8.0_301-b09

**Description:**
A clear and concise description of how the crash happened.
when i click play on the curse launcher a few seconds later it crashes 
**When did the crash happen?**
During loadup (at which phase?) / when entering the world / when joining the server / when placing a certain block / ...

when i open the game 

**Minecraft crash report:**
https://pastebin.com/asd ...
(You can attach any number of them, but please describe when each of them occurred.)
https://pastebin.com/4X7hhYTg

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
Ex. "I dedicated 6 GBs and my PC has 8 GBs of RAM." [This is the bare minimum - if you have less, that might be the cause of the crash.]
i am using 11 on the client
**Screenshots:**
If applicable, add screenshots to help explain how your crash happened. These can also be attached to the "Description" or "Step to reproduce" sections. If you have no screenshots, this part can be removed.

**Additional context:**
Add any other context about the crash here.
![image](https://user-images.githubusercontent.com/91233226/134444142-39e29c1b-fa5c-437b-bbf8-30d59e2dfc71.png)
![image](https://user-images.githubusercontent.com/91233226/134444182-2a605fdc-762f-4c31-a737-c1f01eac3f60.png)

**Comment by WaitingIdly** [comment]
You arent using Java 301, you're using Java 051, and will be as long as you use curseforge. use multimc.
Also, read that first paragraph again, you missed multiple instructions.
