### ISSUE TITLE
Arc Furnace recipe conflict: Pulverized Iron doesn't make Steel Ingots with Coke Dust

### ISSUE THREAD

**Issue by dafthaporth** [Divine-Journey-2/main#346]
**Modpack version:**
2.4.0

**Description:**
When a Pulverized Iron is put into an Immersive Engineering Arc Furnace with Coke Dust, the resulting output is a single smelted Iron ingot. The same recipe using an Iron ingot (instead of Pulverized) results in 2x Steel ingots. Both recipes are shown in JEI to produce 2x Steel ingots.

**Steps to reproduce:**
1. Build and power an Arc Furnace and put in Graphite Electrodes.
2. Put Coke dust in the 'additive' slot.
3. Put Pulverized iron in the Input slot.
4. Output will be an Iron ingot.

**Expected behavior:**
Output 2x Steel ingots.

**Screenshots:**
Arc Furnace recipe shown in JEI:
![2021-09-23_13 54 32](https://user-images.githubusercontent.com/91266076/134514262-6f0911a0-098f-4b7b-82fe-886d1f075a27.png)
Outcome:
![2021-09-23_13 46 40](https://user-images.githubusercontent.com/91266076/134514280-d48cc1b7-fd05-47e4-977d-3bb361f48e1b.png)

**Comment by Atricos** [comment]
The recipe shown above now makes 2 Ingots of Steel in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385

(Note: You can no longer smelt Iron Dust into Iron Ingot in the Arc Furnace though, but you can still do that in any Furnace.)
