### ISSUE TITLE
Clientside mod in Server Pack (Auto Run)

### ISSUE THREAD

**Issue by Willshaper** [Divine-Journey-2/main#347]
**Modpack version:**
2.4.0

**Description:**
Simple Auto Run mod is part of the Server Pack even though it's a clientside mod.

**Steps to reproduce:**
Download the 2.4.0 Server Pack and look for "simpleautorun-1.12.2-1.2.0"
https://www.curseforge.com/minecraft/mc-mods/autorun

**Expected behavior:**
N/A

**Screenshots:**
N/A

**Additional context:**
N/A

**Comment by Atricos** [comment]
Auto Run has been removed from the 2.5.0 Server Pack: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472392
