### ISSUE TITLE
Game Crashing on Startup

### ISSUE THREAD

**Issue by gmastern1** [Divine-Journey-2/main#350]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.4.0

**Java version:**
1.12.2

**Description:**
I fought Baykok next to my base and he spawn-killed me about 30-50 times. That crashed my game, and now my game crashes whenever I try to start it up

**When did the crash happen?**
When trying to join my single-player world, after it has finished loading

**Steps to reproduce:**
1. Open the game
2. Join my single player world
3. World loads
4. The game crashes
5. It takes me to the multiplayer tab for some reason

**Minecraft crash report:**
https://pastebin.com/Qg4nZuJ6**

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
I dedicated 6 gigs of RAM and I my PC has 16 gigs of RAM

**Screenshots:**
![image](https://user-images.githubusercontent.com/62083701/134589515-e13d8c62-64e4-45a1-8679-f5aa93f38111.png)

**Additional context:**
Add any other context about the crash here.

**Comment by WaitingIdly** [comment]
Using Java 0_51, 5 years out of date. if you use curseforge, regardless of settings, this version of java will be used. use a different launcher.

**Comment by gmastern1** [comment]
I did my best dude, damn. I don't dive deep into minecraft configs or anything on a daily basis, I just play stuff that interests me. Got any recommendations for other launchers that use updated Javas? The only launchers I know about are MYM and Twitch/Curseforge.

**Comment by WaitingIdly** [comment]
For ease of use, I would suggest using https://gdevs.io - its pretty lightweight, has a decent UI, and most importantly, doesnt have the java version bug. Its also quite easy to use, as you can download packs directly from curseforge and it downloads java for you. 

To change launchers, just create the DJ2 instance in GDLauncher `+ button in botton left -> Curseforge -> search "Divine Journey 2" and download latest`, and then, from your Curseforge instance, copy over your `Journeymap` folder, `Saves` folder, and `options.txt` file.
