### ISSUE TITLE
Lower blizz spawnrates in iceika

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#352]
**Modpack version:**
2.4.0

**Describe the request:**
Lower the spawnrate of blizzes in iceika

**Reasons why this should be changed:**
Blizzes currently spawn everywhere in icekia, all the time, and their range is practically infinite. This means that you're basically being bombarded on all sides by them. Not only that, but each hit debuffs the player with slowness 3, making it even more annoying to deal with them

**Comment by Atricos** [comment]
Lowered Blizz spawn rate in Iceika fro 40 to 10 in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
