### ISSUE TITLE
Remove wither bones from wither skeleton quest

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#356]
**Modpack version:**
2.4.0

**Describe the request:**
I feel like the wither bones should be removed from the quest about killing wither skeletons

**Reasons why this should be changed:**
1. This quest is integral towards game progression as it blocks off the snowglobe
2. Withered Bones are in no way required to actually defeat the wither, and thus serve no purpose in a required quest
3. There are ways (such as via world gen) to obtain wither skulls without fighting skeletons. However, wither bones force you to gather them regardless for progression

**Describe alternatives you've considered:**
While killing wither skeletons will probably grant you the bones require to complete the quest, It is still a fairly arbitrary quest requirement and limits alternative routes (E.G. world gen) to gather skulls.

**Comment by Atricos** [comment]
Wither Bones are no longer required for the quest in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385 (Make sure to use `/bq_admin default load`!)
