### ISSUE TITLE
Typo in quest book Chapter 16 - quest 'Thermal' (T3 seeds)

### ISSUE THREAD

**Issue by IntoxicatedPlatypus** [Divine-Journey-2/main#357]
Location:
In quest book, chapter 16 (Diamond from Dirt), quest 'Thermal' (Tier 3 seed row).
"... You'll need them to get **Menril** Seeds ..."

Exact fix:
The thermal elementals' seeds are used to craft Mithril seeds, not Menril seeds. The quest description should change Menril to Mithril.

**Comment by Atricos** [comment]
Fixed the typo, changed it to "Mithril" from "Menril" in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
