### ISSUE TITLE
'Elsa's long lost sister' quest has the wrong Amethyst as a reward.

### ISSUE THREAD

**Issue by dafthaporth** [Divine-Journey-2/main#358]
**Modpack version:**
2.4.0

**Description:**
One of the choice rewards for 'Elsa's long lost sister' quest is Amethyst Ore from Bewitchment - which has no uses.

**Expected behavior:**
Reward Amethyst Ore from Mystical World.

**Screenshots:**
![2021-09-25_20 14 53](https://user-images.githubusercontent.com/91266076/134783882-a312b334-db6e-4c42-98fa-96a51b8e03c9.png)

**Comment by Atricos** [comment]
Now it gives you the correct type of Amethyst Ore in 2.5.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3472385
