### ISSUE TITLE
Wire for plates without power !

### ISSUE THREAD

**Issue by iKurama** [Divine-Journey-2/main#360]
**Modpack version:**
2.4.0

**Describe the request:**
You can hammer ingots into plates. I now present: Plate(s) to wire(s). Be it two plates for one wire _or_ one to one.

**Reasons why this should be added:**
You're out of power, it is clogged up and you really need a wire or two, to solve it.

**Describe alternatives you've considered:**
Multiple presses, but frankly invalid if you don't have the power to do so.

**Comment by Pajama-Day** [comment]
Isn't there a plate to wire recipe [already](https://i.imgur.com/bbr4Vb4.png)? There's even ones for the other three IE wires as well: [Electrum](https://i.imgur.com/AozeJEK.png), [Aluminum](https://i.imgur.com/aWzdMXH.png), and [Steel](https://i.imgur.com/42d68cX.png).

**Comment by King65868** [comment]
There is, this request doesn’t make sense

**Comment by Atricos** [comment]
Yeah, you can manually craft Plates into Wires.
