### ISSUE TITLE
Add a Lumium recipe in the Arc Furnace

### ISSUE THREAD

**Issue by Pajama-Day** [Divine-Journey-2/main#362]
**Modpack version:**
2.4.0, still not in 2.5.0 either

**Describe the request:**
Lumium should be craftable via the Arc Furnace (not just the Smeltery or other alloying methods e.g. Alloy Smelter).

**Reasons why this should be changed:**
Signalum, a material available through the Smeltery and obtainable earlier than Lumium, can be made via the Arc Furnace, yet Lumium is not. Furthermore, Enderium, another alloy from the same mod, is ALSO craftable through the Arc Furnace. Lumium is the only exception. The recipe(s) can be the same as the Alloy Smelter recipes for Lumium that also already exist.

**Describe alternatives you've considered:**
If Lumium is somehow meant to be gated, remove the Smeltery and Crafting Table recipes instead.

**Additional context:**
The only recipe Lumium currently has is simply [smelting Lumium Blend](https://i.imgur.com/DKzvEut.png).
The existing [Signalum](https://i.imgur.com/rhviInQ.png) and [Enderium](https://i.imgur.com/0k8wE5h.png) recipes.
The existing [Lumium recipes](https://i.imgur.com/AI8RzGy.png) via EnderIO's Alloy Smelter.

**Comment by Atricos** [comment]
Added a recipe for it in the Arc Furnace in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
