### ISSUE TITLE
Additional info in engraver quest

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#363]
**Modpack version:**
2.4.0

**Describe the request:**
I suggest adding in quest "The writing's on the wall"(ch18, top left corner) that engraver can also be found in some omothol houses.

**Reasons why this should be added:**
Why not? :)

**Describe alternatives you've considered:**
Remove the engraver spawn in omothol

**Comment by Atricos** [comment]
Added the info to the Engraver quest in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
