### ISSUE TITLE
Thaumcraft Redstone Inlay doesn't craft correct amount

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#365]
**Modpack version:**
2.4.0

**Description:**
If you do the Redstone Inlay recipe in the runic matrix, you only get 1 instead of the 4 shown in JEI

**Steps to reproduce:**
1. make a runic matrix setup and provide it with enough essentia for the Redstone Inlay recipe
2. Craft the Redstone Inlay
3. You only get one

**Expected behavior:**
To get 4

**Screenshots:**

https://user-images.githubusercontent.com/57828910/134816095-45f1517f-476d-4d52-ab1f-9d5472164a8e.mp4

**Comment by Waisse** [comment]
Yes it's not working, only one inlay per infusion

**Comment by Atricos** [comment]
Added a custom item called "Redstone Inlay Package". The Infusion Matrix now crafts this item, which can then be converted into 4 Redstone Inlays. I haven't change the Auto Infusion Matrix recipe, becuase it's been working correctly.

This is in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
