### ISSUE TITLE
Absence of QOL in building(better building wands recipes)

### ISSUE THREAD

**Issue by NaminBeforeGamin** [Divine-Journey-2/main#366]
**Modpack version:**
2.4.0(not in 2.5.0 either)

**Describe the request:**
The recipe for any sort of builders wand is too gated for being just qol, so change it. For example, the stone builders wand is gated until chapter 9 in which it has low durability(131) AND requires diamonds just to craft.  

**Reasons why this should be changed:**
For example, the stone builders wand is gated until chapter 9 in which it has low durability and requires diamonds(like an 8th of one for gp powder). This is a basic feature, a qol, in most packs that is heavily absent in this one. 

**Describe alternatives you've considered:**

-make the builders wands from better builders wands ALL unbreakable(the range on say a stone builder wand is already garbage so I believe this to be fair) replace the current wand from xu2 in the crafting tier with the creative one as well.

**Comment by NaminBeforeGamin** [comment]
I am not quite sure if this will pass, probably won't, but I am still open to discourse with the devs as to why the wands are like this.

**Comment by Ringedtech203** [comment]
Atri seems to be against anything to do with building

**Comment by NaminBeforeGamin** [comment]
is there anything in specifics as to why hes against it? since ik the point of the pack is to be hard but building a large area to house automation is pretty integral like id say late early game and mid game onward

**Comment by Ringedtech203** [comment]
idk. I've just noticed that most things building related seem to be declined

**Comment by NaminBeforeGamin** [comment]
o like did he decline the building gadgets request? kinda wack lol. we dont even have projectors for IE multiblocks so its a pain to place everything. on god spent like 30 minutes building the excavator

**Comment by KleinGrrmpf** [comment]
But the reason that there are no projectors for the multiblocks is because that is a feature of Immersive Petroleum which is not in the pack (sadly because it adds an oil pump that mines oil the way an Excavator mines ores).

**Comment by NaminBeforeGamin** [comment]
yeah but itd still be nice to have a substitute

**Comment by KleinGrrmpf** [comment]
I don't think there is a substitute. And after you have built them a few times you kinda have them down. And honestly, it is not that bad. But I don't get the builders wands either...

**Comment by Lgmrszd** [comment]
Absolutely agree on this. I don't know any way building wands can give advantage in progression other than just making your base look nicer, so such gating seems unnecessary, unless there are reasons we don't know.

**Comment by 1234abcdcba4321** [comment]
They're against building QoL... but then add OreExcavation to the pack for some reason?????

(I mean hey, at least you get some exchangers over in the last third of the pack.)

**Comment by Atricos** [comment]
Made all the Wands cheaper, moved them to earlier chapters, and increased their durability by a lot in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373

Details:
- They're now available in Chapter 1/4/9/11/14 (instead of 9/11/13/17/18).
- Also moved the Destruction Wand to Chapter 9.
- Moved the ExtraUtils Wand quests to Chapter 9.
- Created a new quest in Chapter 13 for the Unbreakable Wand.
- Increased the durability of all (non-unbrakable) Better Builder's Wands: Stone: 130 -> 1000, Iron: 250 - > 3000, Diamond: 1561 -> 8000.

I'm going to close this now. If this isn't satisfactory, feel free to reopen it.
