### ISSUE TITLE
Consistency for Roots and Underground Biomes; On Scraping for Terra Moss

### ISSUE THREAD

**Issue by BiFrossGames** [Divine-Journey-2/main#368]
**Modpack version:**
2.5.0

**Describe the request:**
I would love a consistency change for Terra Moss! All of the Underground Biomes stones have mossy versions, and as someone who *loves* Roots, I felt almost let down when I couldn't scrape Mossy Lignite or Mossy Gabbro, or whatever stone I might try to scrape besides vanilla cobble.

**Reasons why this should be added:**
Adding this consistency would be a nice QoL change. Small, but impactful enough that someone will take note and go "hey the dev added this in that's pretty neat"

**Describe alternatives you've considered:**
N/A

**Additional context:**
The modified config, but not the scripts disabling Mossy Stone crafting, is attached.

[moss.txt](https://github.com/Divine-Journey-2/main/files/7233130/moss.txt)

**Comment by iKurama** [comment]
Mine is, put it in a crafting table of 2 and get vanilla version.

**Comment by KleinGrrmpf** [comment]
You can just mine up all the mossy stone and convert it one to one to vanilla mossy cobble which you can then scrape.

**Comment by Atricos** [comment]
Added the file you provided, except the mossy and non-mossy variants were swapped. Now it's working correctly in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
