### ISSUE TITLE
Sand in Pulverizer makes Gravel

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#369]
**Modpack version:**
2.4.0

**Description:**
When you put Sand in a Pulverizer you get Gravel

**Steps to reproduce:**
1. Power a Pulverizer
2. Put Sand into it
3. Observe it becoming Gravel

**Expected behavior:**
You either can't put Sand in a Pulverizer or putting Sand into a Pulverizer gets you silicon the same way that Sand becomes silicon in Mekanism's Crusher.

**Screenshots:**
JEI:
![grafik](https://user-images.githubusercontent.com/50833808/134908088-bdb3ded3-d18d-4943-8aa4-37fc13e25d02.png)

In the machine:
![grafik](https://user-images.githubusercontent.com/50833808/134908303-74071e22-9efd-4df5-aa72-036e855b1981.png)

**Comment by Atricos** [comment]
This is absolutely intended. I added this functionality recently. You can get Silicon from a SAG Mill or a Mekanism Crusher.
