### ISSUE TITLE
Endervoir/Unending Bowl recipe is impossible to automate before Modularium

### ISSUE THREAD

**Issue by 40110** [Divine-Journey-2/main#373]
**Modpack version:**
2.5.0

**Describe the request:**
Endervoir has a Fey Crafting recipe, making it impossible to automate before the Runic Crafter, which needs Modularium. Automation for this recipe is unnecessarily gated too far in, there should be an alternative way of making Endervoirs or a different recipe altogether.

**Reasons why this should be changed:**
Making Endervoirs manually is inconvenient, especially when they use an unstackable item and only craft 1 at a time. Being able to automate this process before Chapter 18 wouldn't break the balance in any way, considering they can be crafted as soon as Chapter 3.

**Describe alternatives you've considered:**
Move it to a Pyre recipe, which is automatable earlier through the Mechanical User.

**Additional context:**

**Comment by 1234abcdcba4321** [comment]
But there's like... literally only two items you ever want a runic crafter for and this is one of them. A better solution would just be to move the runic crafter earlier, since it's not like automating elemental soil hurts much either.

**Comment by Atricos** [comment]
You can just batch craft a bunch on Endervoirs at once. Put it all the ingredients for multiple Endervoirs at once, right click with a Knife, and you've crafted all of them at once.

**Comment by King65868** [comment]
You can’t do them all at once is the point, it’s 1 at a time since the unstackable bottles

**Comment by Atricos** [comment]
Right, okay. Still, I don't think you'll need that much.
