### ISSUE TITLE
Absurd augmented capacity rune crafting recipe

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#374]
**Modpack version:**
2.4.0.

**Describe the request:**
I think that augmented capacity rune recipe is very expensive and painful to do(even with automation). In ch 18 you need 120k lp for orb and big amounts for other items(i know that this can be done even without storing needed lp but still). For them to be more effective than normal capacity runes, you need 15. You can find how much it costs in screenshots part of this request.

**Reasons why this should be changed:**
Because the recipe is absurdly expensive and you need to wait a lot of time for all empowered things as well as thousands of different alloys to process(you don't have access for better elevatium at this moment)

**Describe alternatives you've considered:**
Tweak demonically gargantuan drums/make them craft by 2-4/just remove these drums from runes recipe.

**Additional context:**
Here are the materials needed for 15 runes:
![image](https://user-images.githubusercontent.com/87584837/135118357-6d5e8b17-140c-48b9-a58b-ee026f12ec16.png)
![image](https://user-images.githubusercontent.com/87584837/135118387-0b3d4be9-ef31-4ab5-81fd-f44fbd2e95c3.png)
![image](https://user-images.githubusercontent.com/87584837/135118409-66cd921c-af35-4e99-a37f-b550d1b3d319.png)
![image](https://user-images.githubusercontent.com/87584837/135118430-d58a96b7-1ef7-4e5a-a403-02745cbc61a9.png)
![image](https://user-images.githubusercontent.com/87584837/135118445-a413174c-cc91-428a-9f3d-e75c1a33fe3f.png)

**Comment by 1234abcdcba4321** [comment]
You can get 120k LP by just using 55 normal capacity runes, too. A lot of things are ridiculously expensive in this pack; those gargantuan drums are pretty much the only thing that makes the runes expensive.
If you find it too expensive, make a better automation setup. Unlike before chapter 13, you can afford to scale things up if it's too slow.

**Comment by Atricos** [comment]
All I did for now is made the Mekanism Teleportation Core craft 2 at a time (up from 1), in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373

However if you have everything autocrafted, then no matter how crazy the recipe is, you can just click it from AE and sit back while it does its thing. You should have enough resources from a Quarry, and it's not like you need thousands of Capacity Runes.

If you recommend any more specific changes though, I'll think about them.
