### ISSUE TITLE
Mythic Pickaxe Voids items

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#375]
**Modpack version:**
2.4.0

**Description:**
 
Mystic and Skyfather Pickaxe can void and dupe blocks

**Steps to reproduce:**

Enter a world
Get either pickaxe
Break a block that has no smelting recipe

For duping, simply apply silktouch on the Mystic. The Skyfather acts normally, except both will void any Block Entity, enchanted or not.

**Expected behavior:**
Getting the item back

**Comment by Ringedtech203** [comment]
Nice use of the issue format

**Comment by luciscout** [comment]
I am sorry it autosubmitted when I went to hit enter 
![image](https://user-images.githubusercontent.com/77116048/135167135-f5898a86-30d3-481e-9c70-67204b2738c9.png)
It is now updated

**Comment by luciscout** [comment]
Been told offline this still is confusing, let me lay it out differently

With a Skyfather Pickaxe:

- Unenchanted, it voids any block with no smelting recipe
- Enchanted with Silk Touch, it works normally except for entities, which it will still void

With a Mystic Pickaxe:

- Unenchanted, it voids any block with no smelting recipe
- Enchanted with Silk Touch, it dupes any non-entity block (for example, one stone gives 1 stone and 1 cobblestone, one grass block gives 1 grass and 1 dirt, and one diamond block gives 2 diamond blocks) and will void any entity, like the LE Receiver Tier 1

To note, both of these work as expected when applied as Tinker's Tools, but not as the original mod tools.

**Comment by Atricos** [comment]
Disabled all LightningCraft Electricium, Skyfather and Mystic tools (didn't disable the Sword, it seemed to be fine), and made the Galacticraft Heavy Duty tools craft out of the tier before Electricium, which is Cold Iron in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
