### ISSUE TITLE
Absurd thermal elemental spawn rates in modded dimensions

### ISSUE THREAD

**Issue by nekojo1023** [Divine-Journey-2/main#376]
Title
For every mob that's supposed to be there, there's like 5 thermal elementals just chilling
It's extremely irritating just trying to explore and constantly being shot from damn near every direction because they aggro from a mile away
pics related, iceika and atum
they're just everywhere, can't go two feet without seeing another
![2021-09-28_16 43 13](https://user-images.githubusercontent.com/71620315/135162989-1600ccc1-709f-4c5e-8236-3dd9b489073a.png)
![2021-09-28_16 48 48](https://user-images.githubusercontent.com/71620315/135163491-cb44af17-c528-4f89-bf28-435bd5b7f370.png)
![2021-09-28_16 50 37](https://user-images.githubusercontent.com/71620315/135163614-eb5cd719-ef9a-441d-b2b8-42357829f603.png)
![2021-09-28_16 51 05](https://user-images.githubusercontent.com/71620315/135163667-d8b0961c-6c8c-4449-9d69-b42146330f43.png)

added glowing effect for clarity

![2021-09-28_17 57 24](https://user-images.githubusercontent.com/71620315/135171624-4a71a5fb-b0d0-4bdc-b5e5-b47a42fb2f10.png)
![2021-09-28_17 59 38](https://user-images.githubusercontent.com/71620315/135171649-94acd6fd-0238-4100-87be-403acf26def0.png)

**Comment by WaitingIdly** [comment]
please fill out the designated form instead of creating a blank issue

**Comment by antrobot1234** [comment]
related to #352

**Comment by Atricos** [comment]
I assume you're playing on 2.4.0 or earlier. This was already fixed in 2.5.0 Please include your version number next time.
