### ISSUE TITLE
Casting Cobalt gives a different block than expected

### ISSUE THREAD

**Issue by BiFrossGames** [Divine-Journey-2/main#378]
**Modpack version:**
2.5.0

**Description:**
When casting Cobalt blocks, the Casting Basing makes Chisel Cobalt Caution blocks

**Steps to reproduce:**
1. Melt 9 ingots' worth of Cobalt in the smeltery
2. Pour the Cobalt into a Casting Basin
3. Observe the @Chisel Block of Cobalt #Caution

**Expected behavior:**
I expected TiCon's Cobalt Block to be casted.

**Screenshots:**
![image](https://user-images.githubusercontent.com/12004007/135329338-4f66d573-c1fa-4cab-9f7c-eadf0bd277dd.png)

**Comment by Atricos** [comment]
Now it gives the correct block in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
