### ISSUE TITLE
An adjustment to the way Refined Obsidian is made

### ISSUE THREAD

**Issue by dafthaporth** [Divine-Journey-2/main#379]
**Modpack version:**
2.4.0

**Describe the request:**
Refined Obsidian ingots can be made without Osmium because of a Tinker's Smeltery recipe.

Refined Obsidian Dust is made in the Metallurgic Infuser:
Pulverized Obsidian + Diamond.
![2021-09-29_18 04 05](https://user-images.githubusercontent.com/91266076/135325805-648c01a2-4daf-4a18-8db0-f94b7858e54d.png)

The next step should be to use the Osmium compressor to turn it into a Refined Obsidian Ingot:
![2021-09-29_18 04 49](https://user-images.githubusercontent.com/91266076/135326020-f5ac16be-6767-47ee-84a3-195781e76a15.png)

But it's possible to skip this step by smelting the dust directly in the Smeltery, and casting it out as an ingot:
![2021-09-29_18 04 36](https://user-images.githubusercontent.com/91266076/135326797-ddf754ad-8fd5-4939-ba21-038fc701cd34.png)

**Reasons why this should be changed:**
Refined Obsidian is used to craft Dark Steel and Osgloglas - which are common materials in the pack - so saving an Osmium ingot per craft makes a huge difference.

**Describe alternatives you've considered:**
It's a material used for tool parts, so the best solution would be to just remove the recipe for smelting the dust (rather than losing the ablity to cast an ingot).

**Additional context:**
I'm playing on version 2.4.0 but I've read through the changelog of the latest version (2.5.0) and haven't noticed any changes that would affect this issue, apologies if so.

**Comment by Atricos** [comment]
Refined Obsidian Dust can no longer be melted in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
