### ISSUE TITLE
Electrotine Ore

### ISSUE THREAD

**Issue by King65868** [Divine-Journey-2/main#381]
**Modpack version:**
2.5.0

**Description:**
Electrotine Ore can not be placed down with a builders wand from better builder's wands. 

**Steps to reproduce:**
1. Place down Electrotine Ore.
2. Try to use a builders wand from better builder's wands and it not work.

**Expected behavior:**
I would expect the ore to place.

**Screenshots:**
![2021-09-29](https://user-images.githubusercontent.com/84357753/135371014-5496032f-1172-46ce-b357-6f3062e592ac.png)
(Me trying to use the builders wand to place the ore.)

**Additional context:**
Extra utilities wands work fine for placing the ore.

**Comment by Atricos** [comment]
Unfortunately no custom blocks can be placed down with Better Builder's Wands. Try any block from ContentTweaker, e.g. Demonlord Block, Energized Osmium Block, Charred Stone, etc. etc.

Not much I can do about it, it's an incorrect mod interaction between Better Builder's Wands and ContentTweaker.

Use one of the Extra Utilities Wands.

**Comment by King65868** [comment]
Good to know
