### ISSUE TITLE
Iridescent Altar recipes requiring faint constellations

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#382]
**Modpack version:**
2.4.0

**Description:**
Some seed recipes in the Iridescent Altar require crystals attuned to faint constellations, which you cannot do

**Expected behavior:**
Have the recipe use non-faint constellations

**Screenshots:**
These are all the recipes that use faint constellations:
Coralium Seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469472-481e32d5-8eba-4b38-a024-ac918d9dd805.png)
Alumite Seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469585-fdfb1cc9-74f1-4767-9c04-e105a3ebab6a.png)
Elementium Seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469614-38455dff-6401-4f35-9c6c-d41c3cedc3fe.png)
Dark Steel Seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469683-d8d92191-747d-4537-b0bc-69ecbd724227.png)
Fluxed Electrum Seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469745-16964570-b70c-4fc6-bba9-f5654b2c63d0.png)
Enderman seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469793-83ba7392-981a-4ae4-9196-9cb2ede58911.png)
Ghast Seeds:
![grafik](https://user-images.githubusercontent.com/57828910/135469940-a1bcfbce-c978-42a7-a8bb-d6a80a23ef0b.png)

**Comment by JohanniklasLp** [comment]
Abyssalnite Seeds
Dreadium Seeds
Enderium Seeds
Pulsating Iron Seeds
Vibrant Alloy Seeds
Alchemical Brass
Meteoric Iron
End Steel

All of these Seeds require seeds from the original comment to craft and are thus also unobtainable rn

**Comment by Atricos** [comment]
Changed all the items you showed to require non-faint Constellations in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
