### ISSUE TITLE
Adding a way to spawn Pech

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#383]
**Modpack version:**
2.4.0

**Describe the request:**
Some way to spawn pech or get their spawnegg, using either Materials (for eg the roots summon ritual) or crafting stations (eg the auto infusion matrix) from Thaumcraft or another mod later on in progression.

**Reasons why this should be added:**
Because they were disabled so you cannot use them to skip progression, but there is no way to get them once you are at that point of progression. They allow for a few more possibilities in the Spell and Auromancy section and are needed for the 100% completion of the thaumonomicon.

**Comment by Atricos** [comment]
No, even when the player has progressed to Thaumcraft, they're an incredibly abusable way to farm materials that were made much more expensive in the pack, simply by using some Gold, Diamdonds and Emeralds.

**Comment by 1234abcdcba4321** [comment]
It would be good if they could still be crafted, even if it costs a Tier 5 Crafting Seed or something of similar price.

Though I think gating it around ch23 would do fine.

**Comment by JohanniklasLp** [comment]
Yeah, as I wrote,
> or another mod later on in progression
this can be anywhere between bewitchment/lightningcraft and projectE/avaritia
I don't know what items they give, so I cannot say when you should have made certain items you get from them yourself/producing enough of them anyway, so that you don't get the big abuse advantage from them, but the point has to be somewhere since you have to make a creative chest anyway.
