### ISSUE TITLE
Fix suggestion for Auto-Infusion Matrix (250 essentia recipes hatch overflow)

### ISSUE THREAD

**Issue by IntoxicatedPlatypus** [Divine-Journey-2/main#384]
At the moment using the AIM is impossible for recipes which cost 250 of an essentia. This is because adjacent essentia hatches will instantly overflow when the recipe starts, which makes pushing original essentia back in impossible.

A simple fix to that is to change AIM recipes to use 249 essentia instead of 250. This will ensure that at least 1 essentia stays in each hatch, and overflowing won't happen.

**Comment by KleinGrrmpf** [comment]
The auto infusion matrix has the exact amount of input hatches as there are essentia types, so you just need an essentia export bus for every type of essentia and you are good to go

**Comment by IntoxicatedPlatypus** [comment]
The problem is that when a recipe uses up all 250 essentia from a hatch, neighboring hatches will 'overflow' to the (now temporarily empty) hatch. Having separate busses won't fix this, since they can't export to a hatch which has a different essentia type.

**Comment by KleinGrrmpf** [comment]
Oh, I wasn't aware that this is a thing.

**Comment by 1234abcdcba4321** [comment]
Another option to fix this would be to change the layout of the machine to not have any 2 adjacent essentia input hatches. This is probably less effort to change, but would require players to rebuild the machine. But it is a better fix, in my opinion.

**Comment by KleinGrrmpf** [comment]
But I think that rebuilding the machine is not really possible because it the requirements (set by Atri for people to submit the modular machine) was that it has to fit into a quarter of a chunk and redesigning this machine with the 41 hatches not touching each other would most likely not make for a pretty machine and still fit into a 7x7 area...
I wonder what the testers who tested some auto infusion crafting have to say to this.

**Comment by IntoxicatedPlatypus** [comment]
It would be possible if the structure was taller, but yeah, I don't think it's a good idea to change the structure now. Another possibility is to reduce all essentia costs in the AIM, and just say in the quest book that it provides some discount. That way there won't be 'odd' numbers like 249

**Comment by Atricos** [comment]
Each recipe that took 250 of some type of Essentia now takes 240 in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373. This'll leave the Hatches with 10 Essentia each, preventing overflow.
