### ISSUE TITLE
state that time change ritual is disabled

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#385]
**Modpack version:**
2.4.0

**Describe the request:**
Add a tooltip to the Imperfect Ritual Stone in blood magic saying that the ritual that sets time to night is disabled.
There is also a roots ritual that advances time forward, but I haven't actually checked if it is disabled; if it is, a tooltip or quest description about it should be added somewhere.

**Reasons why this should be added:**
I tried to use the (blood magic) ritual, but there was no feedback for why it was not working, and thus I would have reported this as a bug if Idly didn't tell me it's disabled.

**Describe alternatives you've considered:**
Actually enable time-changing effects. As these mainly help for Chapter 23, an option is making the Imperfect Ritual Stone a quest item in late ch23 (probably requiring at least starlight infusion) (as the stone is really not helpful for anything else).

**Additional context:**
I'm playing on a multiplayer server, and haven't checked to see if they would also be disabled if I was playing on singleplayer.

**Comment by Atricos** [comment]
Instead I enabled it, and gated the Imperfect Ritual Stone to Chapter 23 (and also added a quest for it) in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
