### ISSUE TITLE
Enhanced Building Guide is not craftable with manually crafted Building Guide

### ISSUE THREAD

**Issue by Lgmrszd** [Divine-Journey-2/main#386]
**Modpack version:**
2.4.0 (I checked recipe script and it's not fixed in 2.5.0)

**Description:**
As title says. If you place and break Building Guide though, EBG becomes craftable

**Steps to reproduce:**
1. Attempt to craft Enhanced Building Guide using manually crafted Building Guide

**Expected behavior:**
It is craftable

**Screenshots:**
![image](https://user-images.githubusercontent.com/16291541/135539427-d0215560-50a5-4375-85f6-a66b72161938.png)

**Additional context:**
According to recipes, Building Guide required for the recipe needs to have empty tag: https://github.com/Divine-Journey-2/main/blob/3dbef9133022577890da9f600cbafa2a354b8184/scripts/OpenBlocks.zs#L70

Yet the one you craft doesn't have a recipe at all

Possible solutions:
 - Add empty tag for Building Guide recipe
 - Add hidden recipe for EBG using `.withEmptyTag()` instead of `.withTag({})`
 - Unsure, but maybe simply not using IItemStack modifier might work?

**Comment by Atricos** [comment]
Now it can be crafted with any tag in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373

Note: By applying no functions to the item, it asks for an item with *any* tag, so that's what I did.
