### ISSUE TITLE
Conductive Iron Seeds recipe

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#387]
**Modpack version:**
2.5.0

**Describe the request:**
Conductive Iron Seeds require 4 manyullyn blocks to craft. Instead, they should require 4 conductive iron blocks.

**Reasons why this should be changed:**
Because it would make way more sense.

**Comment by Atricos** [comment]
Fixed in 2.6.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373), now it requires Conductive Iron Blocks. Oops!
