### ISSUE TITLE
Angel ring only accepts no-winged flügel tiara

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#388]
**Modpack version:**
2.5.0

**Description:**
You cannot craft an Angel ring from a flügel Tiara with wings

**Steps to reproduce:**
1. Get a flügel tiara
2. change the wings from "No wings" to any wing type
3. try to craft the angel ring with it
4. You can't

**Expected behavior:**
Being either able to craft the no wing tiara from any other tiara or being able to use any tiara to craft the angel ring

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/57828910/135661272-1450af8e-b867-4b55-a40e-bba93acf42fb.png)

![grafik](https://user-images.githubusercontent.com/57828910/135661713-9b38bd03-7f48-4e98-973b-f55c7eb89c89.png)

**Comment by Atricos** [comment]
Fixed in 2.6.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373), now you can use any Flügel Tiara in the recipe.
