### ISSUE TITLE
More ways to make HOP Graphite Dust

### ISSUE THREAD

**Issue by Electrolyte220** [Divine-Journey-2/main#389]
**Modpack version:**
2.5.0

**Describe the request:**
I would like more ways to crush down HOP Graphite ingots to dust, such as using the Mekanism Crusher and/or the EXU2 Crusher, as right now, I have to use the IE Crusher until I get access to the Pulverizer.

**Reasons why this should be added:**
Since getting access to the Mekanism Crusher and Enrichment Chamber, I've moved fully away from and disassembled my IE Crusher, believing that I would not need it anymore. However, it seems that the only way to get HOP Graphite Dust in this stage of the game is to use the IE Crusher, meaning I would have to re-assemble it. Adding these QOL recipes would allow me to not have a giant multiblock sitting in my base that's only used for one recipe once in a while.

**Describe alternatives you've considered:**
The alternative to this would be re-assembling the IE Crusher, and going through progression until I reach the Pulverizer.

**Additional context:**
N/A

**Comment by Atricos** [comment]
HOP Graphite can now be crushed in the AE2 Grindstone, Extra Utilities Crusher, SAG Mill, and Mekanism Crusher in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
