### ISSUE TITLE
Enderman and Peridot Seeds won't spread

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#391]
**Modpack version:**
2.5.0

**Description:**
Fully Grown mystical agriculture nether seeds in crop sticks won't spread to other farmland tiles with crop sticks.

**Steps to reproduce:**
1. make a few adjacent blocks to farmland and hydrate them
2. place one crop sticks on each
3. place a nether seed in one of the fields and let it grow (you may use "/gamerule randomTickSpeed 1000" to speed it up)
4. The nether seed will not spread.

**Expected behavior:**
For nether seeds to spread

**Screenshots:**
My test setup
![grafik](https://user-images.githubusercontent.com/57828910/135679397-13ecfc7b-b670-4ec2-b953-1ce6d91b05f4.png)

Nether Seeds don't need anything else according to JEI
![grafik](https://user-images.githubusercontent.com/57828910/135679950-f6dc0d6b-9cf3-4462-852c-a6c2a730bc03.png)

**Additional context:**
Every other seed I tried (almost all seeds up to tier 4) didn't have that problem.
They spread very fast with the gamerule command enabled

**Comment by Atricos** [comment]
Accidentally had spreading set to `0.0` for this seed specifically somehow, so I fixed it, made it `0.1` (which is the same as all other Seeds) in 2.6.0: HOP Graphite can now be crushed in the AE2 Grindstone, Extra Utilities Crusher, SAG Mill, and Mekanism Crusher.

**Comment by JohanniklasLp** [comment]
![grafik](https://user-images.githubusercontent.com/57828910/135770368-7e358e38-93e8-4a17-8b6b-74bc543594d3.png)
Same issue with the enderman seeds

**Comment by JohanniklasLp** [comment]
And Peridot Seeds.

I haven't been able to find more seed with that issue.
