### ISSUE TITLE
some inaccurate tips

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#392]
**Location:**
The loading screen tips. (Line numbers are by loading tips.cfg in a text editor with line numbers.)

**Exact fix:**
Line 79 - "Modular Fey Crafter" -> "Runic Crafter"
Line 99 - change to "You must explore Atum, the Erebus, the Aether, Iceika, and optionally the Twilight Forest in the first quarter of the pack!" (The way it is now, it seems like you have the choice to do all of them when the only one you have a choice for is twilight.)
Line 121 - "Astral Sorcery" -> "DivineRPG". (AS isn't really intertwined inside the progression like the ones in the first half of the magic mods, and also even thaum/bewitchment. This makes "mix" feel off; an alternative would be to fix that.)

And yes, this could probably be placed as feature request instead of typo. But typo is the label it fits most closely.

**Comment by Atricos** [comment]
Changed all the tips you suggested in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
