### ISSUE TITLE
Stellar energy conduits are too cheap compared to cryoducts

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#393]
**Modpack version:**
2.5.0

**Describe the request:**
For high-throughput power transfer in ch21-25, the player has two options - Cryo-Stabilized Fluxducts and Stellar Energy Conduits. Cryoducts should be cheaper, stellar conduits more expensive, or both.
Specific request would be to lower the yield of the stellar conduit recipe from 6 -> 3, and cryoducts 1 -> 2 (or make them available earlier).

**Reasons why this should be changed:**
The player probably isn't going to need 2BRF/t, so the fact that cryoducts can actually transfer more doesn't really matter. Hence, the stellar conduits are just flat-out better, since they come with all of the advantages that conduits have that cryoducts definitely don't (placing in the same block as other conduits, being able to disconnect specific connections, redstone control).

Stellar conduits take stellar alloy, which requires gaia spirits. However, you get 12 conduits for a single gaia kill (and gaia is weak enough to just go kill 5 at a time), while making those same 12 cryoducts takes a fairly large amount of resources... though it is automatable with enough effort to not be worth it unless you actually need like a thousand cables.

**Describe alternatives you've considered:**
Just lower the transfer rate of stellar conduits to something around 25 million rf/t, even adding a more expensive tier above that if needed,

**Additional context:**
As #342 was rejected, I believe this is more likely to be accepted if the suggestion is to make stellar conduits more expensive rather than cheapening cryoducts. However, I believe both that cryoducts are too expensive and stellar conduits too cheap.

There are other options for long range power transfer - P2P Tunnel (FE) is one, but I'm not sure how much it can transfer. The more obvious one is integrated dynamics. These are both also viable options that suffice for most purposes - if the issue is people making large cryoduct networks being laggy, that's fine; but people shouldn't just be able to use a strictly better alternative for cheaper. These options are very cheap for long distances but are a pain for connecting many short-distance things, which is where using a few cryoducts or stellar conduits to connect everything shines.

**Comment by luciscout** [comment]
If Stellar Conduits are to be flat nerfed in their RF/t transfer, they should have a higher tier to upgrade to or not be nerfed so low - Cryoducts are bad for performance in both FPS and TPS

**Comment by Atricos** [comment]
Reduced the transfer rate of Stellar Energy Conduits from 2 Billion RF/tick to 10,485,760 RF/tick (32x the previous tier), to make it more inline with Cryoducts in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373

If additional adjustments still need to be made, then feel free to reopen the issue.

**Comment by 1234abcdcba4321** [comment]
Hi, people told me to tell idly to reopen the issue, so hey idly can you reopen the issue thanks.

The problem with the current fix is that, while ID can be used to interface power around, conduits are still more convenient and it would be good to have the option to use them if someone does want to use them for very high throughput power.

I'm not sure what a good material to have a new conduit tier cost would be. I feel like something along the lines of rainbow tablets, superium, or awakened draconium could be good.
