### ISSUE TITLE
Cant craft black hole unit

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#396]
**Modpack version:**
2.5.0

**Description:**
The black hole unit dosent craft, presumbably becuase it dosent like either the quantum entangloporter or the 64k cells

**Screenshots:**
![image](https://user-images.githubusercontent.com/8618678/135727213-7a9671ea-29cc-47eb-aee7-a9688301fabb.png)

**Comment by Atricos** [comment]
The items should no longer ask for any specific NBT (any NBT should work) in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
