### ISSUE TITLE
Ender IO Conduits cant pump Glod into the Empowerer

### ISSUE THREAD

**Issue by Command-Crafter** [Divine-Journey-2/main#397]
**Modpack version:**
2.5.0

**Description:**
Ender IO Conduits cannot insert Glod into the Empowerer

**Steps to reproduce:**
1. Get into a world
2. Place down a Chest, an item Conduit and an Empowerer
3. Set the Conduit to extract from the Chest and insert into the Empowerer
4. Put a Glod into the Chest
5. Nothing happens

**Expected behavior:**
Insertion of the glod into the Empowerer

**Screenshots:**
![image](https://user-images.githubusercontent.com/34944204/135729131-1b627d30-bf29-4246-be9f-c4c156ece7f5.png)
![image](https://user-images.githubusercontent.com/34944204/135729192-8de9faea-5c06-415f-98eb-a7ec76118d14.png)

**Additional context:**
Conduits work as expected for Crystal Bundles and all other empowerable Items

**Comment by Atricos** [comment]
I just tested it and it worked (in Singleplayer):
![image](https://user-images.githubusercontent.com/24854267/135729271-155c91ce-95b0-4303-887a-47780c9ecc2d.png)

Can you insert any other items?

**Comment by Command-Crafter** [comment]
Huh, thats odd.
All empowerable items other than Glod can be inserted.

**Comment by Atricos** [comment]
Did you perhaps use a Filter on the Conduit?

**Comment by Command-Crafter** [comment]
No, its just a regular item Conduit.
And I cant even insert Glod by right clicking

**Comment by Atricos** [comment]
Are you using the Glod you crafted? Or one you cheated in?

**Comment by Command-Crafter** [comment]
Ah I see now why it didnt work.
I first noticed this "bug" when I used Conduits with filters. I must have dragged the Glod from JEI and not noticed that I left NBT matching on.

**Comment by Atricos** [comment]
Yeah, it's because of the color of its name. One possible workaround is that you could try to look at the Glod Crystal recipe, pin it to the left side, and drag it from there for NBT matching.
