### ISSUE TITLE
Mekanism upgrading QOL

### ISSUE THREAD

**Issue by NaminBeforeGamin** [Divine-Journey-2/main#400]
**Modpack version:**
2.5.0

**Describe the request:**
Mekanism tier installers. make basic tier installers require rf powder, enriched gum, steel casing, and some fluix. make the latter tier installers just have rf powder in place of where the machine in the recipe would be. 

Additionally, if possible(no clue if it is, cannot check), make it so we can use a specific item to upgrade mek cables. You guys disabled the easy upgrade feature with the various alloys but if you can make it so we can use an item that's exactly the same as the upgraded wire recipes(minus the wires themselves) for upgrading.

**Reasons why this should be added:**
It would provide a heavy boost to quality of life because I don't have to break a mek machine or wire anymore. My base is heavily built on mek cables and it'll be difficult to upgrade to ender io cables in the distant future.

**Describe alternatives you've considered:**
setting up automation would be different if this is added because it wouldn't require you to take down your entire automation setups to keep up with the demand of say energy or say ore processing.

**Additional context:**
Nothing else to add!

**Comment by WaitingIdly** [comment]
\> Mekanism tier installers
the upgrade costs from [tierX] to [tierY] vary significantly, meaning you would frequently be wasting materials to upgrade (same tier of fluid tanks are way cheaper than factories). Additionally, the cost for machines from none -> Basic requires 2 machines.
\> specific item to upgrade mek cables
not possible

you should not be using mekanism cables for long, as they can be quite laggy in large numbers.

**Comment by NaminBeforeGamin** [comment]
oh I see. my bad. I will make a different thing then and close this
