### ISSUE TITLE
ME Gas Storage Monitors and ME Gas Conversion Monitors uncraftable

### ISSUE THREAD

**Issue by hoi6789** [Divine-Journey-2/main#401]
**Modpack version:**
2.5.0

**Description:**
You can't craft ME Gas Storage Monitors or ME Gas Conversion Monitors because they need a ME Gas Level Emitter, which is disabled.

**Steps to reproduce:**
1. Enter a world
2. Click on the ME Gas Storage Monitor or ME Gas Conversion Monitor recipe
3. Realize that one of the ingredients is disabled
4. cry

**Expected behavior:**
All the ingredients should have recipes and not be disabled.

**Comment by Atricos** [comment]
Changed their recipes to take Basic Pressurized Tubes instead of a Gas Level Emitters in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373
