### ISSUE TITLE
Conduit recipe buff

### ISSUE THREAD

**Issue by NaminBeforeGamin** [Divine-Journey-2/main#402]
**Modpack version:**
2.5.0

**Describe the request:**
Pretty simple: make conduit binding a tiny bit cheaper. (make it give 3 or 4 binding instead of 2 per craft)

**Reasons why this should be changed:**
-as mentioned in a previous request, mek cables are laggy in large quantities so you need to switch to either flux ducts or conduits in early mid game (which is when you are setting up the framework of your base)
-there is no AE2 auto crafting or automated dark ingot for a long while; you usually want to use your dark ingots for the sheer amount of dark steel you need
-you still need binder in upgrading conduits, so it is still quite expensive 

**Describe alternatives you've considered:**
-Making an extremely early game wireless rf transfer
-buff flux ducts to the point where they are far better than any mek cable(as well as removing mek cables past advanced tier)

**Additional context:**
No additional context

**Comment by Atricos** [comment]
Binder Composite now crafts 4 at a time (up from 2) in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373

If you feel like this isn't enough, feel free to reopen the issue.
