### ISSUE TITLE
Ender IO Conduit Facades

### ISSUE THREAD

**Issue by CodedInMyHead** [Divine-Journey-2/main#403]
**Modpack version:**
any

**Describe the request:**
Change the conduit facades recipe to not take energized Dark Ingots :)

**Reasons why this should be changed:**
I believe that the Ender IO conduit facade recipe is too expensive costing 8 conduit binder to facade 1 wire since you need tons of them but making that much energized Dark Ingot for facading wires is too much.

**Describe alternatives you've considered:**
An alternative would be that 1 craft doesn't give you 4 facades but maybe 32 or 64 since they're purely cosmetic

**Additional context:**
-

**Comment by Atricos** [comment]
I can go up to 8 Facades per craft, but any more seems too much. That would mean each facade costs half an Energized Dark Ingot.

**Comment by Atricos** [comment]
Binder Composite now crafts 4 at a time (up from 2) in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373. This makes it so you get twice as many Conduits Facades from the same number of ingredients as in 2.5.0.

If you feel like this isn't enough, feel free to reopen the issue.
