### ISSUE TITLE
Modify automation help quest descs in ch15/22

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#406]
**Modpack version:**
2.5.0

**Describe the request:**
The quest descriptions for the Hellfire Forge, Alchemy Table, and Lightning Infusion Table should be modified.

The Alchemy Table can be done with renaming items as is currently shown in the Hellfire Forge quest. Alternatively, recipes that need a duplicate item can be given their own alchemy table, already supplying a stack of one of the items you need two of. (But this doesn't work well for expensive things like tablets, because a stack of clean runic plates isn't cheap). Alternatively, something similar to the Hellfire Forge setup in this post also works. I suggest placing both of these in the quest description, with the example using a recipe that takes multiple of a stackable item (the current one in the Hellfire Forge quest uses water buckets, which renaming is not necessary for).

The easiest way to automate the Hellfire Forge that I can find is with Integrated Dynamics. Set up an ME interface on blocking mode into a chest, connect an Item Interface to it, and set 4 Item Exporters onto the hellfire forge, then in "Export All items", set each to a distinct slot (0,1,2,3 respectively), quantity to 1 (so that items will be placed evenly between slots - this deals with the issue of Air Reagents having two of the same stackable), and add a Variable Card set to "true". To extract, use an item filter for completed craft components, or use an Item Importer to import from slot 5 (and something separate for buckets). This process should replace the current one on the quest.

The Lightning Infusion Table is mostly harder than these because you can't use renamed items, which makes the ID solution an easy one if the user doesn't want to use a timer. Also, please tell people to make a different machine for each recipe, it's just way too painful otherwise.

**Reasons why this should be added:**
The current descriptions are still fairly difficult to follow. Even after reading them, I found it difficult to figure out the intention of any of the current descriptions except the explanation of how to automatically rename items and use them.
These proposed descriptions go over some options that aren't too complicated to set up (while it uses ID, it doesn't use any actual logic). Instead of the current ones where I feel like if I tried to do them I'd just stop and use the ones here anyway.
ID does have a fairly high resource cost (which rewards creativity as that can make it cheaper), and using it in ch15 encourages the player to look more into it as it becomes useful for everything in Astral Sorcery.
For the Lightning Infusion Table one, I think it's just good to at least mention that this machine is hard to automate even knowing that the crafts take a fixed amount of time, and it should direct the player back to the blood magic quests as it's a similar problem.

**Describe alternatives you've considered:**
It's fine to expect people to figure it out for themselves, but in that case the current Hellfire Forge description is too detailed. Instead, I would change it to just some hints (How to make an inscriber name press, and that ID can insert into specific slot numbers, is all that's really needed in the ch15 quests).

**Additional context:**
I've been using a weirder setup than the one described here for the Hellfire Forge which is cheaper and still reliable, but as mentioned above, it's better for an easier to understand setup to be the one that is shown.

**Comment by King65868** [comment]
For my hellfire forge automation I just did the renaming, and then used ID to make sure that only 4 inputs were put in. I do see your point about putting in specific slots though, pretty smart.

**Comment by 1234abcdcba4321** [comment]
If something was already done about this issue before this point, I've now actually set up a lightning infusion table setup and I realized what I wrote in there wasn't quite accurate. So be careful and test the setup you describe yourself before adding it to the book, because I'm not 100% confident everything's right.

**Comment by Atricos** [comment]
The title also says Chapter 22. What needs to be modified there?
