### ISSUE TITLE
Unification of Underground Biomes ore types in JEI/Just Enough Ressources

### ISSUE THREAD

**Issue by Jolain** [Divine-Journey-2/main#407]
**Modpack version:**
2.5.0

**Describe the request:**
If at all possible, it would be great to be able to see the "overall" distribution of the overworld's ores instead of having them separated for each Underground Biomes variant of each ore. 

**Reasons why this should be added:**
Could help new players get a feel of the ore distribution in the pack, especially in the early game. It's borderline impossible to get the "true" ore distribution in the overworld because of the variants.

**Describe alternatives you've considered:**
It can be useful to see the concentration of ores in individual UB's if you need one particular ore, alternatively we can go check the config file to see the ore distribution.

**Additional context:**
Mostly for new players before automated resources, but a nice QoL.
[This is confusing.](https://i.imgur.com/ykoTpxO.png)

**Comment by Atricos** [comment]
I have updated the world-gen file in 2.6.0, thanks to Auti. I'm not saying it's perfect, but it's better. So please update and check it out.

**Comment by Jolain** [comment]
Did not see that the update was already released, updating now.

**Comment by Jolain** [comment]
Definitely better than it was! I'm fine with it as it is.
