### ISSUE TITLE
Mortum tower has botania runes as loot

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#410]
**Modpack version:**
2.6.0

**Description:**
Mortum tower has botania runes as loot, which are useless

**Screenshots:**
![image](https://user-images.githubusercontent.com/8618678/135771661-ab8bdcf7-efb3-4e6b-9694-ba6f351fee0c.png)

**Comment by Atricos** [comment]
Corrected the loot table, now it gives the ContentTweaker runes, and also changed Zinc Ingot to Sodium Ingot in the loot table in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165 (Mortum has to be regenerated for the existing loot to change though.)
