### ISSUE TITLE
Have stone torches but not getting achievement

### ISSUE THREAD

**Issue by EHawk3** [Divine-Journey-2/main#411]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.X.X

**Description:**

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Get the item ... / Go to ... / Open the ... / Place a ... / Break a ... / ...
3. ...
4. ... doesn't craft correctly. / Can't get the ... / ... can't be completed. / ...

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. These can also be attached to the "Description" or "Step to reproduce" sections. If you have no screenshots, this part can be removed.

**Additional context:**

**Comment by WaitingIdly** [comment]
Template issue, fill out with information
