### ISSUE TITLE
Useless mortum tower rewards

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#415]
**Modpack version:**
2.6.0.

**Describe the request:**
Adding to useless botania runes request, you also get zinc ingots which are not used for anything until singularities. They should be probably changed to sodium(all removed)

**Reasons why this should be changed:**
Cuz they are useless

**Describe alternatives you've considered:**
^

**Comment by Atricos** [comment]
I forgot to update the Mortum loot after I made several changes. I will fix this in the next update.

**Comment by Atricos** [comment]
Corrected the loot table, now it gives the ContentTweaker runes, and also changed Zinc Ingot to Sodium Ingot in the loot table in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165 (Mortum has to be regenerated for the existing loot to change though.)
