### ISSUE TITLE
Transparent Conduit Facades should craft 4 at a time

### ISSUE THREAD

**Issue by 40110** [Divine-Journey-2/main#417]
**Modpack version:**
2.6.0

**Description:**
Conduit Facades were buffed to give 4 items per recipe while Transparent Conduit Facades still give 1 per recipe

**Expected behavior:**
Expected both recipes to give 4 items

**Comment by Atricos** [comment]
Now they craft 4 at a time in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165
