### ISSUE TITLE
modpack server crashes due to an ender io recipe error

### ISSUE THREAD

**Issue by awesone959** [Divine-Journey-2/main#418]
hosting an apex server for the pack with my friends all of the server files i use seem to give me this error and the server wont start. any help would be apricated. 
![Screenshot 2021-10-05 040901](https://user-images.githubusercontent.com/91930026/135954062-dc64e438-592b-4fa2-8f17-a2db638103c0.png)

**Comment by WaitingIdly** [comment]
Please fill out the template when submitting an issue. 

The issue is likely that scripts are not being initialized, and so the ingot isnt being created.
