### ISSUE TITLE
Broken Capacitor Banks

### ISSUE THREAD

**Issue by Ahri0511** [Divine-Journey-2/main#429]
**Modpack version:**
2.6.0

**Description:**
i tried it in singleplayer and on our server and im not able to change anything on the capacitor bank regarding input and output and its not showing the input/output as well (Screenshot 1 will show what i mean) also you cant change the faceplate to the input/output screen you can only set it to the bar and thats not showing as well (shown on Screenshot 2) but they do charge

i removed the other steps because they're not needed in this case imo

**Screenshots:**
[https://gyazo.com/eb18dda3c992beb205da8cf6dcdc04d9](Screenshot 1)
[https://gyazo.com/c2d6ba70c70a8e8cad02f2027988fc6a](Screenshot 2)

**Comment by Ahri0511** [comment]
only setting input/output/disabled works nothing else sadly

**Comment by Atricos** [comment]
I tried it in Singleplayer and it worked, so please include a detailed step by step walkthrough of how your acquired your Capacitor Banks, how you placed them down, what configurations you changed.

**Comment by Ahri0511** [comment]
i crafted them from scrap and tried getting them in creative and simply placed them down i tried it in Singleplayer and Multiplayer on version 2.6.0 and 2.7.0 (only SP for 2.7.0 since pg isn't updated yet) and each time i get the same broken capacitors i cant change the max in/output and it's visuals aren't working either

**Comment by Ahri0511** [comment]
only optifine and laggoggles

**Comment by Ahri0511** [comment]
i will try that i need to update my modpack first and if that's the cause thats bad for me because i need laggoggles since im staff on pg xD
