### ISSUE TITLE
Destabilized clathrate in compacting Drawer

### ISSUE THREAD

**Issue by Krollbotid** [Divine-Journey-2/main#430]
**Modpack version:**
2.6.0

**Description:**
Compacting drawer thinks that destabilized clathrate (Thermal Foundation) is crystallized redstone (Abyssal Craft)
**Steps to reproduce:**
1. Get into a world
2. Put destabilized clathrate into a compacting drawer.
3. Compacting drawer let you get crystallized redstone chunks and fragments

**Expected behavior:**
Compacting drawer doesn't do step 3.

**Screenshots:**
![image](https://user-images.githubusercontent.com/37172495/136567000-53c7cce7-cb5a-4834-a7ec-79cdccca6a05.png)

**Comment by Atricos** [comment]
They happened to have exactly the same OreDictionary name, and by removing this name from the Destabilized Clathrate in 2.7.0, the issue has been fixed: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165
