### ISSUE TITLE
Bloodgem Dust is useless

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#431]
**Modpack version:**
2.6.0

**Description:**
There are no uses for Bloodgem Dust. Not even a smelting operation to get the Bloodgem back. The only use would be to use it to smelt in an Essentia Smeltery. Furthermore is the only way to get the Bloodgem Dust to grind down a gem and not the ore.

**Steps to reproduce:**
1. Look up uses for Bloodgem Dust

**Expected behavior:**
I would suggest just removing the item. You could also add recipes to smelt the dust back into gems and add recipes to get the dust out of ores. But this is unnecessary because when grinding down the ore you already get the gem itself.

**Additional context:**
To add to the Essentia subject, the amount of Potentia you get out of the dust is three times what you get from the gem itself. And you only get Potentia from either of them.

**Comment by Atricos** [comment]
Imp Summoning now takes Bloodgem Dust in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165 It's no longer useless, woohoo!
