### ISSUE TITLE
Enderium Base -> Enderium Recipes are different in Alloy Smelter and Induction Smelter

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#433]
**Modpack version:**
2.6.0

**Describe the request:**
Either: One Enderium Ingot also takes one Enderium Base and one Sand in the Alloy Smelter
Or: Two Enderium Ingots also take two Enderium Base and one Sand in the Induction Smelter

**Reasons why this should be changed:**
To make the two recipes consistent

**Describe alternatives you've considered:**
None, you could just leave it inconsistent

**Comment by Atricos** [comment]
Either way, one Enderium Base goes into one Enderium, you might just need a little bit more Sand in the Induction Smelter. Not an issue in my opinion.
