### ISSUE TITLE
Automatically crafted Clocks and Compasses can’t be put into induction smelter.

### ISSUE THREAD

**Issue by Lgmrszd** [Divine-Journey-2/main#434]
**Modpack version:**
2.6.0

**Description:**
#313 introduced similar issue. Now, compasses that are crafted using machines and were never held by player, cannot be inserted into Induction Smelter.

**Steps to reproduce:**
1. Set up a way to automate Compass crafting (I used Formulaic Assembler)
2. Pipe the result into Induction Smelter (I tried hopper, different kind of pipes, or just chest with Auto-Input enabled)

**Expected behavior:**
Compass can be inserted into Induction Smelter

**Screenshots:**
![hopper](https://user-images.githubusercontent.com/16291541/136663501-24ccabc4-8769-422d-965a-abccc68071b5.png)
![smelter](https://user-images.githubusercontent.com/16291541/136663535-cbf33587-46b4-4ee9-b58b-2845bd665217.png)
![setup](https://user-images.githubusercontent.com/16291541/136663553-54fb0a68-2ec7-4541-9df3-31b953f46857.png)

**Additional context:**
The problem is introduced here:
https://github.com/Divine-Journey-2/main/blob/8c43febee0cff1e3293526e8591a6b1cee11975d/scripts/ThermalExpansion.zs#L577

Possible fix is to either not remove original recipe (but it might only accept Vanilla Sand) or re-add recipe, using compass without any NBT data.
(Also, does Thermal machines support IIngredient in CraftTweaker scripts? Because then maybe it is possible to just use <ore:sand> as input, without using loop, but maybe this is intentional.)

**Comment by Atricos** [comment]
Re-added the non-NBT recipe for Clocks and Compasses in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165
