### ISSUE TITLE
Adjust Mob Imprisonment Tool Recipe

### ISSUE THREAD

**Issue by Command-Crafter** [Divine-Journey-2/main#435]
**Modpack version:**
2.5.0

**Describe the request:**
The Mob Imprisonment Tool is gated behind chapter 25. I think it should be moved to chapter 12 or 13.

**Reasons why this should be changed:**
The Mob Duplicator is available in chapter 12, but it is useless without a Mob Imprisonment Tool. So if you craft the machine without knowing that, you have a block you cannot use until 13 chapters later. 

**Describe alternatives you've considered:**
Moving the Mob Duplicator to chapter 25 or adding a short text that explains that the machine is useless until chapter 25

**Additional context:**
I'm still on 2.5.0, but the changelog for 2.6.0 makes no mention of the Mob Imprisonment tool or the mob duplicator

**Comment by Atricos** [comment]
I'm not moving the Mob Imprisonment Tool earlier, because there is no blacklist for what it can pick up. That means bosses, Arcana traders, etc. are transferable, which I do not want. I can add the short text that you've recommended though.
