### ISSUE TITLE
Supernatural Velocity quest typos

### ISSUE THREAD

**Issue by Xynariz** [Divine-Journey-2/main#439]
**Location:**
Questbook, chapter 7 (Exploration II), quest "SPEEEEEEEEEEEEEEEED!!!"  There are two typos.

**Exact fix:**
Typo 1: "Supernatural Velocity wings" should be "Supernatural Velocity"
Typo 2: The quest should require 8 Supernatural Velocity (instead of the current 6).

**Reasoning:**
Typo 1: There is no item called "Supernatural Velocity wing" - the item is called "Supernatural Velocity".
Typo 2: Making a Lightning Velocity Block requires 8 supernatural velocity.

**Comment by Atricos** [comment]
1) I clearly capitalize every item name, and the item required is shown on the right, so I don't think it's possible to get confused on what you need by adding "wings" for "flavour".
2) But I can correct the amount you need.

**Comment by Atricos** [comment]
Corrected the amount needed in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165
