### ISSUE TITLE
Rune of earth fusion crafting

### ISSUE THREAD

**Issue by dedikkepapzak** [Divine-Journey-2/main#440]
**Modpack version:**
2.6.0

**Description:**
When craftin the biothaumic mind a rune of earth is used. However you can't use the rune of earth if its from botania. It has to be the rune of earth from contenttweaker. I don't think/know of a way to swap the mod it is from, but without the contenttweaker variant the crafting won't even start

**Steps to reproduce:**
Set up a thaumic fusion altar with 4 pedestals / place 2 brains, 1 complex arcane mechasnism and a rune of earth on the pedestals / place a clockwork mind on the pedestal in the middle / place down warden jars with the correct essentia (cognitio, machina, herba, bestia) / try to start the fusion crafting with the caster's guantlet

**Comment by Atricos** [comment]
You have to use ContentTweaker runes for everything. How did you get the Botania Earth Rune? Was it from Mortum? Because I fixed the Mortum loot table in 2.7.0.

**Comment by dedikkepapzak** [comment]
i think i got it from mortum yes. Since im still in 2.6 that would probally explain why
