### ISSUE TITLE
Remove Research papers from galacticraft quests

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#442]
**Modpack version:**
2.7.0

**Describe the request:**
Remove research papers from galacticraft quests

**Reasons why this should be changed:**
If you research a planet before getting to the quest that wants the corresponding research paper, you are stuck if you cannot use commands and aren't playing with other people.

**Describe alternatives you've considered:**
Just telling people that they will need the research papers, which is basically already done in the quests "Twolescope" and "TO THE MOON!"

**Additional context:**
Venus research paper in quest 377 "Expanding your reach",
Mars research paper in quest 403 "To the red planet! Are there aliens...?"
Moon research paper in quest 395 "Twolescope"

**Comment by Atricos** [comment]
Research Papers are no longer required for the quests in 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170
