### ISSUE TITLE
Increase the Speed of the Ultimate Compressor

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#443]
**Modpack version:**

2.7.0 

**Describe the request:**

The Ultimate Compressor in its current state does not seem to work as intended. The 12 advanced compressors needed for the machine, when run in parallel, produce 5.5~ as fast as the Ultimate Compressor itself.

**Reasons why this should be changed:**

There is currently no reason to make this Modular Machine.

**Describe alternatives you've considered:**

- Lower the cost in terms of machines. This is not ideal as you're gonna want them anyways.
- Have it able to run multiple recipes at once. This could make it competitive though Im not sure if feasible.

**Additional context:**

The quest description seems to imply the machine can run multiple recipes at once (the second alternative) but this just isn't true. I tested automating both setups (12 vs 1) and 12 was both  easy and produced more.

![image](https://user-images.githubusercontent.com/77116048/136721083-2ce178c4-4a55-48c5-83c5-b917231a2cc3.png)

12:
![2021-10-10_18 12 25](https://user-images.githubusercontent.com/77116048/136721101-69004de9-a44e-4a27-ad03-07cac8327040.png)

1:
![2021-10-10_18 12 26](https://user-images.githubusercontent.com/77116048/136721106-a23bdf04-1155-4473-bd1e-9ee671ac2581.png)

**Comment by Atricos** [comment]
The Ultimate Compressor is now 10x faster and crafts items 4 at a time in 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170 So overall it should craft items 40x faster.
