### ISSUE TITLE
Add conversion between dense and non-dense ME cables via crafting recipes

### ISSUE THREAD

**Issue by Pajama-Day** [Divine-Journey-2/main#444]
**Modpack version:**
2.7.0

**Describe the request:**
Simply add crafting recipes to turn ME dense cables into ME cables and vice versa.

**Reasons why this should be changed:**
Crafting cables is a hassle when there isn't a way to convert between dense and non-dense at all, and being locked in to your decision (either dense or non-dense) after making smart cables is even more so. The recipes would be:

1x ME Dense Covered Cable - Fluix = 4x ME Covered Cable - Fluix
1x ME Dense Smart Cable - Fluix = 4x ME Smart Cable - Fluix
4x ME Smart Cable - Fluix = 1x ME Dense Smart Cable

**Describe alternatives you've considered:**
Add another (non-crafting table) method of converting between dense and non-dense cables

**Additional context:**
N/A

**Comment by KleinGrrmpf** [comment]
Couldn't you just make the dense smart cable recipe to just take four normal smart cables? This way you could just convert between the two easily.

And for the sake of consistency, would you add the recipe for the conduits as well? So one dense conduit -> four normal conduits?
