### ISSUE TITLE
Remove Rutile Ore from Excavator

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#447]
**Modpack version:**
2.7.0

**Describe the request:**

Remove Rutile Ore from the Bauxite excavator vein

**Reasons why this should be changed:**

This is a progression skip, skipping mining in the Asteroids to get titanium.

**Describe alternatives you've considered:**

Probably a good idea to replace it with something else more useful for a not 100% aluminum vein.

**Additional context:**

Titanium is currently only useful once in Galacticraft, and you need to do the dungeon anyways, so it's not a Huge deal.

**Comment by Atricos** [comment]
Removed Rutile Ore in 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170 Now there is only an "Aluminum deposit" instead of the Bauxite one.
