### ISSUE TITLE
Dark Bow Not Craftable

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#449]
**Modpack version:**
2.7.0

**Description:**

Dark Bow is not craftable due to Nutritious Stick having no recipe

**Steps to reproduce:**

1. Open game
2. See no recipe for Nutritious stick

**Expected behavior:**

Nutritious stick being obtainable

**Screenshots:**
![image](https://user-images.githubusercontent.com/77116048/136877118-6a401fee-f06c-4fed-b4e6-9ef2bb626c58.png)

**Additional context:**

![image](https://user-images.githubusercontent.com/77116048/136877139-cfc6b46e-8b42-4823-af9e-bc5a1d6a043b.png)

**Comment by Atricos** [comment]
Made Nutritious Sticks craftable using 500 mB of Nutrient Distillation + a Stick in the Fluid Transposer in 2.8.0, which fixes the issue: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170
