### ISSUE TITLE
Crystaltine Ingots do not need the 9x9 Crafting Table

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#452]
**Location:**
Quest 411 "Crystal Eyes" description

![grafik](https://user-images.githubusercontent.com/57828910/136979677-ccc177c5-dcb3-437f-82c5-9f8a0d2bf8b3.png)
![grafik](https://user-images.githubusercontent.com/57828910/136979706-0330af00-aee9-4758-84ff-fc3de5ca917a.png)

**Exact fix:**
Gating the quest behind quest 418 "IMA FIRIN' MAH LAZER" instead of the Ultimate Crafting Table Quest [443 "The PenULTIMATE Crafting Table"] and rewriting the description so that it doesn't mention the table (The quest "Auto Your Mato" does require the table, so maybe questgate that behind the ultimate crafting table quest instead))

**Comment by Atricos** [comment]
The quest now only requires the Laser Focus in 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170
