### ISSUE TITLE
Superium Infusion Crystal not craftable

### ISSUE THREAD

**Issue by Katsuro27** [Divine-Journey-2/main#453]
**Modpack version:**
2.7.0

**Description:**
You cant craft the Superium Infusion Crystal in the Iridescent Altar from Astral Sorcery. The crafting process keeps going forever.

**Steps to reproduce:**
1. Setup an Iridescent Altar from Astral Sorcery.
2. Put in the crafting recipe for a Superium Infusion Crystal.
3. Start the crafting with resonating wand:
4. The crafting wont stop

**Expected behavior:**
The Superium Infusion Crystal should pop out on top of the Altar after a few seconds

**Additional context:**
It seems like the required amount of starlight (8000 which is the max capacity of the altar) is too much to use. Lowering the required starlight a tiny bit (i made it to 7800) didnt change fix this either... The highest value I tested and worked was 7500.

**Comment by Atricos** [comment]
Changed the required Starlight from 8000 to 4000 in 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170
