### ISSUE TITLE
Increase LightningCraft and Fusion Reactor Speed

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#454]
**Modpack version:**
2.7.0

**Describe the request:**

Fusion Reactor:

Make the Fusion Reactor faster by having it consume more RF/t.

LightningCraft:

Increase the Infusion table speed from 30/15 to 15/5 seconds (or similar)

**Reasons why this should be changed:**

Fusion Reactor:

The fusion reactor is too slow. It takes 1200 ticks currently (60 seconds) and with any lag that only goes up. Given that you need hundreds of crafts and you cannot have 100% uptime, this is just a huge waiting game and not really what this pack is. I'd suggest bringing it down to 10 seconds most

LightningCraft:

The infusion table currently takes 30 or 15 seconds for each craft, and the nested crafting in these along with insane amount of skyfather ingots required for progression is another waiting game.

**Describe alternatives you've considered:**

- Creating Mystic and Skyfather seeds, and moving up Uranium seeds earlier. (this would be an A+ Divine maneuver)
- Lowering Resource Costs

**Additional context:**

![image](https://user-images.githubusercontent.com/77116048/137052448-63a0cdb1-0b17-4054-b1ce-c05627f53c68.png)

Just look at this Uranium recipe, slowed down by the coolant unit:
![image](https://user-images.githubusercontent.com/77116048/137052470-9f3d016a-a1f0-4eb9-a0f0-b4180842aefa.png)

**Comment by Bosfik** [comment]
agree

**Comment by Atricos** [comment]
LightningCraft doesn't have a config to increase its machines' speeds, so I instead increased material yields for Skyfather Ingots, Mystic Ingots, Divine Underpowder and also Mystical Iron Ingots.

The Weak Fusion Plant is now 40x faster but consumes 40x more RF/tick.

Changelog of 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170

If this still isn't enough, feel free to make a new issue or reopen this one.
