### ISSUE TITLE
Add better prudentium recipe

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#457]
**Modpack version:**
2.6.0

**Describe the request:**
Add a compressed inferium infusion crystal (made with 9 full durability ones which get consumed in the craft) and a recipe to use that to convert 4 inferium blocks into a prudentium block.

**Reasons why this should be added:**
Due to #455, the best way to compress inferium into prudentium is to use a crafting terminal and just shiftclick a bunch of times. However, you need to do this a *lot* due to how much supremium you need to create every tier 5 seed (and the tier 6 ones are four times worse, of course), and shiftclicking in crafting terminals tends to cause short-lived server lag. (This is less of an issue for Tier 6 since you gain access to the Master Infusion Crystal soon after, which makes this issue a strong incentive to make the crystal.)

**Describe alternatives you've considered:**
Fixing #455 would make this unnecessary, but I think it would still be nice to have regardless.
There could be an "unbreakable infusion stone" craftable around the same time as the superium infusion crystal that can only infuse inferium->prudentium but without durability, but see the note below.

**Additional context:**
Heavily related to #455.
Unlike the fix suggestions 1/3 there (and probably also 2, unless made so you can't enchant with mending), this doesn't change balance at all; the player is still expected to set up their first automation interface on the ender crafter so that they can produce infusion crystals without needing to babysit the machine. The only difference this makes is that it allows for crafting enough essence without it taking too much hassle.

**Comment by Atricos** [comment]
This part of #455 is fixed, the Mystical Agriculture Tiered Crystals are now unbreakable in 2.8.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170), which fixes this issue.
