### ISSUE TITLE
Allow the C&B Bit Bag to be stored inside the Simply Backpacks backpacks

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#459]
**Modpack version:**
2.7.0

**Describe the request:**
Allow the C&B Bit Bag to be stored inside the Simply Backpacks backpacks.

**Reasons why this should be added:**
In my opinion the Bit Bag is just as much of a tool as the Chisel itself. Without the bag you can't really chisel blocks because you'd have you inventory spammed with bits. It is also not really the system of a bag inside a bag because the Bit Bag is not really storing anything. It can't even store eight whole blocks. So it would not be worth it to cut down blocks into bits just to store six more blocks.

**Comment by WaitingIdly** [comment]
Items with nested NBT should never be stored in each other, as it can cause player corruption.
