### ISSUE TITLE
Lead ore smelting in redstone furnace to pulverized lead

### ISSUE THREAD

**Issue by Denecon** [Divine-Journey-2/main#468]
**Modpack version:**
2.7.0

**Description:**
Lead ore smelting to pulverized lead

**Steps to reproduce:**
1. Put Lead ore in redstone furnace.
2. smelts into pulverized lead not lead ingots nor does the flux anodizer augment.
3. doesn't smelt correctly. 

**Expected behavior:**
Smelt lead ore into lead ingot

**Screenshots:**
![Capture](https://user-images.githubusercontent.com/58856884/137590489-002a8671-ee7c-4a6d-a6c1-2cdbfc296da4.PNG)

**Comment by Atricos** [comment]
Now it correctly produces Lead Ingots in 2.8.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3493170
