### ISSUE TITLE
New, quicker, recipes for rods 

### ISSUE THREAD

**Issue by NaminBeforeGamin** [Divine-Journey-2/main#470]
**Modpack version:**
2.8.0

**Describe the request:**
make it so pulverizers and crushers crush down plates into rods.  

**Reasons why this should be added:**
The metal mold presses are bulky and incredibly slow. It is kinda ridiculous that you have to use it for like the whole pack. Rods can be used for steel casing and building material as well. 

**Describe alternatives you've considered:**
If this does not work, maybe add an inscriber press for rods and wires. Or make an induction smelter recipe for the rods.

**Comment by King65868** [comment]
You can craft rods by hand which is perfectly reasonable once you start getting good resource generation, I think it’s perfectly fine

**Comment by Atricos** [comment]
You can just... craft any rod with 2 ingots. Once you have a Quarry or Mystical Agriculture, there is no reason to save the extra Ingot for each of them.
