### ISSUE TITLE
Imp summoning wrong

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#471]
**Modpack version:**
2.7

**Description:**
Imps are summoned with blood gems, not blood gems dust

**Steps to reproduce:**
Try it

**Expected behavior:**
Either JEI displays the gem or the recipe takes the dust

**Additional context:**

![](https://user-images.githubusercontent.com/77116048/136877139-cfc6b46e-8b42-4823-af9e-bc5a1d6a043b.png)

**Comment by WaitingIdly** [comment]
Imps are summoned with blood gem dust as of 2.7.0
