### ISSUE TITLE
Quest reset issue

### ISSUE THREAD

**Issue by DuarDragu** [Divine-Journey-2/main#472]
Every time I open my game the qust reset, it started a few days ago and I dont know how to fix it
![foto para arrumar](https://user-images.githubusercontent.com/92649769/137600982-5515e7cb-33f6-47d4-8286-dd9888c39ec1.png)
In this world I had already completed the 1 and 2 quest group, so every time that I get back to mu world everything is back to the start

**Comment by WaitingIdly** [comment]
Please fill out the bug report template when submitting issues. This does not have enough data to attempt to replicate or solve.

**Comment by WaitingIdly** [comment]
Could not replicate, no response.
