### ISSUE TITLE
Alchemy tables are too slow

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#476]
**Modpack version:**
2.8.0

**Describe the request:**
Alchemy Tables from blood magic run too slowly for how many items you need from them.
I don't know how configurable they are, but instead of changing their running speed (which still has the annoying part of item logistics) I suggest just adding a modular machine for it (which can take liquid life essence if needed, though by this point generating LP should be so cheap that that step really shouldn't matter), craftable at some point before you need awakened cores.

**Reasons why this should be changed:**
There are several items that need large amounts of blood magic cores. While the reagents aren't too much of an issue, alchemy tables are chained crafts, and so you quickly start needing to set up a table for each item. (And it still takes hours to make the Tenebrae if you do give each item its own table, so you start wanting to set up multiple.)
Additionally, actually charging a blood orb for this fast enough requires stuff like setting up an altar with speed runes as otherwise you run out of LP and the crafts just almost completely stall. This is fine, though I find it annoying as blood altars are hard to decorate well.

**Describe alternatives you've considered:**
- Lower the amount of cores you need in recipes.
- Add some lategame cheaper way to obtain some of the items from alchemy tables. This can be as simple as giving concentrated catalysts (and *only* those) an EMC value, for instance.

**Additional context:**
The specific item that you need a lot of is the Offensive Core and Defensive Core in Cracked Runic Plates (4 per rainbow tablet), and the Dark Core in Corrupted Light Ingots (1 per draconic core).

**Comment by Atricos** [comment]
All Alchemy Table recipes were sped up a LOT in 2.10.0.
