### ISSUE TITLE
Refined Obsidian not using the correct amount of pulverized obsidian

### ISSUE THREAD

**Issue by itsWeezing** [Divine-Journey-2/main#485]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.8

**Description:**
When attempting to auto-craft refined obsidian via AE2, the system either does not supply enough pulverized obsidian, or the machine is using more than 1 per craft. I cannot tell which. 

**Steps to reproduce:**
1. Order 10 refined obsidian via crafting terminal
2. Move to metallurgic infuser to check progress
3. 10 diamond dust is inserted, but less than 10 obsidian dust is inserted (it varies between 1-2 less than requested in the craft)

**Expected behavior:**
In this specific case 10 refined obsidian should be crafted

**Screenshots:**
![image](https://user-images.githubusercontent.com/92771014/137838995-210b37a1-9212-41d5-a04c-a01b1811257e.png)
The AE2 pattern used for this craft

![image](https://user-images.githubusercontent.com/92771014/137839213-8d77f620-ab68-472c-b8f6-e997ae5d2f93.png)
Requesting 10 refined obsidian to be crafted

![image](https://user-images.githubusercontent.com/92771014/137839237-2b378329-c6f8-4448-8a54-d5b5c209ef5b.png)
Crafting plan

![image](https://user-images.githubusercontent.com/92771014/137839901-01eb8491-4832-41a5-a47b-fd47ec3edb83.png)
Diamond left in the infuser after craft

![image](https://user-images.githubusercontent.com/92771014/137839964-2342e5dc-a9ff-45dc-9644-dd46f29e60d3.png)
Crafting CPU showing 2 missing refined obsidian, meaning its still missing a diamond dust as well

![image](https://user-images.githubusercontent.com/92771014/137839583-9df4ce4f-9f0d-414e-9fd8-0cda4f6ce4ef.png)
If I don't have items exporting as its crafting

**Additional context:**
Does not happen with less than 10. When requesting more than 10 the material variance is greater
If I do not have the refined obsidian automatically being pulled from the machine as it is crafting it seems to make the correct amount. But if I am using a conduit/itemduct to pull the finished item out it does not make the correct amount. The last screenshot above shows this interaction

**Comment by WaitingIdly** [comment]
cant reproduce - this is likely related to an error in your specific setup, likely items not being properly routed. if you can provide more information to dispel this assumption, please do so.

**Comment by itsWeezing** [comment]
> cant reproduce - this is likely related to an error in your specific setup, likely items not being properly routed. if you can provide more information to dispel this assumption, please do so.

I think I solved it a few days later but unfortunately the server went dark shortly after so I sadly cannot demonstrate how I resolved. Appreciate the reply!
