### ISSUE TITLE
Pulsating Iron should be crafttable in the Arc Furnance

### ISSUE THREAD

**Issue by 00Buster** [Divine-Journey-2/main#494]
2.6.0

A clear and concise description of what the request is.
I think it should be possible to craft Pulsating Iron in the Arc Furnance because you can craft energetic alloy and vibrant alloy in it too.

**Reasons why this should be added:**
It would just make more sens

**Comment by Atricos** [comment]
As of 2.13.0, it is now craftable in the Arc Furnace.
