### ISSUE TITLE
Starmetal dimensions are useless

### ISSUE THREAD

**Issue by 1234abcdcba4321** [Divine-Journey-2/main#500]
Hi your templates are bad but this isn't really a bug, so balance request

**Modpack version:**
2.8.0

**Describe the request:**
Quest 651 "Crafting chains? Pwah, dimensions!" tells the player to make a starmetal dimension, but there's already seeds that produce far more starmetal than you would ever need. Instead, the quest could require Blutonium, a resource that you probably need more of. (Alternative: liquid starlight. But you can't really use that for a quest.)

**Reasons why this should be changed:**
Seriously, did you just forget about the seeds?

**Describe alternatives you've considered:**
Skyfather is useful if you want to build a very large reactor. Or if you don't have blutonium.
Life essence is pretty useful too, but you already have access to it in high enough quantities it's not as important.

**Additional context:**
Blutonium lets you skip the lightningcraft crafting for the large amount of galactic ingots you need.
Liquid starlight makes it so you don't need to make a ton of lightwells to support the large amount of galactic ingots you need.

**Comment by Atricos** [comment]
Removed their quest in 2.11.0.
