### ISSUE TITLE
Update Extra CPUs and ExtraCells2

### ISSUE THREAD

**Issue by Thomas2566** [Divine-Journey-2/main#505]
First check if your request has been submitted before. If a similar request already exists, please don't submit, instead comment on that request. Note that new mods are likely NOT going to be added to the modpack. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your request has been added. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.X.X

**Describe the request:**
Remove the old version of ExtraCells with an updated Fork like AE Additions or ExtraCells Fork by Sam 

**Reasons why this should be added:**
Upon request of Atricos I am creating a feature request to update ExtraCPUs to the newest version. Before the latest update of ExtraCPUs it was impossible to use a forked version of ExtraCells due to dependence issues. The author was updated the mod to allow the forks which have added benefits including FPS performance issues when using gas emitters and fixed the duplication bug. 

**Describe alternatives you've considered:**

**Additional context:**
I cannot speak to which is better but here are the known forks available on Curseforge: 

https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork ~ AE Additions 
 

https://www.curseforge.com/minecraft/mc-mods/extra-cells-2-samlam140330s-fork - Sam's Fork

**Comment by Atricos** [comment]
Updated both of the mods in 2.10.0 and 2.11.0, with the new versions fixing most of the issues.
