### ISSUE TITLE
Crafting the transmutation tablet doesn't use up the input Philosopher's Stone

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#509]
**Modpack version:**
2.8.0

**Steps to reproduce:**
1. Craft a transmutation tablet
2. The philosopher's stone will stay in the input slot

**Expected behavior:**
For the Philosopher's stone to be used up or for the warning to be removed

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/57828910/138549858-5f9726a5-f62b-481a-97ec-38153732cfbc.png)

**Comment by Atricos** [comment]
I removed the tooltip, so no everything works as expected.
