### ISSUE TITLE
nether quartz ->nether quartz dust uses sag-mill grind ball durability

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#519]
**Modpack version:**
2.8.0

**Description:**
Despite not giving any benifit, the quartz recipe uses sag-mill grinding ball durability.
**Steps to reproduce:**
1. obtain a sag mill
2. insert a grinding ball (such as energized alloy)
3. pulverize nether quartz 
4. Watch as the ball gets used
**Expected behavior:**
I expect it to work like recipes such as the grains of pieziality, which do not use sag mill durability when crafted

**Comment by Atricos** [comment]
This is intended.
![image](https://user-images.githubusercontent.com/24854267/158798716-139eb781-93bd-4f9e-be8e-1e2a2edc0203.png)
