### ISSUE TITLE
Enable cross-tier connections for EnderIO energy conduits

### ISSUE THREAD

**Issue by VeeArr** [Divine-Journey-2/main#528]
**Modpack version:**
2.8.0

**Describe the request:**
In `enderioconduits.cfg`, set `B:canDifferentTiersConnect` to `true` to allow different types of EnderIO energy conduits to connect to each other.

**Reasons why this should be changed:**
With this setting set to `false` (the default), different tiers of EnderIO energy conduits do not connect to each other. This means that if you want to upgrade some of your energy conduits to another tier, you need to either replace the whole network, or put something like a capacitor bank or energy cube in between any segments using different tiers to provide the connection.

Due to the point in progression where using energy conduits becomes viable, having to do this is just tedious rather than actually being any kind of strain on resources (as the resources needed to make a cube to serve as a junction are less advanced than the resources used in the conduit itself), so it would make more sense and be more convenient to simply permit the different tiers of conduit to connect without an intermediary.

**Comment by Atricos** [comment]
Enabled in 2.13.0.
