### ISSUE TITLE
Add the BetterP2P mod

### ISSUE THREAD

**Issue by alperydrug** [Divine-Journey-2/main#530]
https://www.curseforge.com/minecraft/mc-mods/betterp2p 
its new ae2 addon and so amazing mod. i think this must be in dj2 next update

**Comment by Atricos** [comment]
I am considering this, but I'd like it to be further tested. Mods with such few downloads tend to still have a ton of bugs lurking.

**Comment by Atricos** [comment]
Added in 2.13.0.
