### ISSUE TITLE
Make the Pereskia Bulb processable in the IE Squeezer

### ISSUE THREAD

**Issue by Nocallia** [Divine-Journey-2/main#535]
**Modpack version:**
2.8.0

**Describe the request:**
All roots plants are able to be processed in the industrial squeezer and fermenter into plant oil and ethaline respectively. However, there is an exception in the Pereskia Bulb. The Pereskia itself is able to be put in the fermenter, but the Bulb (which can be seen as the seed of the plant) cannot be used in any of the IE machines.

**Reasons why this should be added:**
The addition of allowing the bulb to be squeezed into plant oil will allow parity with all other Roots crops, which have their seeds processed in the squeezer and products in the fermenter.

**Describe alternatives you've considered:**
While making the bulb usable as input in the IE machines, adding it wouldn't make a huge impact in progression. The only reason for this is to allow for parity between other Roots crops.

**Comment by Atricos** [comment]
As of 2.13.0, Pereskia Bulbs can now be squeezed.
