### ISSUE TITLE
Pig Spawners

### ISSUE THREAD

**Issue by ArethaCairn** [Divine-Journey-2/main#54]
So far the two structures I've come across in world gen have generated with Pig Spawners instead of whatever spawner might have been intended for the structure.

![image](https://user-images.githubusercontent.com/87624854/128601494-fe7364a0-6906-411c-a041-4333e4a4f0e8.png)
This is one of them, 

![image](https://user-images.githubusercontent.com/87624854/128601539-7079de94-051e-476c-8632-a2c2daff1f14.png)
This is the other one.

**Comment by WaitingIdly** [comment]
As nobody has created an issue remarking on this, and it appears to be resolved, this is being closed. Please reopen if any more evidence is found.
