### ISSUE TITLE
Erebus Cabbage not able to be harvested without breaking

### ISSUE THREAD

**Issue by HQManiac** [Divine-Journey-2/main#540]
**Modpack version:**
2.8.0

**Description:**
When growing Erebus Cabbage, attempting to harvest it when fully grown will only give seeds and not the desired item (Cabbage). This occurs when using Roots harvest spell and when right-clicking on the plant. Breaking the plant does drop the cabbage, but that is very inconvenient as you then have to manually replant it.

**Steps to reproduce:**
1. Open game, enter a world
2. Obtain Erebus Cabbage seeds, and fully grow.
3. Right Click the plant; receive only seeds.
4. Repeat above, but break instead of click; obtain cabbage.

**Expected behavior:**
The plant would drop cabbage, or cabbage and some seeds while auto-replanting itself.

**Comment by Atricos** [comment]
This is a mod behaviour, I can't change this with external tools. If you reallllly want to, you *can* report this to the Erebus mod authors, but seeing as you only need a few pieces of Cabbage, I don't see this as a big deal.
