### ISSUE TITLE
Change egg stack size to 64

### ISSUE THREAD

**Issue by Xynariz** [Divine-Journey-2/main#543]
**Modpack version:**
2.8.0

**Describe the request:**
Many items with a stack size of 16 have been changed to 64 (e.g. ender pearls, snowballs, and as of 2.9.0, Coralium Gem clusters).  This request is to do the same thing to the vanilla egg, which also stacks to 16.  

**Reasons why this should be added:**
This change would not only be in line with other stack size changes, but it would also be helpful in the early-to-mid game.  Eggs are a viable source of "glue" in many of the required EnderIO dyes.  During that stage of the game where a player has access to many of the EnderIO frames, but has not yet set up auto-crafting, having a stack size of 16 for eggs increases the amount of time it takes to bulk-craft the respective dyes.

Additionally, this would inherently quadruple the number of eggs that can be stored in storage drawers, which the pack explicitly encourages for early-game use.

**Describe alternatives you've considered:**
EIO dyes could be scaled to require fewer eggs, so that a stack of eggs can produce a stack of dyes.  Similar changes could be made to other recipes that involve eggs (e.g. fried egg).

**Additional context:**
* I am on 2.8.0, not 2.9.0, but I did not see any reference to egg stack size in the 2.9.0 release notes.
* I don't know if the modpack intends to explicitly encourage "bulk-crafting", but it is something consistently suggested on the Discord as a viable method of early-game production of items (specifically pre-AE autocrafting).  I personally have found the egg stack sizes to be particularly annoying when bulk-crafting dyes, but perhaps this is just a problem in my personal play style.

**Comment by avykrm** [comment]
In addition to that, 
If possible please add same feature for Soul Vials too.
Currently there stack size is 16 too.

**Comment by luciscout** [comment]
Also increase The Ultimate Singularity stack size to 64 because otherwise the craft you need it for takes 4x as long as necessary
