### ISSUE TITLE
quest rewards can be used to bypass vethea

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#544]
**Modpack version:**
2.9.0

**Description:**
quest rewards (such as the ender chest quest) can be used to gain items in vethea.

**Steps to reproduce:**
1. Complete a quest, such as the ender chest quest in CH. 13
2. enter the vethea from bewitchment.
3. claim the reward eroneously.

**Comment by KleinGrrmpf** [comment]
Holy crap, this is smart! I don't want this to be fixed ^^

**Comment by Ringedtech203** [comment]
sounds like more of a big brain bonus than a bug

**Comment by KleinGrrmpf** [comment]
I like that description. Then let's not spread it around in case that not everybody follows the github feed channel.

**Comment by luciscout** [comment]
Atricos knew about this before the pack came out, and decided this was fine for “speedrunning”

**Comment by Atricos** [comment]
Exactly as @luciscout said, I don't think this is an issue. If people are aware of this, they can use this as a "speedrun strat". It also makes a second playthrough less painful. I'm not going to change this.
