### ISSUE TITLE
Immersive engineering excavator formation

### ISSUE THREAD

**Issue by andrewlinington** [Divine-Journey-2/main#549]
**Modpack version:**
2.7.0

**Description:**
When forming the excavator the steel blocks used to form the excavator are replaced with immersive engineering steel blocks. if an attempt is made to use a differing steel block that isn't the same block of steel as it the multiblock won't form so if I have a mix of the normal steel and immersive it will not form.

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Build the excavator as normal.
3. Remove one of the steel blocks on the mining wheel after the multiblock has been formed 
4. Replace the steel block with a new steel and attempt to rebuild the multiblock
5. Multiblock will fail to form due to conflicting types of steel.

**Expected behavior:**
The Multiblock should form regardless of differing steel blocks.

**Additional context:**

**Comment by scatter-dev** [comment]
This should be fixed, but for the benefit of anyone having this issue, you can just uncraft the IE steel into 9 ingots and remake the TE blocks.

**Comment by Lgmrszd** [comment]
This is probably duplicate of https://github.com/Divine-Journey-2/main/issues/438

This is how IE works, and there won't be any updates for it on 1.12.2. Either uncraft steel blocks to ingots or use chisel to convert between blocks.

**Comment by andrewlinington** [comment]
fair enough closing issue.
