### ISSUE TITLE
Emerald ore from laser drill only obtainable in mountain biomes

### ISSUE THREAD

**Issue by antrobot1234** [Divine-Journey-2/main#552]
**Modpack version:**
2.9.0

**Description:**
Emerald ore from laser drills can only be obtained in mountain biomes. This goes against the balance change in the modpack that spawns emerald ore everywhere, regardless of biome. This inconsistency should be fixed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/21179158/140657080-556bed16-dabc-4cf4-b231-853dc65e8d98.png)

**Comment by WaitingIdly** [comment]
click the arrow on the right side of the box
