### ISSUE TITLE
Add a quest for the Goddess' Pearl

### ISSUE THREAD

**Issue by 40110** [Divine-Journey-2/main#555]
**Modpack version:**
2.9.0

**Describe the request:**
Add a quest for the Goddess' Pearl

**Reasons why this should be added:**
The player might not be aware they can make this item by the time it becomes available (after fission multiblock in the Alchemistry chapter)

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Atricos** [comment]
Added a quest for it in the Alchemistry Chapter in 2.10.0.
