### ISSUE TITLE
[Recipe addition] Lightningcraft recipes to Combination Crafting

### ISSUE THREAD

**Issue by TheonlyTazz** [Divine-Journey-2/main#560]
**Modpack version:**
2.9

**Describe the request:**
Lightingcraft Infusion Table is Laggy as ...
Moving the recipes off that Table will reduce lag a whole lot

**Reasons why this should be added:**
While trying to automate 5 Infusion Tables my TPS went down from 20tps to 9tps. Seeing how some items are needed VERY often, it would mean i would have to live with 9tps till the end of the pack?

**Describe alternatives you've considered:**
I created a custom Zenscript with 4 of the main Infusion recipes added to the Combination crafting. They might need tweaking still (power consumption, time,maybe lower the output/increase the ingredients needed etc)

**Additional context:**

```
# Author TheonlyTazz

# Electrium Block
mods.extendedcrafting.CombinationCrafting.addRecipe(<lightningcraft:metal_block:0>, 100000, 5000, <minecraft:iron_block>, [<minecraft:gold_block>, <minecraft:diamond_block>]);

# Skyfather Ingot
mods.extendedcrafting.CombinationCrafting.addRecipe(<lightningcraft:ingot:1>, 100000, 5000, <divinerpg:skythern_chunk>, [<lightningcraft:stone_block:0>, <lightningcraft:stone_block:0>, <lightningcraft:stone_block:0>, <lightningcraft:stone_block:0>]);

# Mystic Ingot
mods.extendedcrafting.CombinationCrafting.addRecipe(<lightningcraft:ingot:2>, 100000, 5000, <lightningcraft:stone_block:3>, [<lightningcraft:material:11>, <lightningcraft:material:11>, <lightningcraft:material:13>, <lightningcraft:material:13>]);

# Empowered Underpower
mods.extendedcrafting.CombinationCrafting.addRecipe(<lightningcraft:material:13>, 100000, 5000, <lightningcraft:material:12>, [<lightningcraft:material:8>, <lightningcraft:dust>, <lightningcraft:material:8>, <lightningcraft:dust>]);

# Divine Underpower
mods.extendedcrafting.CombinationCrafting.addRecipe(<lightningcraft:material:14> * 8, 100000, 5000, <lightningcraft:material:13>, [<lightningcraft:dust:1>, <lightningcraft:dust:1>, <lightningcraft:dust:1>, <lightningcraft:dust:1>]);

```

**Comment by Paronity** [comment]
I like this idea. 

You could even make it so that you have to make the first one in lightning craft, which gives you some sort of item that can then be used to leverage the rest in CC. It might be neat to force people to use LightningCraft since it is a different sort of mod, and then it unlocks the recipes that don't eat the TPS like it's cake.

**Comment by TheonlyTazz** [comment]
> 
> 
> I like this idea.
> 
> You could even make it so that you have to make the first one in lightning craft, which gives you some sort of item that can then be used to leverage the rest in CC. It might be neat to force people to use LightningCraft since it is a different sort of mod, and then it unlocks the recipes that don't eat the TPS like it's cake.

yes, as said, this is only a rough idea and the recipes might need a tweak. maybe add 1 original item to the input aswell making it a "duping" recipe, this way you still need to make your first in the infusion table... and if you happen to use up all, you need to make 1 in the infusion table again

**Comment by 40110** [comment]
There could be a modular machine for lightning infusion recipes

**Comment by King65868** [comment]
Yes, I think that would be best

**Comment by WaitingIdly** [comment]
Resolved via the addition of the Lightningcraft Infusion Multiblock in #569
