### ISSUE TITLE
Can you dial back the amount of crap generated in the nether its way to congested and difficult to navigate.

### ISSUE THREAD

**Issue by rickspencer** [Divine-Journey-2/main#565]
**Modpack version:**
2.9.0

Loving the pack however I'm hating the nether. 
There is so much crap generated it's almost impossible to navigate.

Is it possible to dial back the amount of flora and fauna generation?

Cheers

**Comment by Atricos** [comment]
In 2.10.0, now only about 60% of the plants generate (in new chunks). If this still isn't enough, feel free to reopen the issue.
