### ISSUE TITLE
Chapter 2 No Trophy?

### ISSUE THREAD

**Issue by Buffbud96** [Divine-Journey-2/main#566]
**Modpack version:**
2.9.0

**Description:**
I finished chapter 1 and got a trophy, now i just finished chapter 2 and didn't get a trophy... Are all chapters supposed to give trophies?

**Steps to reproduce:**
1. Load up world
2. Continue through chapter 2
3. Defeat Baykok and pick up his bow
4. Complete Quest and turn in quest/ collect rewards
5. Don't get a trophy?

**Expected behavior:**
I'm assuming after turning in the "BOSSFIGHT: Baykok" quest, you should get a trophy for completing chapter 2, but you dont.

**Screenshots:**
I don't have exact screenshots, but i will include links to videos depicting the issue.

**Additional context:**
1/2: https://www.twitch.tv/videos/1210675085
2/2: https://www.twitch.tv/videos/1210676417

**Comment by WaitingIdly** [comment]
Trophies are based on Advacements, and are not based on the questbook

**Comment by Buffbud96** [comment]
Thanks for the clarification! I guess it's just a coincidence that the first trophy is given after completing the first chapter... I just looked into it, and it seem the next one is after making a Roots Pyre, so if I just worked a little more, i'd have found it!
