### ISSUE TITLE
unusable ore spawning in 2.9.1

### ISSUE THREAD

**Issue by Thrensing** [Divine-Journey-2/main#572]
**Modpack version:**
2.9.1

**Description:**
After updating from 2.9.0 to 2.9.1, ore gen in my existing mines seems to have changed. There is a large abundance of copper ore from the Mystical World mod. The issue being that there is no use for this ore (not in ore dictionary?)

**Steps to reproduce:**

**Expected behavior:**
I would expect that any copper ore could be used just like any other ore.

**Screenshots:**
![image](https://user-images.githubusercontent.com/95107917/143660271-27675237-a46b-4cd5-9148-122891d832c4.png)
![image](https://user-images.githubusercontent.com/95107917/143660280-198291d9-000f-4600-89d3-491a36b4444a.png)

**Additional context:**

**Comment by Thrensing** [comment]
Seems like iridium is spawning in the overworld too, and many resources seem to be spawning at a way higher rate.

Order of operations this morning:
Download fresh install of 2.9.1 through MultiMC
Download fresh 2.9.1 server from Curse Forge.
Shut down existing 2.9.0 server.
Copy world folder over to 2.9.1 directory.
Relaunch server.

Flying around a fresh single player world in spectator on 2.9.1 and everything seems to be just fine.

It sounds like 2.9.1 was a relatively small update. idk how the ore gen could have got messed up that bad like that..

**Comment by WaitingIdly** [comment]
It wasnt anything to do with an update. If the internet connection is unstable (among other things), stuff may be downloaded corrupted. Its not common, but... sorry you got unlucky.
Whenever something like this happens, just redownload it. Its not something anything other than a redownload can fix.
