### ISSUE TITLE
Tinkers breaks Totemic

### ISSUE THREAD

**Issue by ItsBesater** [Divine-Journey-2/main#573]
**Modpack version:**
2.9.0

**Description:**
Tinkers break wind chimes

**Steps to reproduce:**
1. Open the game / Launch the Modpack / Load a world
2. Place a Wind chime anywhere / Use a tinker's tool with Luck on it / Break the wind chime with the tool

**Expected behavior:**
The wind chime duplicates

**Comment by siky112** [comment]
The wind chime shouldn't duplicate. If it could, that would be a problem.

**Comment by Atricos** [comment]
I tested this with a maxed out Luck Pickaxe, both veinmining and regular breaking, and the Chimes never duplicated.

Please provide more specific steps to reproduce. What pickaxe did you use? How much Luck was on it exactly? Where did you place the Chimes (on what block)?
