### ISSUE TITLE
Mystical World Quartz Ore is not processable in the Sag Mill

### ISSUE THREAD

**Issue by desht** [Divine-Journey-2/main#574]
**Modpack version:**
2.9.0

**Description:**
Mystical World Quartz Ore is not processable in the Sag Mill, but is processable in pretty much every other mod's crusher-type machine.

**Steps to reproduce:**
1. Try to put Mystical World Quartz Ore in a Sag Mill
2. Sag Mill won't accept it

**Expected behavior:**
I would expect the Sag Mill to act like any other ore processing machine here.

**Screenshots:**
n/a

**Additional context:**
I discovered this when I started running a Silk Touch Builder in the Deep Dark, where I'm getting some of this Mystical World Quartz Ore.  My current ore processing system uses Sag Mills.

**Comment by Atricos** [comment]
Fixed in 2.11.0.
