### ISSUE TITLE
Sacthoth's Soul Reaper Blade loses enchants when making Souls of the Dark realm

### ISSUE THREAD

**Issue by RexxyJ** [Divine-Journey-2/main#575]
**Modpack version:**
2.9.1

**Description:**
Sacthoth's Soul Reaper Blade loses its enchantments when crafting Souls of the Dark Realm with the Soul Extractor.

**Steps to reproduce:**
1. Enchant Sacthoth's Soul Reaper Blade (only way I've found to do this is with the mana enchanter from Botania).
2. Get a kill with the Blade so that it has a soul on it.
3. Craft it together with the Soul Extractor and take the Soul of the Dark Realm out of the Blade.

**Expected behavior:**
All enchantments remain intact.

**Additional context:**
I did shift-click all of the souls out at once. Unsure if that could have had an effect.

**Comment by Atricos** [comment]
Fixed in 2.11.0, the enchantments now remain intact.
