### ISSUE TITLE
Impetus Cannon damage buff

### ISSUE THREAD

**Issue by VeikkoV** [Divine-Journey-2/main#576]
**Modpack version:**
2.9.1

**Describe the request:**
A damage output buff to the thaumic augmentation impetus cannon (both railgun and burst variations)

**Reasons why this should be added:**
Very simply, it is the 2nd most expensive ranged weapon in the pack (putting all draconic evo bows into one category cos they all destroy worlds and cost more than my soul is worth to the devil), yet it is absolutely annihilated in damage output even by a normal vanilla minecraft bow when fighting anything with a health pool of above 30 hearts (single shot absolute max hit with the impulse railgun).
The burst focus has the rifle deal 3-4 damage on 3 quick consecutive hits on a few second delay between burst sequences, while the railgun focus has it deal 30 on very long delay hits (about 10 seconds between). These default values may sound great but they are way too low for how late you unlock the weapon. It takes over a minute to kill a skythern golem with the railgun focus at close range, and its not even worth testing with the burst as their armor value will just drop its damage to 1s and 0s.

The burst obviously should have lesser damage compared to the rail, as it has far greater RoF.
Even a general 10x multiplication would make the weapon viable, a 10x'd rail in this case dealing 300 damage every ~10s prior to factoring in enemys damage reductions like armor etc. (for reference a budget 0 sharpened signalum-restonia-nickel laser gun can kill a wither with 300 health in just 3-4 seconds)

The damage multiplication would be great way to make the weapon worth using as its a really cool one, but absolutely not worth its assembly cost when its out dps'd by a low power enchanted vanilla minecraft bow.

**Additional context:**
I'm totally fine w sticking to my budget laser gun (that can smack everything except for Arnie and Chuck Norris) if u dont like this idea.

**Comment by snowyrime** [comment]
I'd also like to put the Primal Cutter and most of the configurable Thaumcraft weapons and gears up for a possible adjust as well. They are simply obtained way too late to be of any real use without being tuned.

Perhaps this issue is better suited for Balance Requests?
