### ISSUE TITLE
Add the Translocators mod

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#577]
**Modpack version:**
2.9.1

**Describe the request:**
Add the Translocators mod.

**Reasons why this should be added:**
It is the best short distance transportation mod (1 block distance).

**Describe alternatives you've considered:**
Just don't add it. But all the other methods of transfer are slower and thus don't allow for efficient automation of quarries in one block.

**Comment by WaitingIdly** [comment]
ID is a stack per tick, per connection, meaning ID has a infinitely higher potential item transfer rate (as you are not capped to the 6 faces of a block) and an equal realistically expected transfer rate.

**Comment by KleinGrrmpf** [comment]
So per connection you mean I can just use more Phantomfaces to get more connections? Can't you do the same thing with translocators? But I get your point. I am not really accustomed to Integrated Dynamics, so I didn't know. Thanks :)
