### ISSUE TITLE
Superium Infusion Crystal doesn't get consumed in laser focus while crafting Supremium Infusion Crystal

### ISSUE THREAD

**Issue by BlackStone5677** [Divine-Journey-2/main#580]
Superium Infusion Crystal doesn't get consumed in laser focus while crafting Supremium Infusion Crystal, Same issue as https://github.com/Divine-Journey-2/main/issues/487, not fixed yet either, I doubt it is intended since the infusion crystals get consumed with the other crafting recipes so these 2 shouldn't be special in my opinion.
 
**Modpack version:**
2.9.1

**Steps to reproduce:**
1. Craft a supremium infusion crystal in a laser focus
2. The craft finishes successfully but you are still left with the superium infusion crystal

**Expected behavior:**
get consumed lol

**Comment by WaitingIdly** [comment]
Duplicate of #487
