### ISSUE TITLE
EnderIO Crashes on start

### ISSUE THREAD

**Issue by Jumbeer** [Divine-Journey-2/main#582]
![unknown](https://user-images.githubusercontent.com/74884201/145094609-283504cc-7a6c-4aeb-8c35-e3e04f867492.png)

Me and my friend downloaded the modpack from the curseforge client, its all good for me, but for him, that crash happens

**Comment by KleinGrrmpf** [comment]
Have you tried the classic "turn it off and on again"? Just redownload the pack. My first guess is that some EnderIO file did not download correctly.

**Comment by Jumbeer** [comment]
> 

Yes, it also happened to have duped ender IO files, removed it and still the same error

**Comment by Atricos** [comment]
Delete and redownload the whole pack. Multiple things may have corrupted.

**Comment by WaitingIdly** [comment]
taiga is not in this pack, so it must have been a corruption in download. presumed resolved.
