### ISSUE TITLE
Reduce Alchemical Machine Frame energy cost per tick!!!

### ISSUE THREAD

**Issue by realthecaffiend** [Divine-Journey-2/main#583]
2.8.0

**Description:**
The above mentioned quest indicates that it is "recommended" to upgrade your laser focus to a higher energy hatch; This is incorrect, it is *required*. The alchemical frame recipe requires 128,000 fe/t, the huge hatch you would have at that point only accepts 32,767. Worse, the laser consumes the input items and then says not enough energy; Making the next tier of energy hatch, unless you happen to have parts such as draconic energy cores laying around, requires... Using the laser. Your options at this point seem to all result in: Losing the resources spent on an alchemical frame (Or building a second laser which is ridiculous). This quest should say, in bold, that this is required, perhaps a dependency on a new quest to make a new hatch. Alternatively, if the bigger hatch could be made without using the laser, it would be a roadblock, not such a large problem. 

**Steps to reproduce:**
Follow the required questbook line until attempting to make an alchemical machine frame

**Expected behavior:**
Quests not to lead players into a "broken" state requiring an upgrade they cannot do without breaking a multiblock and wasting what is, at the time, very valuable resources.

**Comment by Atricos** [comment]
I changed the title so I'll remember to actually work on this.

**Comment by Atricos** [comment]
I *did* remember to work on it. In 2.11.0, the inputs for the Alchemical Machine Frame will no longer be consumed when trying to craft it. Also added a large red warning tooltip for the next tier of Machine Frame.
