### ISSUE TITLE
Dim shard on servers require making dimensions

### ISSUE THREAD

**Issue by Tenchu98** [Divine-Journey-2/main#584]
Most server ban all rftools dimensions, so there should be a recipe alternative to get shard or the ore. Even if it required using the laser drill in a specific biome so it remains gated. Otherwise the pack can't be completed on most servers.

**Comment by WaitingIdly** [comment]
Please follow the issue format when making an issue.
If a server bans RFTools Dimensions, the onus is on the server to add an alternative recipe for the shards/ore.
