### ISSUE TITLE
Crash in game [Fatal Error]

### ISSUE THREAD

**Issue by Lenile** [Divine-Journey-2/main#586]
**Modpack version:**
2.9.1

**Java version:**
Latest

**Description:**
I can't launch my game, a fatal error has occuried 

**When did the crash happen?**
When entering i nthe world

**Steps to reproduce:**
Open the game / Start the modpack / Get into a world / ...

**Minecraft crash report:**
[latest.log](https://github.com/Divine-Journey-2/main/files/7712854/latest.log)

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
I dedicated 10 GBs and my PC has 16 GBs of RAM.

**Screenshots:**
![image](https://user-images.githubusercontent.com/96131223/146029266-339cf33a-ea9c-4de6-ae11-07477a7c086e.png)
I crash after that

**Additional context:**
I was in the nether, doing some exploration quest

**Comment by WaitingIdly** [comment]
in your log, `Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51`. that version is five years old.

**Comment by Lenile** [comment]
I downloaded the latest version of java on https://www.java.com/

but is still crashing. 
![image](https://user-images.githubusercontent.com/96131223/146046368-9b71fc14-0433-4d8f-aaab-7cbc8eb0195d.png)
(Sorry it's in french. )

**Comment by WaitingIdly** [comment]
just because you downloaded it, doesnt mean you're using it. curseforge ignores it to always use 0_51. switch to multimc.

**Comment by Lenile** [comment]
I don't understand why I am having trouble now when I have had it before.

Isn't it more because of a backup problem?

When I open another backup I have no problem.

**Comment by Lenile** [comment]
Crash with MultiMC too.

**Comment by WaitingIdly** [comment]
Could you join the discord https://discord.gg/Hg4qsmRQ and ask for help in the tech-support channel, where help can be more easily rendered?
