### ISSUE TITLE
Chests show incorrectly in crafting station

### ISSUE THREAD

**Issue by R3Ked** [Divine-Journey-2/main#587]
**Modpack version:**
2.9.1

**Description:**
When you place a chest in a crafting station, it shows the black and pink checkerboard missing texture.

**Steps to reproduce:**
1. Get into a world
2. Get the item Chest
3. Place it into a crafting station
4. The chest shows the black and pink checkerboard.

**Expected behavior:**
The chest displays correctly.

**Screenshots:**
![chest](https://user-images.githubusercontent.com/20342336/146470893-46a2ff5d-f79a-4906-b575-a83e6f646905.png)

**Additional context:**
I was crafting a drawer when this happened. The screenshot shows the crafting recipe of said drawer.

**Comment by Lgmrszd** [comment]
This is a known issue with Tinkers' Construct on 1.12 and it won't be fixed: https://github.com/SlimeKnights/TinkersConstruct/issues/3599

**Comment by R3Ked** [comment]
ok closing i guess
