### ISSUE TITLE
Laser multiblock charging better solution

### ISSUE THREAD

**Issue by realthecaffiend** [Divine-Journey-2/main#589]
**Modpack version:**
2.8.0

**Describe the request:**
A second-stage laser multiblock charging solution

**Reasons why this should be added:**
I'm working through chapter 29 and the laser just keeps being a roadblock due to charge; I get the initial solution of just slap down more lasers, and that's neat to start with, but I already have 50. It's really boring and tedious to simply build more and more and more non-stacking lasers (Especially given the annoyance of the possible block damage). I would love to see... A laser pre-charger multiblock, an "Advanced" laser that adds more power (As the default mek ones have a simply pitiful rf/t cap), some other way of applying heat, a way to increase the 5GJ buffer on the laser even? Anything except: simply add 200 more lasers(Honestly, I doubt 200 more would even keep up). IMO, solutions of "just copy this 100+ times" aren't great gameplay, especially with how annoying to setup these in particular are. 

**Describe alternatives you've considered:**
A second laser multiblock: However, this doesn't at all solve the problem. It would be nearly functionally equivalent to take all of the lasers used for the second block, and add them to the original. The buffer just becomes not very material later. 

**Additional context:**

**Comment by KleinGrrmpf** [comment]
I like the idea of having a second multiblock that is just a giant laser which can then power the laser focus multiblock. But unless there are output hatches for the laser in the mod (which are disabled or hidden in JEI) I don't think it is possible...
There is a config option for the laser throughput in the mekanism config file which is currently set to 5kJ/t. I don't know what the conversion rate to RF that is. And if you were to pump that rate up, it would also be available in the earlier stages of the multiblock.

**Comment by realthecaffiend** [comment]
Hey, the server is shut down now since I finished the pack a while ago, so I don't have a screenshot; However due to the symmetry of it, I think I had 11 of the laser consolidators so 44 lasers+ 1 around those, in a line, and then three more directly into the multiblock? This would mean I technically lied and had 48 when I was constantly running out.

The solution later that was expensive and annoying was to just build the lasers and some other multiblocks in an awful 3D clump so as to wedge as many of them into the AOE of a watch of flowing time pedestal as I could. It wasn't at all pretty and nearly got to the point I had to use a travel staff to get inside to look at/change anything, but applying the watch to ~40 of them did finally keep up to demand; That would be, if I am remembering the time multiplier in this pack correctly, the equivalent of something in the area of 700 lasers which does seem excessive. Note of course it may have been overkill by then, but I was sick of ever running out :)

**Comment by Atricos** [comment]
I could reduce the Laser energy costs.

**Comment by realthecaffiend** [comment]
Yep that's a potential, I didn't mind the energy costs, or even the resource costs, just the fiddly laser-placing... Especially because if I accidently charged one of the lasers wirelessly, placing it becomes a bit of an adventure. Alternatives could be a second-stage multiblock of some form, incorporating the previous one with some "attachment" to charge it faster? I didn't see any sort of "advanced" laser in Mek, sadly, just more and more concentrators feeding into each other.

**Comment by Atricos** [comment]
I reduced the Laser energy costs in 2.10.0. The Laser placing might be a bit "fiddly", but it's nothing you can't do after 24 completed chapters ;)
