### ISSUE TITLE
Version 2.9.1 Server files seem to be bugged

### ISSUE THREAD

**Issue by Ricky2148** [Divine-Journey-2/main#595]
**Modpack version:**
2.9.1

**Description:**
So I'm trying to run the modpack on a pebblehost server. I have correctly followed all the steps to setup a modpack and have done everything right, so it's not that I have set up the server wrong. Everytime I try to startup the server and set up the initial modpack for the server, the console gives various errors, and always stops at this certain point. https://mcpaste.io/d9c9f0575bf6d48c. The link is a mcpastebin link that shows the last lines of code that has been shown everytime I try to set up the server. Other errors say that a certain mod is expecting a signature, there are also various parsing errors and whatnot.

**Steps to reproduce:**
1. https://www.youtube.com/watch?v=5rCQ6k7AWzY
2. Follow this video. The issues occur when you start the server after saving with the forge installer, after you have already saved the server with the minecraft server installer, and started the server.

**Expected behavior:**
Have the server files correctly setup the server and allow me to use it as a playable server.

**Screenshots:**
If applicable, add screenshots to help explain your problem. These can also be attached to the "Description" or "Step to reproduce" sections. If you have no screenshots, this part can be removed.

**Additional context:**

**Comment by luciscout** [comment]
24.12 05:42:02 [PebbleHost] Skipped 1644 lines due to rate limit (500/s)
This is present in the small portion of log you posted, and the fatal error is not shown. In order to properly troubleshoot this the full log would be required. You can redownload the pack and try with fresh files, but otherwise there's no information here. Consider joining the discord to properly troubleshoot this

**Comment by Ricky2148** [comment]
I don't know how I would be able to show you the full log of all that happens, do you think that if I sent you a full log, you could troubleshoot it properly? And if you think that you can, can you tell me a way to capture a full log?

**Comment by Atricos** [comment]
Try one of the later versions, they have more bugs fixed anyway.
