### ISSUE TITLE
Xnet for automation

### ISSUE THREAD

**Issue by Tenchu98** [Divine-Journey-2/main#596]
I would like to officially request that xnet be added to the pack. This mod can be used to automate Ae2 with less spaghetti cabling.

**Comment by luciscout** [comment]
Please use the issue template.

**Comment by Tenchu98** [comment]
I don't see any template for making suggestions or feature requests, let alone an issue template.

**Comment by Lgmrszd** [comment]
![изображение](https://user-images.githubusercontent.com/16291541/147369833-da501885-643a-45e9-8de5-203683fcf179.png)
It's right there. when you create new issue

**Comment by Tenchu98** [comment]
I didn't get prompted with that, but I will try again
