### ISSUE TITLE
Game freezing when opening inventory.

### ISSUE THREAD

**Issue by splyfof** [Divine-Journey-2/main#597]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.9.1

**Description:**
After playing for a while my game freezes permanently when i open my inventory, i think it might have something to do with player data of some type

**Steps to reproduce:**
1. Get into a world
2. Play for a while
3. Open inventory
4. Game freezes

**Expected behavior:**
I expected it to not freeze my game and let me play

**Additional context:**
This bug has also happened with po3 at some point
[latest.log](https://github.com/Divine-Journey-2/main/files/7781443/latest.log)
![dwm_Rqt1Mpie57](https://user-images.githubusercontent.com/83120236/147499996-18ba4298-b464-4bf8-92e8-1bdbcd11a3bf.png)

**Comment by splyfof** [comment]
i would like to add that im using gdlauncher
and here is the whole minecraft folder
https://drive.google.com/drive/folders/1_n51xAUg1a6sFBVcHARt-CcOSMHi49fb?usp=sharing

**Comment by splyfof** [comment]
whoops wrong button, sorry

looks like its cause too big of a player.dat file

**Comment by LittleCircles** [comment]
Did you try what I told you todo in the DMs? Take your player data file out and reload the world and see if it still happens? Because, if it still happens it has nothing todo with your player data. And if it isnt, we cant do anything and this aint a bug?

And also, your launcher has nothing todo with the possible bug.

**Comment by splyfof** [comment]
I fixed it by deleting the inventory entry in my player.dat file (please make a backup if you are gonna try it) and that fixed it
