### ISSUE TITLE
Farming Station Crop Stick bug

### ISSUE THREAD

**Issue by YuToxic** [Divine-Journey-2/main#602]
**Modpack version:**
1.12.2

**Description:**
Farming stations trying to harvest crops from Crop Sticks like Sugarcane will make the server/world crash.

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Get the item ... / Go to ... / Open the ... / Place a ... / Break a ... / ...
3. ...
4. ... doesn't craft correctly. / Can't get the ... / ... can't be completed. / ...

**Expected behavior:**
I expected the crops to be harvested like any other crop that has been planted on normal farm land.

**Screenshots:**
![image](https://user-images.githubusercontent.com/68398249/149571024-62578519-1f4f-481c-8ed6-c4f89884685c.png)

**Additional context:**
If there is a possibility for this to be fixed or removed so no one else get this to happen to them. Or even add a WARNING to the Farming Station Quest

**Comment by Atricos** [comment]
Added a Warning tooltip to the Farming Station and its quest. Added alternatives to use. I can't do much more than that.
