### ISSUE TITLE
Crash when entering the game

### ISSUE THREAD

**Issue by Dimon1231231231** [Divine-Journey-2/main#604]
**Modpack version:**
2.9.1

**Description:**
Crash when entering the game

**Steps to reproduce:**
1. Open the game / Start the modpack / Get into a world / ...
2. Get the item ... / Go to ... / Open the ... / Place a ... / Break a ... / ...
3. ...
4. ... doesn't craft correctly. / Can't get the ... / ... can't be completed. / ...

**Expected behavior:**
Game launch

**Screenshots:**
[click](https://imgur.com/a/NJhKG1d)

**Additional context:**
I am also attaching the crash log.
[crash-2022-01-21_18.54.42-client.txt](https://github.com/Divine-Journey-2/main/files/7914995/crash-2022-01-21_18.54.42-client.txt)

**Comment by Atricos** [comment]
Please specify
- your exact allocated RAM
- how much RAM does your PC have in total
- what is your Java version
- what launcher are you using.

**Comment by WaitingIdly** [comment]
no response provided
