### ISSUE TITLE
AE2 randomly stops working for a second

### ISSUE THREAD

**Issue by RealLith** [Divine-Journey-2/main#605]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.9.1

**Description:**
An AE2 system would randomly stop working.
Started happening when ae2 system was expanded with multiple p2p channels and 2 quantum rings.
The energy storage has been expanded to supply the suddent energy cost to 580M rf (Photo: https://imgur.com/a/mDYpDkj)
The energy usage is around 6k rf/t (same as generation). 
The max generation can reach up to 120k rf/t (its 6k since thats the amount is being used (same picture))

also, the ME controller (thats all energy is connected to) also turns off suddently (becomes black) as if the energy would be 0 :| but clearly there is 500M rf capacity.

Regardless if you manually use the system or not - it would randomly shut off and then back on again.
The dense energy cells (181 placed) still all contain energy without an issue.
This happens randomly - sometimes few times an hour, sometimes few hours no issues.

**Steps to reproduce:**
1. Have a big AE2 system with p2p
2. have multiple passive crafting rooms (using interfaces for items output and storage busses for drawers)
3. wait for it out of nowhere turn off

**Expected behavior:**
With just the capacity of the dense cells (since they are full) it should have no issues to supply the me system with energy for like 10 hrs without turning off nor being charged back up.
There is no expectation to why it should suddently turn off.
So it should be running smoothly (yes all chunkloaded)

**Screenshots:**
https://imgur.com/a/mDYpDkj

**Additional context:**
Has happened to others too (talked on DJ2 discord)

**Comment by King65868** [comment]
Are you sure every part of your ae system is chubkloaded?

**Comment by RealLith** [comment]
Yes. everything is chunkloaded. I have a 3x3 chunk base and 5x5 chunks are fully chunkloaded.

**Comment by King65868** [comment]
With that behavior, the common issue is that your ae system isn’t all chunkloaded. Do you have areas outside your 3x3 chunk base that your ae system is in? Even 1 cable outside the chunkloaded area can cause issues. 

Did this just start recently?

**Comment by RealLith** [comment]
I have a 3x3 base chunk base onside the void dimension. The ME controller is in the center chunk.
There are no cables (of any kind) nor anything outside the 3x3 area.
It's 5x5 chunk loaded.

There are 2 quantum rings connected both to overworld. Both sides of quantum ring, and its content, is chunk loaded.

This started few weeks ago when I added my first quantum ring. But it was only happening at the output end and only when I relog (when offline, chunk loaded chunks don't load). Suggestion, from dc, was to put dence cells around the quantum ring. That helped and the issue was fixed.
Did the same with my second quantum ring the other day and the issue (described above) started happening and ONLY happening to the main system (void dimension, the input side of both quantum rings).

This also happened regardless where I am - in the middle of my base (on the controller) or literally anywhere else.

Everytime it starts breaking - it does it alot. So I place 10 more dense cells. And for some time it's good without turning off.
After I place few more p2ps (or sometimes without me doing anything to me system) it starts turning off and on again (like described) every like 30 mins until I place down my dense cells.

Max capacity is right now around 600 M (paced more) and usage is still less then 6k.

One theory I found was the AE2 modifying mod (throusers or whatever its called?) bugs it for me system to require at once a large sum of energy that the system can not provide (in billions or trillions of rf) so it shuts down without even consuming the existing energy.
But I can not confirm nor deny this theory.

**Comment by RealLith** [comment]
In addition, should inform the server has 2 extra mods installed - framed compacting drawers and architecture craft.
Both are just more pretty blocks so it has nothing to do with me nor power.
So can't be an issue.

Additionally, one user from dj2 discord also said he has the issue as me.
And before (roughly 2 weeks ago) user, who suggested the dense cells thing) said it too but for him adding few thoughts of dense cells fixed it. So I'm not alone with the issue.
And if few thoughts of dense cells fixes the issue - that theory seems more likely, dosent it?

**Comment by RealLith** [comment]
And yes, it's on a public server (hosted). Not singleplayer.
I probably should have mentioned that.
I don't mind giving a tour (discord shared screen, video, or even in person (game)) if it's required/would help.

**Comment by WaitingIdly** [comment]
known issue with the current version of ae2 trousers, and fixed like 2 versions ahead of the one in 2.9.1. will be resolved in the next release, when it is updated to the version published on curseforge: https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life

**Comment by KleinGrrmpf** [comment]
So we are changing to this version of AE2 in the next update?

**Comment by Atricos** [comment]
Updated AE to Extended Life v50 in the most recent (2.11.0) update, which hopefully fixes these issues. I'm going to close this thread now. If the issues still occur, feel free to reopen it.
