### ISSUE TITLE
Can't craft iron plates with iron hammer from Contenttweaker

### ISSUE THREAD

**Issue by M4pfl** [Divine-Journey-2/main#613]
### Modpack version

2.9.1

### Description

I can't craft iron plates with the hammer from Contenttweaker. I need them to craft stuff for the smeltery.

### Steps to reproduce

1. Open the game
2. Get the items iron ingot and iron Contenttweaker and craft iron plates
3. doesn't craft correctly.

### Expected behavior

It should craft iron plates like the recipe shows.

**Comment by KleinGrrmpf** [comment]
I don't think you are supposed to be able to craft iron plates with that hammer. You need to use an IE hammer for that

**Comment by M4pfl** [comment]
But this hammer also needs an iron plate

**Comment by King65868** [comment]
The iron hammer is the one you make plates with, are you using 2 ingots to make the plate?

**Comment by M4pfl** [comment]
yup, like the recipe says

**Comment by King65868** [comment]
Are you doing it in a crafting table or your inventory?

**Comment by M4pfl** [comment]
I tried both, but none of them is working.

**Comment by King65868** [comment]
Try reinstalling the pack then I guess

**Comment by M4pfl** [comment]
ok I will try it.

**Comment by M4pfl** [comment]
still doesn't work after reinstalling modpack.

**Comment by M4pfl** [comment]
ok, so it only doesn't work on our server. In singleplayer I can craft it.

**Comment by WaitingIdly** [comment]
then your server needs to reinstall the pack. scripts being missing isnt an uncommon error (its a big pack, curseforge can "forget" to download files occasionally), and the only fix for that is to reinstall. typically its easier to spot because the issue occurred clientside instead of serverside, and thus doesnt appear in JEI.

**Comment by M4pfl** [comment]
ok thanks, we will try it and i report, if it works.

**Comment by WaitingIdly** [comment]
presumed resolved after 2 months of no followup
