### ISSUE TITLE
Extended Processing Pattern Terminal shows up as Disabled Item

### ISSUE THREAD

**Issue by KleinGrrmpf** [Divine-Journey-2/main#620]
### Modpack version

2.11.0

### Description

The Extended Processing Pattern Terminal shows up as Disabled Item in the quest book and doesn't show up at all in JEI.

### Steps to reproduce

Open the questbook and navigate to the quest in chapter 13.

### Expected behavior

It shows up in the quest book and JEI.

### Additional context

![grafik](https://user-images.githubusercontent.com/50833808/153731916-1b2392e4-04a2-4279-8e54-633171f55855.png)

**Comment by Atricos** [comment]
2.11.0 isn't officially out yet. It seems you just haven't updated AE2 to the new version provided.

**Comment by KleinGrrmpf** [comment]
I fetched the newest version from GitHub...

**Comment by KleinGrrmpf** [comment]
Fixed it. Apparently everything except for the new mods got fetched from GitHub. Is that not a possibility anymore or has that never worked?

**Comment by Atricos** [comment]
CurseForge does not allow for mod redistribution outside of its website, so the mod files themselves are no longer available here.
