### ISSUE TITLE
Efficiency rune hidden from JEI?

### ISSUE THREAD

**Issue by hardstylefox** [Divine-Journey-2/main#621]
### Modpack version

2.10.0

### Description

![image](https://user-images.githubusercontent.com/99778476/154186037-9fad1e37-f12c-4bd0-ba17-9cda1339458e.png)

You can still check the uses on the mana rune and see the efficiency rune recipe.

### Steps to reproduce

1. Search for efficiency rune in JEI
2. doesnt show up

### Expected behavior

efficiency rune should show up

**Comment by KleinGrrmpf** [comment]
Can confirm.

**Comment by Atricos** [comment]
Unhid it in 2.11.0. I don't know how it got hidden, but fixed it now.
