### ISSUE TITLE
transposer fill recipes 

### ISSUE THREAD

**Issue by sinandds** [Divine-Journey-2/main#634]
### Describe the feature

the transposer fill recipes are hard to navigate there are a million of the same recipe such as treated wood and sooty marble  and it would be nice if it were just the basic oak planks and basic marble recipes for said items

### Reasons why this should be added

because its annoying looking through 117 pages only to find treated wood and sooty marble recipes

### Describe alternatives you've considered

.

**Comment by WaitingIdly** [comment]
currently we add these recipes via [simply iterating through the oredict](https://github.com/Divine-Journey-2/main/blob/fd653fbd00db8a74dca715bdaec4fc2fa74e43ed/overrides/scripts/ImmersiveEngineering.zs#L38). this change would require us to create a local array (which has the ability to introduce issues via oversights). so, this cant be done without significantly changing how we add these recipes.
additionally, the community has consistently raised issues that indicate that changing it from "all x" to "some x" would be undesired. finally, it is at most inconvenient, and you can easily find the recipe for the other items via simply looking for their recipe directly - and as such have no reason to need to scroll through 117 pages.

as such, i believe the suggested change is an unneeded and negative one.
