### ISSUE TITLE
New AE2 version breaks crafting recipes with items that don't get used

### ISSUE THREAD

**Issue by hardstylefox** [Divine-Journey-2/main#640]
### Modpack version

2.12.0

### Description

![image](https://user-images.githubusercontent.com/99778476/158637783-b7ee929e-d8ea-4505-bc1a-6f02291bd6b1.png)
![image](https://user-images.githubusercontent.com/99778476/158637854-4dc77d35-2149-4fec-b9dc-24a2d75a07e0.png)

### Steps to reproduce

1. Create a pattern such as a bifrost block or blank rune with the correct items
2. Try to craft it

### Expected behavior

On previous versions of extended life crafts like these worked perfectly fine with no issues

### Additional context

According to WaitingIdly, its fixed by updating extended life

**Comment by Atricos** [comment]
Fixed in 2.13.0.
