### ISSUE TITLE
Quest - a little bit of Paradise - #1519

### ISSUE THREAD

**Issue by Arando1990** [Divine-Journey-2/main#647]
### Modpack version

2.13.0

### Where is the typo located?

14th Chepter - the Quest - a little bit of Paradise - #1519 

### Exact fix

![image](https://user-images.githubusercontent.com/20774626/160238405-b8c5f064-1e93-4513-b96d-47662bd19986.png)
--- the Quest says that u can Reuse a Spawner but there is no Spawner for the Boss -> Only a Golden Block with a Button that disapired after use meaning that the Eden Chunks are Useless

**Comment by luciscout** [comment]
This is not a typo. There are spawners that exist outside of the dungeon, in small structures around Eden.
