### ISSUE TITLE
Add localization for custom bewitchment rituals

### ISSUE THREAD

**Issue by Tom4455** [Divine-Journey-2/main#73]
**Modpack version:**
beta-version-0.1

**Describe the request:**
Add localization for custom bewitchment rituals

**Additional context:**
![image](https://user-images.githubusercontent.com/8618678/128740516-8c9bb544-1745-45a1-88b8-ab2d228dfbaf.png)

**Comment by Atricos** [comment]
The localization was added through `resources/moretweaker/lang/en_us.lang`. Thank you to @l4ssc for showing me how to di it.

**Fixed in 2.2.0:**
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
